### ISSUE TITLE
1.16.1: Unicode and escaped unicode not working in formatting.yml,messages.yml,etc

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#1780] opened 2020-08-02 19:57 UTC
Chatcontrol Pro 8.6.8
Paper-131 (1.16.1)

formatting.yml:
Currently, if any escaped unicode is included, that element will not be displayed at all.  If an unescaped unicode character is included, no chat will be displayed ever again, no errors will be given, nothing even written to error.log, there will just be NO CHAT.

messages.yml:
if A unicode character is included, the message will not display.   If escaped unicode is included, it will display the actual escape code into chat instead of the intended character.

**Comment by JavaFactoryDev** [comment] 2020-08-04 12:41
Hi,

I am sorry for the delay.
Once the infrastructure upgrades are done I will personally take responsibility to fix this issue. 

I am sorry for the mess.

Regards,
Leonhard

**Comment by mrcoffee1026** [comment] 2020-08-04 16:12
No worries, do whatever you gotta do, just happy to see things being worked on. Appreciate all the hard work!

**Comment by kangarko** [comment] 2020-08-04 18:51
Hey, 

Stupid question since I could test it myself, but to save some time could you upload an example file to reproduce?

Matej

**Comment by mrcoffee1026** [comment] 2020-08-04 18:59
There are no stupid questions, only really stupid answers.  But yeah I was trying with these:

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/5023951/ChatControl.zip)

This may not work for you since not every implementation will actually show one of the intended icons.  There's an escaped one in the first timed message and I was tinkering with the marry prefix... should be able to reproduce it if you have that plugin and set a gender.  But even when this was partly working in prior builds it failed differently in different places, like it would show the correct character if I returned that character in my javascript.txt and the javascript custom variables were working... but if I placed the character directly into the formatting.yml it would display a different character instead.  If I used an escaped version of that unicode it would display the same incorrect character.  And at one point if I put any variation of the character in the hover action text it would not display everything EXCEPT for the unicode I placed there.  So you'll probably still have to test since it does different things everywhere each time I try it.

**Comment by mrcoffee1026** [comment] 2020-08-04 19:42
Also everything I have in javascript.txt if that would also help:
`
# Getting player's ping.
define {ping}
script:
  player.getHandle().ping;
  
  
define {marry}
script:
  function gethover(){
    var thetext = ''; 
    if ('{marriage_partner}' > '') { 
      thetext += '\n&7Partner&8\u003A {marriage_partner}';
    } 
    return thetext;
  } 
  gethover();

define {gender}
script:
  function getgender(){  
    var theprefix = '';
    if ('{marriage_gender}' == 'male') { theprefix = '&l&9\u2642&r';}
    if ('{marriage_gender}' == 'female') { theprefix = '&l&d\u2640';}
    return theprefix;
  } 
  getgender();

`

**Comment by kangarko** [comment] 2020-08-05 18:23
Works on 1.8.8 but broken on 1.16. Apparently they've changed something in Spigot. The 8.x.x however, is a mess, so I'll be focusing on putting this feature in a fully functional state to 9.x.x. Until then, you can explicitly just paste the symbol there instead of the unicode escape letters. 

I prepared an updated guide on doing this: https://github.com/kangarko/ChatControl-Pro/wiki/Frequently-Asked-Questions#my-emoticons--are-just-showing-as---unicodes--special-characters-not-working

Matej

**Comment by mrcoffee1026** [comment] 2020-08-06 01:36
Ok, I'll try with the characters directly in, but that was failing before: either the line containing the unicode wouldn't print or it would simply print the wrong character... if you did anything differently then maybe at least that much is working as expected again, I'll have to give it a try.

**Comment by mrcoffee1026** [comment] 2020-08-06 15:03
No, putting the unescaped unicode directly into formatting will result it just skipping over that character entirely, it will not display the character.

**Comment by kangarko** [comment] 2020-08-10 14:58
Hey, sorry but that must be an odd issue rather on your side, or I was not able to reproduce this on MC 1.16.1:

![a](https://i.imgur.com/ZxTbwcX.png)

**Comment by mrcoffee1026** [comment] 2020-08-10 15:11
Yeah you're right, it was the resource pack messing it up, thank you!

**Comment by AngellitoX** [comment] 2020-08-10 16:24
Hello. Nice to know it's fixed.

I am closing this ticket as it's solved.

Thanks a lot for bringing so many stuff coffee. Really appreciate that you take your time for this. Have a good one!

**Comment by mrcoffee1026** [comment] 2020-08-10 16:27
It's not truly "fixed", unicode and escaped unicode still do not work in many files... but if you prep it in javascript and return the actual unicode as a value into formatting... THEN it will display, and only then.  Even under those conditions "/n" returned from javascript still prints as "/n" when rendered in formatting.yml even though it should be shown as a new line instead.  So not fixed, but a workaround is present for SOME of it.   Thanks again for all the hard work.

**Comment by kangarko** [comment] 2020-08-13 16:59
Thanks, please be specific --> when does the unicode not work?

Also I replied to your issue regarding \n elsewhere, please stick to one issue per ticket.

**Comment by mrcoffee1026** [comment] 2020-08-13 17:03
When last tested escaped unicode still doesn't work in formatting.yml or messages.yml ... I believe you stated this would be dealt with in chatcontrol 9?  If you want to close this till that release that's fine with me.

**Comment by kangarko** [comment] 2020-08-13 18:12
Got it, yes I want to deal with this in the next branch.

**Closed by kangarko** 2020-08-13 18:12 UTC
Labels: issue
