### ISSUE TITLE
Bungee chat not broadcasted in console?

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1496] opened 2019-12-29 10:46 UTC
Hey,

I have 3 servers, Survival / Creative / Lobby. They are all using the bungee chat (global chat)
But the messages only show up in the console of Survival (since that's where they mostly message)
Sometimes a message randomly shows up in the console of the others, but most of the times it doesn't.

What could this be?

**Comment by lackoSK** [comment] 2019-12-29 16:51
Have you followed the tutorial for the bungeecord and installed BungeeControl well?

**Comment by Sikatsu** [comment] 2019-12-29 16:55
Yes, I have. In-game it works fine, but it's not really being broadcasted to the other consoles.

**Comment by lackoSK** [comment] 2019-12-31 18:54
What do you mean by broadcasting to other consoles? Not sure. Use:
```

# -------------------------------------------------------------------------------------------------
# Announce important messages with the "/chc announce" command.
# You can customize the format in localization.
#
# TIP: Use {receiver} variable in the message to replace it to each player's name!
# -------------------------------------------------------------------------------------------------
Announcer:
  Bungee: true
  Ignore_Self: false
  Log_To_Console: true
```

**Comment by Sikatsu** [comment] 2019-12-31 19:03
That's what I have. So, for example, people are messaging on the survival server.
It is being broadcasted to the console of the creative server too, but then suddenly stops out of nowhere.

As you see here, the last message was 19:23 that is shown in the Creative console. [http://prntscr.com/qhz7ug]

However in the survival console the last message is 20:02 (which is now) [http://prntscr.com/qhz7z7]

So for some reason it stops broadcasting to the other servers consoles after a while.

If you understand what I mean?

**Comment by Sikatsu** [comment] 2019-12-31 19:04
With broadcast I mean log to console.

**Comment by lackoSK** [comment] 2020-01-01 11:39
Can you test the ChatControl plugin alone on the server? Some 3rd party plugin may cause it.

**Comment by Sikatsu** [comment] 2020-01-01 11:44
I did actually, since I just transferred to a dedicated server. The issue persists that after a while it won't log to the console anymore except for the console of the server the messages are actually sent.

**Comment by lackoSK** [comment] 2020-01-02 17:38
Can you explain it? Don´t get it.

**Comment by Sikatsu** [comment] 2020-01-02 21:40
Was it not clear enough a few messages back?

After a while it stops logging the bungeechat to other consoles then the survival console. As if that console loses connection.

**Comment by kangarko** [comment] 2020-01-07 19:23
@lackoSK please get back to this and investigate, contact me if you need a call

**Comment by kangarko** [comment] 2020-01-11 18:10
@Sikatsu 
Please set "debug" of BungeeControl's config to ["bungee"] and Debug key of ChatControl's settings.yml to the same value and report the messages when the problem happens from your Bungee and Spigot consoles here please. 

Thank you and apology for the delay.

**Comment by kangarko** [comment] 2020-01-18 17:29
Closing due to no response, just comment below and we'll continue

**Comment by Sikatsu** [comment] 2020-01-18 17:50
Sorry, I forgot to reply.

The bungee chat does never show up in the bungee console, didn't even know that was possible. My main issue is that when people on the survival server speak, after a while it just stops logging it to the console of the Lobby and Creative.

Survival (last message 18:48)
![image](https://user-images.githubusercontent.com/5664135/72668077-3c68f800-3a23-11ea-8027-954572c28751.png)

Lobby (last message 18:27)
![image](https://user-images.githubusercontent.com/5664135/72668084-4a1e7d80-3a23-11ea-808f-ea3036c638e2.png)

Creative (last message 18:25)
![image](https://user-images.githubusercontent.com/5664135/72668092-5e627a80-3a23-11ea-93c4-a6d48f4c65ba.png)

After a while it usually continues again and then breaks later. It's really odd.

**Comment by lackoSK** [comment] 2020-01-21 18:04
Hey.

That seems like a stranger issue. 

If user sends a message to the bungeechat (global) the message is delivered to bungeecord, and from time to time it stops writing to other server' consoles?

Am I right? 

Regrads,
lackoSK

**Comment by Sikatsu** [comment] 2020-01-21 18:42
Basically that's it indeed. But it shows up in the survival console always.

**Comment by lackoSK** [comment] 2020-01-24 17:08
Okay, zip as your our ChatControl's folders, include bungeecord's one. Thanks

**Comment by kangarko** [comment] 2020-01-25 18:51
@Sikatsu apology for the delay.

From what I know it can be caused by Multicraft or another plugins. If you use Multicraft, ensure this option is disabled: https://i.imgur.com/tCbSuit.png

Next, does it happen if you remove ChatControl? I know this is crucial for your server but maybe you can run with another chat plugin for a short amount of time to confirm this wont happen with CCP installed.

**Comment by Sikatsu** [comment] 2020-01-25 19:59
I'm using the Pterodactyl panel. It happens since I moved over to Bungeecord with ChatControl and BungeeControl. Before that it was working fine. Moving to another chat plugin to see if it's CCP is going to be quite some work, as i'd have to do it for all servers.

Do I still need to zip my chatcontrol folders?

**Comment by kangarko** [comment] 2020-01-26 11:35
> It happens since I moved over to Bungeecord with ChatControl and BungeeControl. 
Can you be more specific? What exactly has changed please?

**Comment by Sikatsu** [comment] 2020-02-03 13:10
@kangarko Before that I wasn't using bungeecord and the messages where just broadcasted to the console. Since moving over to Bungee and the Bungeechat this issue started happening.

Do I still need to zip my chatcontrol folders?

**Comment by lackoSK** [comment] 2020-02-03 19:11
Hey, 

Well, provide us:

ZIP your our ChatControl's folders, include bungeecord's one

Please set the "debug" of BungeeControl's config to ["bungee"] and Debug key of ChatControl's settings.yml to the same value and report the messages when the problem happens from your Bungee and Spigot consoles here, please.

Thanks
lackoSK

**Comment by Sikatsu** [comment] 2020-02-09 13:46
For some reason I don't get notifications from this github issue. Working on it now.

**Comment by Sikatsu** [comment] 2020-02-09 15:22
Lobby console: https://pastebin.com/a1P4fMYM
Creative console: https://pastebin.com/BaE3Cfpq
Survival console: https://pastebin.com/2iG3T0D5

You can see that the survival console continues logging messages from the bungeechat.

Lobby's last logged message was ''xd''
Creative's last logged message was "is niet meer nodig"

[ChatControl Issue.zip](https://github.com/kangarko/ChatControl-Pro/files/4177076/ChatControl.Issue.zip)

I'm using the bungee chat from settings.yml

**Comment by lackoSK** [comment] 2020-02-10 17:39
Can you also debug BungeeCord?

**Comment by lackoSK** [comment] 2020-02-10 17:39
@Sikatsu

**Comment by Sikatsu** [comment] 2020-02-10 17:48
I tried, but I believe bungeecontrol reload doesn't work on that setting? Can't reboot the servers right now, only have 1 proxy.

**Comment by lackoSK** [comment] 2020-02-11 17:21
It should work. Just do "bc reload" to bungee console.

**Comment by Sikatsu** [comment] 2020-02-13 15:43
For some reason setting it to [bungee] it doesn't show me any logs/debugging?

Doesn't the current information I gave show the issue i'm having btw?

**Comment by lackoSK** [comment] 2020-02-15 11:56
Just do "[*]"

**Comment by Sikatsu** [comment] 2020-02-15 12:42
That gives an error. https://pastebin.com/2ZgW2tKu

And [bungee] doesn't debug.

**Comment by lackoSK** [comment] 2020-02-16 14:19
Can you contact me over discord? lackoSK#0001 

I will close it here.

**Closed by lackoSK** 2020-02-16 14:19 UTC
Labels: Issue
