### ISSUE TITLE
Sound Notify Requires Chat Formatter/Channels

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl-Pro#572] opened 2018-01-15 22:42 UTC
I know it's provably an old version. That's why I'm asking. Is it worth updating for now? Since the @Mentioning system doesn't seem to be working on this version together with mc 1.12.2.

**Comment by kangarko** [comment] 2018-01-17 15:58
Please update. I just tested and it works just fine on the latest version.

**Comment by MithrandirCraft** [comment] 2018-02-02 18:31
Mmmm... it still doesn't work, and I updated.
It's not working on any of my servers.
This is my config: 

`Sound_Notify:
  Enabled: true
  Cooldown: 1 seconds
  Require_Afk: false
  Require_Prefix: '@'
  Sound: ENTITY_CHICKEN_EGG, 1F, 1.5F
  Color: '&a'
  Enabled_In_Commands:
  - /msg
  - /tell
  - /t
  - /w
  - /r`

**Comment by kangarko** [comment] 2018-02-04 20:17
I am sorry, I cannot reproduce the problem.

Are the users not receiving any sound AND their username not being colored?

Try setting the Require_Prefix to "".

Also, make sure they have the "chatcontrol.notify.whenmentioned" permission.

**Comment by MithrandirCraft** [comment] 2018-02-05 22:17
It fixed itself after enabling chat formatting. Is it even related?

**Comment by kangarko** [comment] 2018-02-09 10:32
It shouldn't be. I take this as a bug, sorry for that! I will come back to you as soon as possible, I am moving in real life, but should have time 15th or 19th February.

**Comment by MithrandirCraft** [comment] 2018-02-10 22:54
Hmh... if it happens again I'll tell you... kinda odd...

**Comment by kangarko** [comment] 2018-02-12 10:10
This will be resolved in the next version where sound notify will work regardless of formatting / chat options.

**Closed by kangarko** 2018-02-12 10:10 UTC
Labels: Issue: confirmed, Status: queued
