### ISSUE TITLE
/r shows up in red

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#1005] opened 2018-12-02 23:32 UTC
/r shows up in red like people don't have permission to use it, nor is it a command in tabcomplete. However, when u use the command it runs fine. /msg works fine and tabcomplete for it also works fine. People are complaining that it is annoying to see this when they try to reply:
https://gyazo.com/d5f200fb7239287e255df8013bb6849a

Minecraft 1.13.2 paper 470 chc 7.10.5

**Comment by kangarko** [comment] 2018-12-07 09:14
Cannot reproduce, sorry I think that is not a problem on ChatControl's side:

![a](https://i.imgur.com/g9KKZUN.png)

**Comment by LogGits** [comment] 2018-12-13 12:52
So I just tested this with 4 plugins and it still happens. `Vault, Luckperms-bukkit-4.3.2, protocollib, chatcontrol pro 7.10.8` and it still happens.

I am running build paper build 480 1.13.2. When using `/lp check <username> chatcontrol.commands.reply` it says its true for me.

**Comment by kangarko** [comment] 2018-12-23 23:09
Apology for the delay, we are on it however got delayed due to holidays, will return to you in few days.

**Comment by kangarko** [comment] 2018-12-31 09:56
Hey, sorry but even when I tested with 0 permissions and no operator status I was able to tab-complete (which I will patch):

![a](https://i.imgur.com/NJcgYeC.png)

I suggest you test with simply operator status or another permission plugin just for this round. I am confident in that this problem lies beyond ChatControl - are you experiencing tab-complete issues with other commands as well?

**Comment by LogGits** [comment] 2019-01-08 08:01
The only command we have issues with is /r. The users have permission to use the command but the tabcomplete shows up as red. They have the permission node as seen in that picture. Try with https://papermc.io/ci/job/Paper-1.13/486/artifact/paperclip-486.jar and luckperms

**Comment by LogGits** [comment] 2019-01-22 11:42
Any news on this?

**Comment by kangarko** [comment] 2019-01-23 10:12
I closed this because I was not able to reproduce under the same conditions (also with luckperms: https://i.imgur.com/DT4CHCF.png).

**Simply put, I strongly believe this is caused by another plugin.** As you config shows, some of the commands such as /tell work while others do not. That is an indicator that another plugin like Essentials may take them over. 

ChatControl tries to workaround this by unregistering the command first after the server has reloaded, but if you do have Towny installed, we cannot unregister it without breaking the /t command. The code excerpt below should clarity:

![a](https://i.imgur.com/UKkiT82.png)

**Comment by LogGits** [comment] 2019-01-23 13:44
I see what ur saying but i literally tested with 4 plugins (none of which could even cause this). I don't even use towny on my server. However, that works as expected as it registers it (msg/tell) correctly. Nothing else gets registered.

I have no equivalent commands to these:
```yaml
    - t
    - reply
    - r
    - togglepm
    - ignorepm
    - nopm
```
Doesn't that mean they should register as intended?

**Comment by kangarko** [comment] 2019-01-23 15:38
Try removing ChatControl. What happens if you run these commands without it?

![a](https://i.imgur.com/8x8TZ0O.png)

**Comment by LogGits** [comment] 2019-01-24 11:36
if i restart with ChatControl Pro `7.11.8` deleted from plugins folder. I get this: https://gyazo.com/788f882911ea894ccb3c836ede2dfd68

(including whisper)

**Comment by kangarko** [comment] 2019-01-25 10:00
That's very odd. I was able to reproduce that "Unknown command" when removing Essentials and ChatControl.

Are you able to setup a test local server with only ChatControl for a quick test?

Also please check your commands.yml for potential aliases. Same for plugins/ChatControl/rules/commands.txt file.

**Comment by kangarko** [comment] 2019-01-26 11:20
Just checking - if you used PlugMan what-so-ever during testing, it has been proven unstable numerous cases so please make sure to do a clean start without it

I will look deeper in to this issue and let you know

**Comment by LogGits** [comment] 2019-01-26 11:45
Yh i am aware of potential issues with plugman thats why i manually restart for chatcontrol and other plugins. I only use it to reload my plugin when testing stuff as my ide has issues with debug mode.

**Comment by kangarko** [comment] 2019-01-31 19:56
Just a follow up, I am still investigating but got occupied with real-life stuff.

**Comment by kangarko** [comment] 2019-01-31 20:14
Use the next version and set Debug to [pm, command] in settings.yml. You will get bunch of spam in the console at startup and when tab-completing /tell and all its aliases. Post me all the output. Test the tab for other tell aliases.

**Comment by LogGits** [comment] 2019-02-01 05:37
Ok here is the output. Interestingly enough, Reply and togglepm use the same commands? also "t" and "whisper" dont work either (just to clarify).
```
[ChatControl]: [command] Injecting /motd to command map
[ChatControl]: [command] Injecting /ignore to command map
[ChatControl]: [command] Injecting /me to command map
[ChatControl]: [command] Injecting /togglebroadcast to command map
[ChatControl]: [command] Injecting /tell to command map
[ChatControl debug]: Broadcast ignore commands injected. 
[ChatControl]: [pm] Register tell command: [tell, msg, t, whisper]
[ChatControl]: [command] Injecting /reply to command map
[ChatControl]: [pm] Register reply command: [tell, msg, t, whisper]
[ChatControl]: [command] Injecting /togglepm to command map
[ChatControl]: [pm] Register togglepm command: [tell, msg, t, whisper]
[ChatControl debug]: Private messaging commands injected.
```

**Comment by kangarko** [comment] 2019-02-10 12:16
Honestly it seems like an issue with your server, the plugin does register all variables correctly according to the message above. Are you able to put down a local test server running Spigot or Paper with only ChatControl present? That's what I am doing and not being able to reproduce the issue.

**Comment by LogGits** [comment] 2019-02-28 01:50
Ok sorry for the delay. I was able to test this on a seperate server running 1.13.2 paper build 480 with ChatControl Pro version 7.13.1.

This installation had only ChatControl in the plugins folder and a completely default config (with private messages enabled)

```
[11:46:29 INFO]: [command] Injecting /chatcontrol to command map
[11:46:29 INFO]: [command] Injecting /spy to command map
[11:46:29 INFO]: [command] Injecting /channel to command map
[11:46:29 INFO]: [command] Injecting /a to command map
[11:46:29 INFO]: *-----------------------------------------------*
[11:46:29 INFO]:  Cannot enable packet features!
[11:46:29 INFO]:  Required plugin missing: ProtocolLib
[11:46:29 INFO]: *-----------------------------------------------*
[11:46:29 INFO]: Fallback chat listener started at normal priority
[11:46:29 INFO]:  
[11:46:29 INFO]: Time to take action! (took 110 ms)
[11:46:29 INFO]: ______________________________________________________________
[11:46:29 INFO]:  
[11:46:29 INFO]: Done (5.517s)! For help, type "help"
[11:46:29 INFO]: Timings Reset
[11:46:29 INFO]: [ChatControl] [command] Injecting /me to command map
[11:46:29 INFO]: [ChatControl] [command] Injecting /ignore to command map
[11:46:29 INFO]: [ChatControl] [command] Injecting /tell to command map
[11:46:29 INFO]: [ChatControl] [pm] Register tell command: [tell, msg, t, whisper]
[11:46:29 INFO]: [ChatControl] [command] Injecting /reply to command map
[11:46:29 INFO]: [ChatControl] [pm] Register reply command: [tell, msg, t, whisper]
[11:46:29 INFO]: [ChatControl] [command] Injecting /togglepm to command map
[11:46:29 INFO]: [ChatControl] [pm] Register togglepm command: [tell, msg, t, whisper]
[11:46:29 INFO]: [ChatControl debug] Private messaging commands injected.
[11:46:29 INFO]: [ChatControl] A new version of ChatControl is available.
[11:46:29 INFO]: [ChatControl] Current version: 7.13.1; New version: 7.13.3
[11:46:29 INFO]: [ChatControl] URL: https://www.spigotmc.org/resources/10258/.
```
This doesn't make sense `[ChatControl] [pm] Register togglepm command: [tell, msg, t, whisper]` why would togglepm register `tell,msg,t,whisper`?

It produces the same output with everything red.

Why isnt this line:
```
[ChatControl] [pm] Register reply command: [tell, msg, t, whisper]
```
Like this?
```
[ChatControl] [pm] Register reply command: [r, reply]
```

**Comment by kangarko** [comment] 2019-03-23 18:06
Hey, sorry for the delay, seems like LuckPerms-related, unfortunately I am having a really hard time reproducing this but I am taking this seriously since 2 people reported this as per now.

Is it possible you test using PermissionsEx for one round? Just to be sure it is not caused by perms plugin. You can use your local PC server for that.

**Comment by kangarko** [comment] 2019-03-23 18:06
@LogGits

**Comment by LogGits** [comment] 2019-03-24 19:45
Just thought id mention again, I was able to reproduce this on a paper server with only chatcontrol installed. No perm plugin. Both regular and opped had a red /r.

**Comment by kangarko** [comment] 2019-03-27 08:25
I'm dealing with this issue over PM on Spigot, this should get fixed soon ;)

**Comment by kangarko** [comment] 2019-04-19 16:06
Happy Easter everyone, got it fixed!!

**Closed by kangarko** 2019-04-19 16:06 UTC
Labels: Issue: complaint, Status: in progress
