### ISSUE TITLE
Can't set chatcontrol.command.help to false

### ISSUE THREAD

**Issue by Equity7** [kangarko/ChatControl-Pro#1460] opened 2019-11-29 09:39 UTC
I am using Luckperms and I have chatcontrol.command.help set to false for the default group, yet they still have access to /chc ? and help. Then I tested setting other perms to false for default at a global level and none of them are negated.
I restarted several times and rechecked my spelling for the perms.
I am using bungee.

Please advise, thanks!

**Comment by lackoSK** [comment] 2019-11-29 15:23
Hello,

Thanks for reporting this issue. The issue is now fixed in the next version.

Regards, 
lackoSK

**Closed by lackoSK** 2019-11-29 15:23 UTC
