### ISSUE TITLE
1.16.1: NullPointerException - Unable to parse JSON message

### ISSUE THREAD

**Issue by Baterka** [kangarko/ChatControl-Pro#1750] opened 2020-07-02 10:38 UTC
### How to ask questions or report a problem here?
![image](https://user-images.githubusercontent.com/3463591/86348447-f8c81a80-bc5f-11ea-8e4c-0283bb001969.png)

I am getting those messages all day on different types of messages.

### 1 - Write your Minecraft version in the title:
1.16.1 PaperMC #39

### 2 - Be clear: What is your current situation, the desired situation, and your problem?
I am not sure if this error means that players not see messages, but it is happening very often.

### 3 - Upload your plugin's folder.
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4863624/ChatControl.zip)

Thank you.

**Comment by lackoSK** [comment] 2020-07-03 20:21
Hello,

I'm just reviewing this issue and I do not have enough information. Can you add a little more detail to this ticket? 

Sincerely,
Ladislav from MineAcademy.org

**Comment by Baterka** [comment] 2020-07-04 08:10
Hi. I really do not have more details.
But it seems that those errors are mostly with CMI messages.

**Comment by rybuilder23** [comment] 2020-07-04 09:00
i have the same usue.

https://pastebin.com/vBLU3fnU

**Comment by sandwally** [comment] 2020-07-04 10:19
Removed Cmi and it still happens when an advancement is completed
https://pastebin.com/iCsKFp51

Not getting the error from advancements when i'm in OP or having the permission "**chatcontrol.***"
Tried all other permissions from chatcontrol and wildcard after them _"broadcaster, bypass, chat, command, force, group, groups, joinmessage, message, notify, spy"_ but getting the error then so I guess some "hidden" chatcontrol permission is used/not used with **chatcontrol.***
On PaperMC,46 - Waterfall,360 - Chatcontrol,9.0.2BETA

**Comment by JavaFactoryDev** [comment] 2020-07-04 19:48
Got it, please just disable Check_Packets in the settings.yml for now.
Can you tell me on which version this is exactly occurring? 
We are trying to reproduce this but we can't find it at all.

**Comment by Baterka** [comment] 2020-07-04 22:21
> Can you tell me on which version this is exactly occurring?
ChatControl-9.0.2-BETA.jar
PaperMC #39
CMI 8.7.0.6

**Comment by JavaFactoryDev** [comment] 2020-07-05 10:49
I meant the minecraft version.
I will be more precise in the future.

**Comment by Baterka** [comment] 2020-07-05 11:04
PaperMC #39 = 1.16.1

**Comment by broken1arrow** [comment] 2020-07-05 14:36
Use PaperMC 68 and get this error. It interfere with jobs plugin. 

https://pastebin.com/574QHi43

CHC error log
https://pastebin.com/d3tbuwJB

**Comment by broken1arrow** [comment] 2020-07-05 14:37
Same version work in papermc 353

**Comment by JavaFactoryDev** [comment] 2020-07-05 17:02
Hey, 

Does it still happen in the latest version?

Regards,
Leonhard from MineAcademy

**Comment by sandwally** [comment] 2020-07-05 18:53
Check_Packets on, now it only shows this in the console with 9.0.3-BETA
"ChatControl 9.0.3-BETA encountered a NullPointerException! Please check your error.log and report this issue with the information in that file."

Made a hover text and getting this error for hoverEvent in error.log
https://pastebin.com/k1z1PYmu

And one with cmd on hover text and got hoverEvent and clickEvent in error.log
Everything else in the error is the same as above.
https://pastebin.com/J9UGB5rL

Advancements gives a bit different error but still 'the same'
https://pastebin.com/wzRS32vn

**Comment by broken1arrow** [comment] 2020-07-05 20:09
> 
> 
> Hey,
> 
> Does it still happen in the latest version?
> 
> Regards,
> Leonhard from MineAcademy

Yes
CHC error log
https://pastebin.com/gJ5JBgn3

**Comment by JavaFactoryDev** [comment] 2020-07-06 10:40
Hi, this seems to be caused by ProtocolLib, maybe you can contact their support?

**Comment by Aitnys** [comment] 2020-07-06 16:16
[error (3).log](https://github.com/kangarko/ChatControl-Pro/files/4880093/error.3.log)

the errors changed with the latest release but it still gives errors on death messages and achievements.

**Comment by JavaFactoryDev** [comment] 2020-07-06 18:26
Hi, I am still not able to reproduce this. I am already using your ChatControl folder.
Are you sure that this is not caused by any other plugin?

**Comment by broken1arrow** [comment] 2020-07-07 08:14
> 
> 
> Hi, I am still not able to reproduce this. I am already using your ChatControl folder.
> Are you sure that this is not caused by any other plugin?

Is combo of CHC and jobs reborn and try cmi same error (so guess all plugin some has hover in chat is infected). 

CMI error (and CMI is upgraded to work with 1.16.1).

**Comment by JavaFactoryDev** [comment] 2020-07-07 14:33
So which plugins are you exactly using?
We need an exact step by step way to reproduce this to fix it.

**Comment by broken1arrow** [comment] 2020-07-07 16:29
> 
> 
> So which plugins are you exactly using?
> We need an exact step by step way to reproduce this to fix it.

https://www.spigotmc.org/resources/jobs-reborn.4216/ and https://www.spigotmc.org/resources/cmi-270-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/ 

Use /jobs quest and cmi is it /cmi rankinfo (probably more commands do the same, has only confirm the problem not check all commands).

**Comment by sandwally** [comment] 2020-07-07 18:11
What I use to make it happen.

https://ci.dmulloy2.net/job/ProtocolLib/472/
https://papermc.io/ci/job/Paper-1.16/79/
And Chatcontrol Pro 9.0.3.BETA

Everything is default and newly generated from chatcontrol nothing touched, even Bukkit.yml Spigot.yml and paper.yml are newly generated

Then run this tellraw in console AND DON'T be in OP mode on your online character
/tellraw @a ["",{"text":"ChatcontrolChatText","hoverEvent":{"action":"show_text","contents":["",{"text":"ChatcontrolHoverText"}]}}]
Or complete any advancement.

**Comment by maaatthias** [comment] 2020-07-07 21:21
Hey, 
I can't reproduce the issue. I've tested the issue with advancements, deaths and other plugins like CMI or ProtocolLib. I don't think that the issue is connected to ChatControl.
If you have new information, please let me know.

We're using our latest Dev build: 9.0.4-SNAPSHOT.
Maybe the issue way already fixed by the latest advancements we made.

Regards,
- Matthias from MineAcademy

**Comment by sandwally** [comment] 2020-07-10 18:12
Events from advacements, tellraw and cmi is fully fixed for me in 9.0.4.
Me and my console thanks you a lot 👍

**Comment by JavaFactoryDev** [comment] 2020-07-10 18:25
No problem ;)

**Closed by JavaFactoryDev** 2020-07-10 18:25 UTC
Labels: Issue
