### ISSUE TITLE
[Suggestion] Similar message max live time

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#1079] opened 2019-02-02 19:37 UTC
Suppose you have a a quite player. Who only says rarely something. And suppose he repeats the same message from an hour ago.... I guess nobody really finds that annoying. So I wonder: how long is this similar message kept in the memory? Would it be logical to keep a max live time?

I would suggest this should last for more than a hour (or maybe 2 hours or so). Even though the message is the same, no player can remember what's been said a hour ago, even if it's the same.

**Comment by kangarko** [comment] 2019-02-09 10:59
Duplicate of https://github.com/kangarko/ChatControl-Pro/issues/1076#issuecomment-459989833, we are on it

**Closed by kangarko** 2019-02-09 10:59 UTC
