### ISSUE TITLE
Rules not working at all, everything was fine before

### ISSUE THREAD

**Issue by xnopasaranx** [kangarko/ChatControl-Pro#490] opened 2017-11-17 20:41 UTC
Hello there!
I recently updated my server from spigot 1.11.2 to 1.12.2 and while I was at it, I updated all my plugins as well. I am not exactly sure what version of ChatControl I was on before but I believe it was a 7.5.x build.

I mainly use the plugin for bungeecord network wide chat, name prefixes and filtering out annoying server messages from the chat (save-on, save-off is being run by a cronjob quite frequently), but this does not work anymore and I can't figure out what I am doing wrong.

My old settings.yml was causing problems with the new CC build, so I deleted the whole ChatControl folder to start with fresh configuration files. The plugin loads ok on server start, bungeecord options work fine and global chat is default, names are also formatted. But none of the rules work at all. My own packet filter wouldn't work and now the default rules in chat.txt, packet.txt, rules.txt don't seem to trigger either. 

Debug is turned to true in settings.yml but nothing regarding the rules appears in the console.

What could be the cause of this? Listener priorities? I do not know how to debug this, please help and advise me on what config files or logs I can provide (config is clean default with bungeecord settings activated in settings.yml plus debug turned on, nothing else has been touched) 

Plugins on the server: worldedit, worldguard, voxelsniper, protocollib, vault, multiverse-core,multiverse-netherportals, multiverse-signportals, dynmap, craftinomicon, permissionsex, essentials, essentials.spawn

**Comment by kangarko** [comment] 2017-11-23 17:28
Hello & sorry for the late reply!

If I am understanding you correctly, you have also tried with a completely new ChatControl/ folder. On my test machine, rules are being checked, so I assume something else may be in the way.

Do you have any other plugins formatting chat, like DeluxeChat, TownyChat or even chat in PlotSquared or similar?

Check if the "Chat & rules listening at" message appears at the plugin startup, and make sure no errors appear in the console.

I have added a debug option "rules" into the next version. To enable it, set your Debugger section as such and notice the console output when typing in the chat.:
![img](https://i.imgur.com/cr0ILW7.png) 

Finally, make sure you and your players do not posses bypass permissions.

**Comment by xnopasaranx** [comment] 2017-11-23 18:59
Hi kangarko, thanks for having a look!
I don't have any of those plugins running, I have listed everything that I have installed.

The message "Chat & rules listening at" appears and lists all rule files (chat, packet etc). There is no error message, the plugin seems to be working correctly. It is picking up on urls that are pasted in chat and displays the default ad warning.

Also the anti-spam is triggered when commands are entered repeatedly.

I will try the new debugging option and report back.

**Comment by kangarko** [comment] 2017-11-29 17:38
Hello @xnopasaranx ,

have you tested the debugging option? I have also thought of that it may be another chat-related plugin overriding the rules check. Do you have a plugin like DeluxeChat or similar?

**Comment by Fluxty** [comment] 2017-12-03 17:40
We are experiencing this issue as well today. After our daily server reboots every single server on our network across 5 machines is no longer listening to any of the Chat Control rules. I'm turning on the debugger for our next reboot but being this is on the weekend is very inconvenient D:

ChatControl was stable for weeks before these issues suddenly started to happen, no changes were made except to two of our SkyBlock server configurations. Version 7.6.6

**Comment by kangarko** [comment] 2017-12-04 06:50
Has the plugin booted up correctly Fluxty? Yes please, post me the debugger of '[rules]' section.

**Comment by xnopasaranx** [comment] 2017-12-05 10:21
Hi Kangarko, sorry but I have a huge workload right now and can't test the debugging feature. I hope that I will be able to test this week and will report then.

**Comment by kangarko** [comment] 2017-12-05 19:13
@xnopasaranx no problem, I am leaving this open.

The last version includes a fix for rare scenarious where the plugin would not start at all for some users, I believe if the rules suddenly stopped working, the fix should cover them as well.

**Comment by Mxra** [comment] 2017-12-08 23:14
I'm experiencing this as well, on the latest update it seems to be catching my rules in messages but not in the global chat... Very strange.

**Comment by kangarko** [comment] 2017-12-09 14:23
@Mxra have you changed Listener_Priorities? Do you use any other plugin to format the chat, like DeluxeChat or similar, or only ChatControl's formatting.yml or channels.yml?

**Comment by Mxra** [comment] 2017-12-09 15:11
@kangarko I'm using the latest development build of EssentialsXChat and all of my priorities are on NORMAL which I believe is default.

**Comment by kangarko** [comment] 2017-12-10 08:58
I see, yes, this is the default. To allow me to replicate under exactly the same conditions, please upload your entire ChatControl folder in a ZIP or RAR archive here (make sure to remove mysql information). Thank you.

**Comment by Mxra** [comment] 2017-12-10 16:25
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/1545796/ChatControl.zip)
There you go.

**Comment by Phoetrix** [comment] 2017-12-10 21:17
I have a similar problem. All rules in "packets.yml" work when I start the server but when I send a private message OR when I write a message in the chat then all rules in "packets.yml" doesn't work. :(

I think the bug is caused by functions in "formatting.yml". When I send a message on the chat, the packet rule is broken. So I disable chat formatting, I restart my server and now, when I send a message, the packet rule is not broken. Of course, it's the same problem for private message.

And the Debugger write nothing. :/

**Comment by kangarko** [comment] 2017-12-11 19:50
@xnopasaranx @Phoetrix and @Mxra,

I apology for the time it took to track down this issue. Turns out to be a very nasty one but I believe to have founded it. I have changed something in the code, it seemed to be fixed on my test server but please test out the next release and let me know if anything arises. 

Thank you for your patience.

**Closed by kangarko** 2017-12-11 19:50 UTC
Labels: Issue: complaint, Status: awaiting answer
