### ISSUE TITLE
Error on join/leave

### ISSUE THREAD

**Issue by Geekmakes** [kangarko/ChatControl-Pro#1561] opened 2020-02-12 01:03 UTC
Started getting this error on join/leave: https://pastebin.com/eE8ktux6 no join message is seen in chat but the leaving msg is. Idr what update it started doing this in but it was after there was a java placeholder issue (Running latest now). I've tried resetting my settings file and re-editing the settings but the error is still there and the join msg isn't working. I'm probably doing something wrong just no clue what. 🤷‍♂
 
Paper 1.15.2 v99
ChatControl-8.6.1.jar
here's my settings file: https://pastebin.com/MW1YdVwm
And messages:  https://pastebin.com/sc4Ux4vs
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4193139/ChatControl.zip)

**Comment by lackoSK** [comment] 2020-02-15 12:02
Hello,

This might be caused by JavaScript issue which we are resolving #1531 

Regards,
lackoSK

**Comment by lackoSK** [comment] 2020-02-18 18:24
Okay,

We've released version 8.6.3, which should fix this issue.

If the issue continues for you, feel free to message under it, and we will re-open it. 

PS: Thank you for reporting it ^^ 

Best,
lackoSK

**Closed by lackoSK** 2020-02-18 18:24 UTC
Labels: Issue
