### ISSUE TITLE
2 negations on chatcontrol.command still not working after update

### ISSUE THREAD

**Issue by Equity7** [kangarko/ChatControl-Pro#1468] opened 2019-12-04 20:43 UTC
I have a previously closed case, in which I am having trouble getting chatcontrol.command.help false to work. I am also trying to get chatcontrol.bypass.tabcomplete to work. I think I saw they would go in the next update but they still don't seem to work after 2 more updates.

I have a different help plugin so I want to put the relevant chc info in there.

Also, my aim is to get players to not use tab complete at all, maybe I am misunderstanding the commands to use.

**Comment by lackoSK** [comment] 2019-12-06 12:50
Hello,

What are you having issues with? What you want to do precisely.

The permission to bypass tabcomplete is

> Perm: chatcontrol.bypass.tabcomplete
Info: Allow player to tab complete.
Notice: If you are using Spigot it is highly recommended to disable this feature and use the inbuilt one in spigot.yml

Regards,
lackoSK

**Comment by Equity7** [comment] 2019-12-06 18:29
I had a prior ticket open because, though I have chatcontrol.command.help set to false for players, they could still access /cc help. The response to that ticket is that it would be fixed in the next update (though there is still the same issue). The ticket was closed.

I had a second ticket open because I couldn't turn tabcomplete off, though I had it disabled in the settings.yml and I have chatcontrol.bypass.tabcomplete set to false.  I accidentally closed that ticket and couldn't reopen it. I don't want to turn of tab complete in spigot.yml because it turns it off for me too.

I am running 1.14.4 Paper on a 3rd party server,

**Comment by lackoSK** [comment] 2019-12-10 19:14
I think this is a duplicate of your second 'same' issue https://github.com/kangarko/ChatControl-Pro/issues/1462

**Closed by lackoSK** 2019-12-10 19:14 UTC
Labels: Issue
