### ISSUE TITLE
Chat no longer being logged in console?

### ISSUE THREAD

**Issue by philip-ulrich** [kangarko/ChatControl-Pro#45] opened 2016-05-14 22:06 UTC
I'm not seeing chat from chatcontrol being logged to console anymore. 

Server version: CraftBukkit version git-Spigot-4af49dc-c5e9a16 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)

ChatControl Pro version: 6.9.1

Relevant plugins: DiscordMC, Dynmap

How to reproduce: 
1. Chat
2. ???
3. !profit

If you have an obvious issue with one or more of your configuration file/s include them as well:
I don't see one, but here ya go
http://d.l33t.tech/1lcpD/bUUSjBmA

**Comment by kangarko** [comment] 2016-05-15 11:26
Hello,

I am sorry but I was not able to reproduce it. Can you please post me also your chat.yml ?

**Comment by philip-ulrich** [comment] 2016-05-15 14:00
Sure thing, here you go:
http://d.l33t.tech/16nYc/4up2tbwt

**Comment by kangarko** [comment] 2016-05-22 08:17
I am sorry for the delay, I was still not able to reproduce it. Can you try removing DiscordMC, Dynmap, one by one, to see if it helps? If so, it will mean that it somehow interferes with CHC. In such case I can take a look at the respective plugin's settings, or, you can make contact with its developer.

**Comment by Sikatsu** [comment] 2016-05-23 19:46
ChatControl doesn't support that, it's normal that the chat messages won't be logged to the console. I made an issue earlier about this and Kangarko made sure to test some stuff but it didn't work.

**Comment by kangarko** [comment] 2016-05-24 16:40
Well the messages from chat formatter are indeed displayed in the console. But in some rare occasions, they might be hidden, most likely due to a third party plugin.

**Comment by kangarko** [comment] 2016-07-23 09:10
Closing. Please bug me if it still occurs.

**Closed by kangarko** 2016-07-23 09:10 UTC
Labels: cannot reproduce, issue
