### ISSUE TITLE
 Chat Control help

### ISSUE THREAD

**Issue by rosiejane** [kangarko/ChatControl-Pro#1581] opened 2020-03-01 15:52 UTC
Hiya Everyone

How can i stop this spam from happening?

[code]29.02 22:28:42 [Server] INFO [GriefPrevention] (Muted ILoveSprinkle): nigga
29.02 22:28:42 [Server] INFO [GriefPrevention] (Muted ILoveSprinkle): nigga
29.02 22:28:43 [Server] INFO [GriefPrevention] (Muted ILoveSprinkle): nigga
29.02 22:28:43 [Server] INFO [GriefPrevention] (Muted ILoveSprinkle): nigga
29.02 22:28:43 [Server] INFO [GriefPrevention] (Muted ILoveSprinkle): nigga
29.02 22:28:43 [Server] INFO [GriefPrevention] (Muted ILoveSprinkle): nigga
29.02 22:28:43 [Server] INFO [GriefPrevention] (Muted ILoveSprinkle): nigga
29.02 22:28:43 [Server] INFO [GriefPrevention] (Muted ILoveSprinkle): nigga
29.02 22:28:44 [Server] INFO [GriefPrevention] (Muted ILoveSprinkle): nigga
29.02 22:28:44 [Server] INFO [GriefPrevention] (Muted ILoveSprinkle): nigga
29.02 22:28:44 [Server] INFO [GriefPrevention] (Muted ILoveSprinkle): nigga
29.02 22:28:44 [Server] INFO [GriefPrevention] (Muted ILoveSprinkle): nigga
29.02 22:28:44 [Disconnect] User ILoveSprinkle has disconnected, reason: Kicked for spamming[/code]

What settings do i need to set, what would be ideal? ive tried but can't seem to get it working correctly. It either tends to block the same word more than once or allows the same word constantly.

If someone can post me or pm me their config so i can test it out that would help me so much.

Thank you

**Comment by lackoSK** [comment] 2020-03-02 10:12
Isnt this caused by [GriefPrevention] ? Test chc alone

**Comment by rosiejane** [comment] 2020-03-02 18:13
Nothing to do with GriefPrevention. Chat Control should be able to stop this spam from happening but i dont know whats settings to change to do this. Lot sof people must know. but they are not replying

**Comment by lackoSK** [comment] 2020-03-05 16:29
I think I've replied to you on spigot

Will close it here.

**Closed by lackoSK** 2020-03-05 16:29 UTC
Labels: Issue
