### ISSUE TITLE
Private messages are show to all players

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#92] opened 2016-08-16 09:48 UTC
Server version: 1.8.8
ChatControl Pro version: 7.0.8
Relevant plugins: none
How to reproduce:
I just upgraded from 6.9.6 to 7.0.8 in all my server and now all players are are able to see all sent/reply messages, bungee private messages are disabled and was working fine before the upgrade.
My config

> Private_Messages:
  Enabled: true
  Bungee: false
  Aliases:
    Tell:
    - msg
    - t
    - whisper
    - w
    Reply:
    - r
  Static_Format_Sender: '&8[&6you &8-> &6{player}&8] &7{message}'
  Static_Format_Receiver: '&8[&6{player} &8-> &6you&8] &7{message}'
  Format_Sender: Private_Message_Sender
  Format_Receiver: Private_Message_Receiver

**Comment by kangarko** [comment] 2016-08-17 11:28
I cannot reproduce. Ensure they do not have the chatcontrol.commands.spy permission, which is for the /spy command. Otherwise I cannot see a reason for that. Can you just for a test rename the entire ChatControl folder so it regenerates, just to see whether it happens on a clean installation?

**Comment by xion87** [comment] 2016-08-17 11:51
Basic user just have chatcontrol.commands.reply and chatcontrol.commands.tell
and was working fine in 6.x
I going to to try the new folder thing later

**Comment by xion87** [comment] 2016-08-17 12:49
I was able to reproduce by replying to myself, after that everyone will be able to read all private messages

**Comment by kangarko** [comment] 2016-08-19 15:11
I was able to replicate this bug. I am sorry for this and I will fix this asap.

**Comment by kangarko** [comment] 2016-08-20 11:28
I forgot to close this, it has been fixed in 7.0.10

**Closed by kangarko** 2016-08-20 11:28 UTC
Labels: bug
