### ISSUE TITLE
Multiple punishments

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#261] opened 2017-06-15 08:49 UTC
When multiple punishments are setup under a single point level. The executing is done randomly. THis must be sequentially in order to work.

Example settings:
16:
- "mute {player} 20m Swearing."
- "kick {player} Swearing."

When executed in random order, the player is kicked first. Muting is not an option anymore because the player is no longer online.

This is especially important if you want to do more actions in case of sever swears and higher points. Like: first warn the player, then change the output a the chat message, then mute, then kick.

This also should work with special actions in the rule files.

**Comment by kangarko** [comment] 2017-06-17 11:13
Hey,

I just answered you via PM. I cannot reproduce it, this is what I tested:

![img](https://i.imgur.com/3mFfnVQ.png)

Please choose where it's more comfortable for you to report issues and only stick to one channel.

**Comment by kangarko** [comment] 2017-07-01 18:14
Closing, please comment below if still experiencing issues.

**Closed by kangarko** 2017-07-01 18:14 UTC
Labels: Issue: cannot reproduce, Status: awaiting answer
