### ISSUE TITLE
Issue with chatcontrol.chat.format.color.*

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#362] opened 2017-09-16 12:43 UTC
"chatcontrol.chat.format.color.*" is allowing players to use &l &o &m &n and &k. They don't have the permission "chatcontrol.chat.format.*" but can still use the formats.

Also how do i make swears deny signs. The rules are in the rules.txt, here is an example of one:
```
#Blocks f**k
match \b(f+(\W|\d|_)*u+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*)\w*
then warn &cExcessive swearing is punishable.
handle as swear
```
They get handled by the swear handler but with signs it warns them and doesn't break the sign or censor the text on the sign.

**Comment by xion87** [comment] 2017-09-16 14:30
I confirm this, my user have chatcontrol.chat.format.color.* and they can use all formatting codes

**Comment by EvilOlaf** [comment] 2017-09-17 09:51
Tried the newest release?
https://github.com/kangarko/ChatControl-Pro/issues/353#issuecomment-329911341

**Comment by xion87** [comment] 2017-09-17 10:14
yeah was using 7.5.2

**Comment by kangarko** [comment] 2017-09-17 17:31
1) Color issue: Confirmed, will be fixed.

2) Cannot reproduce:
![img](https://i.imgur.com/jwzVHzc.png)

Please post me your settings.yml and handlers.yml

**Comment by LogGits** [comment] 2017-09-18 02:06
Chat fixed however when users with permission "chatcontrol.chat.format.*" use /msg or /tell user &c&lTest it says &ltest in red (should be bold).

**Comment by LogGits** [comment] 2017-09-18 02:20
Settings.yml is this:
```
Anti_Bot:
  
  Cooldown: 
  
    # How many seconds the player needs to wait before logging in again?
    Rejoin: 3
    
    # How many seconds must the player wait after login to chat?
    Chat_After_Login: 1
    
    # How many seconds must the player wait after login to run commands?
    Command_After_Login: 1
  
  # Block chat until the player has moved? They can still execute commands.
  Block_Chat_Until_Moved: true
  
  # A list of commands to block until the player has moved.
  # To disable, set to: Block_Commands_Until_Moved: '[]'
  Block_Commands_Until_Moved:
    - /afk
    - /me
  
  # If you have AuthMe, only display the quit message if the player was logged in?
  # [TIP] To disable join message, enable 'delayJoinMessage' in AuthMe's configuration.
  Show_Quit_Message_Only_If_Logged: true
  
  # Player will be unable to place two signs with the same text.
  Block_Signs_With_Same_Text: false
  
  # Prevent inappropriate player names from entering the server. Supports regular expressions.
  Disallowed_Nicknames:
    - '(f+(\W|\d|_)*u+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*)'
    - bitch
    - asshole

# -------------------------------------------------------------------------------------------------
# Prevent messages written in BIG LETTERS
# -------------------------------------------------------------------------------------------------
Anti_Caps:
  Enabled: false
  Enabled_In_Commands: false
  
  # List of commands checked for capitalization. Requires 'Enabled_In_Commands' enabled.
  # [TIP] To enable anti-caps everywhere, set the list to - '/'
  Commands_To_Apply:
    - /msg
    - /tell
  
  # How many warning points to give when the player triggers the filter?
  # [NOTICE] Only works if Points are enabled. To disable, set: 'Amount: 0'
  Points: 
    Warn_Set: spam
    
    # You can write a valid mathematical expression here. The result will be rounded to a whole number (without decimals).
    Amount: 4 * ({capsPercentage} / 2)
  
  # Allow player names to be spelled in caps? Disable if having performance issues (especially on large servers).
  Ignore_Usernames: false
  
  Min_Message_Length: 5
  Min_Caps_Percentage: 50
  Min_Caps_In_A_Row: 5
  Whitelist:
  - OMG
  - LOL
  - WTF
  - WOW
  - ROFL

# -------------------------------------------------------------------------------------------------
# Prevent flooding the chat with junk / repetitive messages
# -------------------------------------------------------------------------------------------------
Anti_Spam:

  # This section applies for both commands and messages.
  #
  # Similarity check compares player's message to their last one(s),
  # and prevents sending the same or similar message(s) multiple times.
  Similarity_Check:
  
    # If running a non-english server, disable to improve the check.
    Ignore_Special_Characters: true
    
    Ignore_Duplicate_Characters: false

  # Anti-spam section for commands.
  Commands:
  
    # How many seconds the player must wait till their next command? Set to 0 to disable.
    Command_Delay: 0
    
    # Warning points.
    # [NOTICE] Only works if Points are enabled. To disable, set: 'Amount: 0'
    Delay_Points:
      Warn_Set: fastmessages
      
      # The {delay} is the delay between the current and last command in seconds.
      Amount: 3 - {delay}
    
    # Block the command if it's similar to the previous one, in percent.
    # Set to 0 or 100 to disable.
    Similar_Percentage_Block: 0
    
    # Warning points.
    # [NOTICE] Only works if Points are enabled. To disable, set "Amount" to 0.
    Similarity_Points:
      Warn_Set: spam
      Amount: 0
 
    # If enabled, *ONLY* the commands listed in the whitelist will be checked.
    Whitelist_Works_Like_Blacklist: false
 
    # Commands that the player can run them multiple times after each other.
    Whitelist_Similarity:
    - tell
    - pm
    - t
    - w
    - r
 
    # Commands that the player is not forced to wait before executing them next time.
    Whitelist_Delay:
    - spawn
    - hello
    
    # Commands to handle as chat. 
    # Includes anti-spam, rules, writer, points, anti-caps, capitalizing and punctuation.
    Handle_As_Chat:
    - me

  # Anti-spam section for messages.
  Chat:
    
    # How many seconds must the player wait between their next message? Set to 0 to disable.
    Message_Delay: 0

    # Warning points.
    # [NOTICE] Only works if Points are enabled. To disable, set: 'Amount: 0'
    Delay_Points:
      Warn_Set: fastmessages
      
      # The {delay} is the delay between the current and last message (in seconds)
      Amount: 3 - {delay}

    # Block repetitive messages if they are similar to the previous one, in percent.
    # Set to 0 or 100 to disable.
    Similar_Percentage_Block: 0
    
    # Amount of previous messages to check. Increases effectiveness and preventing spam like so:
    # <player> t
    # <player> lol
    # <player> t
    # <player> lol
    Similarity_Message_Check_Count: 0
    
    # Warning points.
    # [NOTICE] Only works if Points are enabled. To disable, set "Amount" to 0.
    Similarity_Points:
      Warn_Set: spam
      Amount: 0
    
    # A message that starts with the following will be ignored from the similarity check.
    Whitelist_Similarity:
    - hello
    - hey
    
    # A message that starts with the following will be ignored from the delay check.
    Whitelist_Delay:
    - test
    
# -------------------------------------------------------------------------------------------------
# Correct player's grammar.
# -------------------------------------------------------------------------------------------------
Grammar: 
  
  # Punctualize every sentence (insert a dot at the end).
  Insert_Dot:
    Enabled: false
    Min_Message_Length: 5

  # Capitalize sentences (make the first letter uppercased).
  Capitalize:
    Enabled: false
    Min_Message_Length: 5

# -------------------------------------------------------------------------------------------------
# Remove all messages from the chat with the "/chc clear" command.
# -------------------------------------------------------------------------------------------------
Clear:
  Broadcast: true
  Do_Not_Clear_For_Staff: true

  # Amount of blank lines to be printed to the console.
  Console_Lines: 5

# -------------------------------------------------------------------------------------------------
# Stop people from writing to the chat with the "/chc mute" command.
# -------------------------------------------------------------------------------------------------
Mute:
  Broadcast: true
  
  # Deny following actions while the chat is muted.
  Prevent:
    Writing_Books: false
    Placing_Signs: false

  # Hide the following messages while the chat is muted.
  Silence:
    Join_Messages: true
    Quit_Messages: true
    Death_Messages: true

  Disabled_Commands: 
  - me
  - tell
  - msg
  - r
  - w

# -------------------------------------------------------------------------------------------------
# Announce important messages with the "/chc announce" command.
# You can customize the format in localization.
# -------------------------------------------------------------------------------------------------
Announcer:
  Bungee: false
  Ignore_Self: false
  Log_To_Console: true
 
  # Usage: <bukkitSoundName>, <volume>, <pitch> 
  # For Minecraft 1.8.8 and older, it is recommended to use 'SUCCESSFUL_HIT'
  Sound: ENTITY_ARROW_HIT_PLAYER, 1.0, 0.1

# -------------------------------------------------------------------------------------------------
# Let staff communicate together with the "/chc ach" command.
# -------------------------------------------------------------------------------------------------
Admin_Chat: 
  Bungee: false
  Log_To_Console: true
  
  # Write to logs/admin-chat.txt ?
  Write_To_File: false
  
# -------------------------------------------------------------------------------------------------
# Send messages over Bungee with the "/chc global" command.
# -------------------------------------------------------------------------------------------------
Bungee_Chat:

  # Enable bungee chat for players after login automatically. They can turn it off with '/chc g switch'
  Enabled_By_Default: false

  Log_To_Console: false
  
  # Write to logs/bungee-chat.txt ?
  Write_To_File: false

# -------------------------------------------------------------------------------------------------
# Private messages allow you to secretly message another player without everyone else seeing.
# There are currently following commands: /tell and /reply
# [NOTICE] If disabled, you can still use commands with the same label from other plugins/server.
# -------------------------------------------------------------------------------------------------
Private_Messages:
  Enabled: true
  Bungee: false
  # The first alias is the main label, that must be set!
  Aliases: 
    Tell: [tell, msg, t, whisper]
    Reply: [reply, r]
    TogglePM: [togglepm, ignorepm, nopm]
  
  # You can configure the formats in formatting.yml file.
  Format_Sender: Private_Message_Sender
  Format_Receiver: Private_Message_Receiver

# ------------------------------------------------------------------------------------------------- 
# Ability to ignore chat and private messages from certain players.
# -------------------------------------------------------------------------------------------------
Ignore: 
  Enabled: true
  
  # Please do not remove the first alias, as this is the main command label.
  Aliases: [ignore, ign]
  
  # Hide chat messages from ignored players?
  Chat: true
  
  # Do not receive private messages from ignored people?
  Private_Messages: true

# -------------------------------------------------------------------------------------------------
# Features involving packets that require ProtocolLib.
# -------------------------------------------------------------------------------------------------
Packets:

  # Enable all features that require ProtocolLib
  # e.g. packet rules, tab complete
  Enabled: true

  # Prevent using TAB to complete a message. Tab completing may reveal server information.
  Tab_Complete:  
    Disable: false
    
    # Allow completion in messages?
    Disable_Only_In_Commands: false
    
    # Allow if the message/command contains space (' ') ?
    Allow_When_Message_Has_Space: true
    
    # Allow when the message length is above a certain limit. 
    # Not recommended as it might still reveal your server setup.
    Allow_When_Length_Above: 0

# -------------------------------------------------------------------------------------------------
# Most popular feature of ChatControl: Rules are user-defined filters that catch messages
# based on regular expressions. See "rules/" folder for configuration and examples.
# -------------------------------------------------------------------------------------------------
Rules:
  # Print the 'Rule match [...]' and messages about warning points into the console?
  # You can hide rules from appearing individually with "dont verbose" operator.
  Verbose: false

  # Broadcast warning messages from rules and handlers to Bungeecords?
  Bungee: false

  # Check chat with rules/rules.txt file and rules/chat.txt file?
  Chat: true
  
  # Check commands with rules/rules.txt file and rules/commands.txt file?
  Commands: true
  
  # Check messages against rules/packets.txt? Can catch messages from server itself, or even other plugins.
  # Requires ProtocolLib.
  Packets: true
  
  # Check signs with rules/rules.txt file and rules/signs.txt file?
  Signs:
    Check: true

    # Prevent the sign creation?
    Block: false
    
    # Drop as an item?
    Drop: true
  
  # Check books when signed, with rules/rules.txt file and rules/books.txt file?
  Books:
    Check: true
    
    # Replace the title an pages if a rule changes it? If false, denies creation.
    Replace: true
  
  # Check the name of items renamed by anvil with rules/rules.txt file and rules/items.txt file?
  Anvil: 
    Check: true
    
    # Replace item name if a rule changes it? If false, denies creation.
    Replace: true
  
  # Let players choose which messages (caught be a rule) they want to see.
  # Read more at https://github.com/kangarko/ChatControl/wiki
  Chat_Ignorer:
    Enabled: false
    
    # You have to create a set here (just a section) to be able to ignore it. Create as many as you want. 
    # You can limit sets that can be toggled by giving 'chatcontrol.ignoreset.<setName>' permission.
    Sets:
      
      # This is an example set where all possible settings are used (currently just one).
      # Players with 'chatcontrol.ignoreset.swearings' permission can toggle this set for themselves.
      # You do not need to specify any parameters, at all.
      swear:
        # Do not ignore by default. Player has to use "/chc ignore swearings" to make it effective for them.
        # Default value: false
        Ignored_By_Default: true
        
# -------------------------------------------------------------------------------------------------
# Remove unwanted messages from the console.
# -------------------------------------------------------------------------------------------------
Console_Filter:
  Enabled: false
    
  # Save messages that were caught and hidden to logs/console.txt?
  Log: false
    
  # Remove certain messages from console.
  # Does not need to be whole message, just a part of the message you want to block.
  Filter_Console_Messages:
  - Reached end of stream for
  - Connection reset
  # The following is commented out as it causes issues with Multicraft.
  # If you don't use Multicraft you can comment them out to lower console spam.
  #- UUID of player
  #- lost connection

# -------------------------------------------------------------------------------------------------
# Play a sound to a player that has been mentioned.
# -------------------------------------------------------------------------------------------------
Sound_Notify:
  Enabled: true

  # The time before they player will receive sound notify again.
  Cooldown: 2 seconds
  
  # Only notify if the player is afk? Requires Essentials.
  Require_Afk: false

  # Only notify when  player's name in the chat starts with the specific character.
  # Example: 'Hello @kangarko, are you there?'
  # Set to 'none' to always allow.
  Require_Prefix: 'none'
  
  # Format: bukkit_sound_name, volume (float), pitch (float)
  # If you are on MC 1.8.x or older, the default sound name was 'CHICKEN_EGG_POP'
  Sound: ENTITY_EXPERIENCE_ORB_PICKUP, 100F, 0.1F
  
  # Highlight the name of the notified player. Set to none to disable.
  Color: '&b'
  
  Enabled_In_Commands:
  - msg
  - tell
  - t
  - w
  - r

# -------------------------------------------------------------------------------------------------
# Set different settings from this file for people with certain permissions.
# -------------------------------------------------------------------------------------------------
Groups:
  Enabled: true

  # The group list. You can add, edit or remove existing groups here.
  # For tutorial, read https://github.com/kangarko/ChatControl-Pro/wiki/Groups
  List: 
    vip: 
      Message_Delay: 0
      Command_Delay: 0
      
# -------------------------------------------------------------------------------------------------
# Give player warning points for violating rules/actions.
# -------------------------------------------------------------------------------------------------
Points:
  Enabled: false
  
  # Shall the last action be repeated until the reset task gets scheduled?
  Repeat_Last_Action: true
  
  # Should player only get ONE warning (the one from warning set) and not both from rules and warning sets.
  Smart_Warnings: true
  
  # Players will loose their warning points when you reload or shut down the server (unless you use
  # MySQL, and, once upon a time, in the reset task:
  Reset_Task:
    
    # The delay between taking points (in seconds). Set 0 to only reset points on plugin or server reload.
    # [TIP] If this is disabled, enable Repeat_Last_Action
    Repeat_Every_Seconds: 20
    
    # How much points to take from different sets. If you do not specify a set, no points will be taken from it.
    Remove: 
      global: 5
      spam: 1
  
  # To punish the player in different ways for doing a specific thing, you can create multiple warning sets.
  Warn_Sets:
    
    # [NOTICE] This is a special set. Unless removed, all points will go there if you do not specify the set name.
    # example: you don't need to write "then points global 5", but just "then points 5" (in rules)
    global:

      # Specify the commands to execute if the player reaches a specific points threshold.
      # Use operator "warn" to send the message directly to the player, otherwise, run commands as the console.
      # Use operator "bungeeconsole" to send commands to Bungeecords directly.
      5:
        - "warn &7Please obey the &2rules &7otherwise you will be &4punished&7."        
        #- "bungeeconsole tell {player} &cYou have been warned for not respecting the server rules."
      15:
        - "warn &c**** &lHey &c{player} ****\n &7-> &cThis is your &6final &cwarning!"
        #- "mute {player} 5m Do not observing warnings" # Only works if you have a mute plugin        
      30:
        - "kick {player} &cKicked for breaking the rules"

    swear:
      4:
        - "warn &cYou have received first warning for swearing."
      6:
        - "warn &cPlease do not swear, otherwise an action will be taken!"
      8:
        - "kick {player} &cInappropriate language (last warning)"
      20:
        - "tempban {player} 30m autoban for swearing" # This requires compatible third party plugin installed

    spam:
      6:
        - "warn &cPlease do not act like spammer."
      10:
        - "warn &cPlease do not spam, otherwise you will be banned."
      12:
        - "kick {player} &cSpamming the chat (last warning)"
      26:
        - "tempban {player} 10m autoban for chat spam" # This requires compatible third party plugin installed

    fastmessages:
      6:
        - "warn &cPlease slow down chat messages."
      10:
        - "warn &cSlow down chat, otherwise you will be banned."
      14:
        - "kick {player} &cSlow down chat (last warning)"
      30:
        - "tempban {player} 10m autoban for chat spam" # This requires compatible third party plugin installed

# -------------------------------------------------------------------------------------------------
# A variable (placeholder) is a string in brackets {}, which is replaced by
# the actual data. Example: {player} is replaced with the player name.
# -------------------------------------------------------------------------------------------------
Variables:

  # Create own placeholders using JavaScript to get properties from any other plugin or even server itself.
  # See variables/javascript.txt file for their management and creation.
  Custom_Enabled: false
  
  # If Vault is installed, display players' prefix/suffix from each of their group together.
  # Limitation: Only displayed if the player has multiple groups, NO when a group inheritances multiple prefixes from other.
  Vault:  
    Multi_Prefix: false
    Multi_Suffix: false

# ---------------------------------------------------------------------------------------------------
# Save chat communication to see what happened in chat while you were offline.
# ---------------------------------------------------------------------------------------------------
Writer:

  # Write chat messages to logs/chat.txt?
  Enabled: false

  Ignore_Players:
  - ignoredAdmin

  # Commands that will be saved along with the chat messages. To log all, set Write_Commands: ['']
  Commands: 
  - me
  - msg
  - m
  - tell
  - t
  - reply
  - r
  - mail

# ---------------------------------------------------------------------------------------------------
# Welcome players to the server with a Message of The Day
# ---------------------------------------------------------------------------------------------------
Motd: 
  Enabled: false
  
  # How long to wait before displaying after login? Used to avoid covering by other messages.
  Delay_Ticks: 2
  
  # Sound to play. Format: <bukkitSoundName>, <volume>, <pitch> 
  Sound: ENTITY_FIREWORK_LAUNCH, 1F, 1F
  
  # Below it's just an example of the message you can send to players when they log in.
  Message:
  - 'Test'


# ---------------------------------------------------------------------------------------------------
# Spying allows to see others' commands, including content of private messages.
#
# [TIP] Give staff chatcontrol.spy.autoenable permission to auto enable spy on join.
# ---------------------------------------------------------------------------------------------------
Spy:   
  Enabled: true
  
  # Command aliases. The first one is the main label, please do not remove it!
  Command_Aliases: [spy, socialspy]
  
  Format: "&8[spy] {player}: &7{message}"

  # What prefix should we display when you receive a channel message from a channel you're spying?
  # Requires channels enabled in channels.yml
  Channel_Prefix: "&8[spy] "
  
  # Send to staff on other servers as well?
  Bungee: false
  
  # If true, ALL commands except for those listed below shall be monitored. NOT recommended.
  # If false, ONLY commands below are to be monitored. 
  Command_List_Works_Like_Blacklist: false
  
  Command_List: 
    - /tell
    - /msg
    - /t
    - /whisper
    - /r
    - /reply
    - p

# -----------------------------------------------------------------------------------------------------
# Integration with BungeeCords
# You need BungeeControlBridge on your bungee network. (https://spigotmc.org/resources/13079)
# -----------------------------------------------------------------------------------------------------
BungeeCords:

  # Enable the global bungee integration? To enable bungee in various settings, search for "Bungee"
  # key in that configuration setion.
  Enabled: false
  
  # The prefix used in front of all messages coming from other servers.
  Prefix: "&5[Bungee/{server_name}] &7"
  
# -----------------------------------------------------------------------------------------------------
# MySQL connection allows to store same information over multiple servers.
# -----------------------------------------------------------------------------------------------------
MySQL:
  
  # Save players' data to the database when they exit the server and load them on join?
  Enabled: false
  
  # Warning: Never change those on a live server. Do not reload, always restart.
  Connection:
    Host: 'localhost'
    Database: 'minecraft'
    Port: '3306'
    User: ''
    Password: ''
    # Note: There is no automatic update, when changed.
    Table_Prefix: 'ChatControl_'
    # For very advanced users, you may customize the connector syntax to MySQL here.
    Connector_Advanced: "jdbc:mysql://{host}:{port}/{database}?autoReconnect=true"

# -----------------------------------------------------------------------------------------------------
# Allows you to print specific debug messages only about certain parts of this plugin.
# You normally don't need to edit this unless you have problems or been navigated by the dev.
# -----------------------------------------------------------------------------------------------------
Debugger:
  # Which sections to debug? Current possible: pm (private messages)
  Sections: []
  
  # W.I.P
  Keys: ""
  
  # Save to logs/debug.txt ?
  Save: true
  
  # Log to console ?
  Log: false

# --------------------------------------------------------------------------------------------------
# Advanced: Affects the order in which we format and check the chat. No need to touch.
# Read https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities for more information.
# 
# Plugins which may require changing priority of Formatter: FactionsChat, BanManager and WorldGuard.
# You need to find the correct combination for your server yourself. Restart after each change.
# --------------------------------------------------------------------------------------------------
Listener_Priority:

  # Used for formatting or channels. Should have the last say, meaning highest priority.
  Formatter: HIGHEST
  
  # Used for checking a message against duplication, time or rules.
  Checker: NORMAL

# What commands should trigger the chatcontrol menu (separated by a comma ,)? 
# * THE FIRST ALIAS IS THE MAIN LABEL, PLEASE DO NOT REMOVE IT. *
Command_Aliases: [chatcontrol, chc]

# Handle characters with accents internally as without the accents (e.g. á goes to a)? 
# Makes rules and anti-spam more effective on non-english servers.
Translate_Diacritical_Marks: true

# Currently available: en (english), de (german), sk (slovak), cz (czech), es (spanish), pt (portugese), it (italian) 
#                      hu (hungarian), fr (french), nl (dutch), cn (chinese), dk (danish), pl (polish) and ru (russian)
# Read https://github.com/kangarko/ChatControl-Pro/wiki/Localization for tutorial on custom localization.
Locale: en

# Prevent regular expressions freezing the server if they take more time than specified (in milliseconds).
Regex_Timeout_Milis: 100

# Time of some plugin's operations is measured. Print a message to the console if they take 
# over the specified amount of time in milliseconds. Set 0 to disable.
Log_Lag_Over_Milis: 100

# Make the startup messages less intrusive. Disable if having issues.
Silent_Startup: false

# Remove colors from checked messages to prevent bypasses of rules.
# Disable if you wish to retain colors in the message after it's replaced by a rule.
Regex_Strip_Colors: true

# Plugin saves player data, such as their last message or command for anti-spam to use.
# Should the data be reset on player quit? Recommended in lobbies (on bungee), but not elsewhere.
Reset_Cache_On_Quit: false

# Set to true if the \n operator does not work for you.
# Before that, please ensure you've saved the file in an encoding that supports new line operator (usually UTF-8).
Enforce_New_Line: false

# The server name used in {server_name} variable. By default, the 'server-name' property from server.properties is used.
# It is mainly used for BungeeCords integration. Colors are supported.
Server_Name: server

# Notifies about new versions.
Check_Updates: true

# Prints info to the console about various events/configurations.
# [TIP] Don't be afraid to enable it - it helps you understand how plugin sees what
# you have configured, thus enabling you to solve issues by yourself with a glance.
Debug: false

# Do not change this value, otherwise it will corrupt your plugin installation!
Version: 18
```
Handlers.yml swear section is this:
```
advertisement:
  #
  # Ignore players with a proper permission.
  #
  Bypass_With_Permission: "chatcontrol.bypass.ad"
  #
  # Do not filter ads in the following commands:
  #
  Ignore_Commands: 
    - // # WorldEdit
    - /brush
    - /auction
    - /auc
    - /register
    - /reg
    - /login
    - /l
  #
  # Warn the player.
  #
  Player_Warn_Message: "&7Please do not advertise other websites or IP adresses."
  #
  # Notice online staff members.
  #
  Staff_Alert: "chatcontrol.notify.ad &8[&7Ad/ID {ruleID}&8] &7{player}: &f{message}"
  #
  # Deny the message entirely.
  #
  Block_Message: true
  #
  # Log the violation so you can check it if you are offline.
  #
  Write_To_File: none

# -----------------------------------------------------------------------------------------
# The default swear-words handler.
# ----------------------------------------------------------------------------------------- 
swear:
  #
  # Ignore players with permission.
  #
  Bypass_With_Permission: "chatcontrol.bypass.swear"
  #
  # Do not filter commands below:
  #
  Ignore_Commands: 
    - // # WorldEdit
    - /brush
    - /auction
    - /auc
    - /register
    - /reg
    - /login
    - /l
  #
  # Warn the player.
  #
  Player_Warn_Message: "&cSwearing is prohibited on this server."
  #
  # Notice online staff.
  #
  Staff_Alert: "chatcontrol.notify.swear &8[&7Swear/ID {ruleID}&8] &7{player}: &f{message}"
  #
  # Replace the swear word with a censor.
  # If you only specify one letter, it will be automatically stretched to match word's length.
  #
  Replace_Word: "@prolong*"
  #
  # Log the violation so you can check it if you are offline.
  #
  Write_To_File: none
```

**Comment by kangarko** [comment] 2017-09-18 20:14
Regarding the colors issues, I cannot reproduce it on future 7.5.4, please wait a bit and test it tonight :)

![img](https://i.imgur.com/X4G1Mfm.png)

Regarding the signs issue, in the next version try to set Listener_Priority.Signs to LOWEST, HIGH, HIGHEST  or maybe even MONITOR.

**Comment by LogGits** [comment] 2017-09-19 13:50
I have permissions chatcontrol.chat.format.* and chatcontrol.chat.format.color.* and it does this. When i /msg myself it does what yours looks like. When i send to other users "&c&ltest" shows up as &ltest in red.

**Comment by kangarko** [comment] 2017-09-19 18:20
I just tested, it works just fine with me. Are you sure you're on 7.5.4?

Btw, you only need the `chatcontrol.chat.format.*` permission, the color part is inherited by the * character.

![img](https://i.imgur.com/bkYqSPC.png)

**Comment by LogGits** [comment] 2017-09-20 01:17
The account that does the /msg &c&ltest has chatcontrol.chat.format.* the other account is in another group and has chatcontrol.chat.format.color.* 

This is how it looks:
Group2 which inherits from Group1 (sender): chatcontrol.chat.format.*
Group1 (reciever): chatcontrol.chat.format.color.*

**Comment by malonnnn** [comment] 2017-10-12 18:25
@LogGits 

If I understand you correctly, your perms are structured like so, is that correct?

`  group1:
    permissions:
    - chatcontrol.chat.format.color.*
    - essentials.msg
  group2:
    inheritance:
    - test1
    permissions:
    - chatcontrol.chat.format.*`

I think you may be having another plugin interfere with chat control. Can you please list your plugins? Also which tell are you using? essentials.msg or chatcontrol.commands.tell ? or both?

**Comment by LogGits** [comment] 2017-10-13 00:39
Remove essentials.msg from group1. No one has access to that perm on our server.

**Comment by kangarko** [comment] 2017-10-19 20:12
@LogGits I am sorry but still cannot reproduce. Could you send me 

* a) zipped ChatControl/ folder (make sure you remove mysql data info)
* b) permissions.yml file (if you want you can only send the relevant parts)

to make the testing more efficient. Thank you.

**Comment by LogGits** [comment] 2017-10-20 00:44
Sure thing. I'll send you the files when I get back to computer.

**Comment by LogGits** [comment] 2017-10-22 23:59
I am also going to retest this on the latest built to see if it still does it. I haven't tested since 7.5.5.

**Comment by kangarko** [comment] 2017-10-25 18:20
I am on unplanned travel from tomorrow till 30.10. Will get back to you around 31.10 :)

**Comment by LogGits** [comment] 2017-10-31 10:08
Ok so if i send a user without the permission a msg with colours it is testing agains the targets permissions.

I have all permissions given, I typed /msg user &c&lhi the result was &lhi in red. The target only has permission for chatcolors and not formatting. What I am assuming is happening is that the plugin is checking the targets permissions instead of the senders permissions when looking to apply colour and formatting.

Also is there a way to disable coloured chat from appearing in the spy?

**Comment by ipr0james** [comment] 2017-11-27 14:24
@LogGits 

Hey LogGits, apologies for it taking so long for anyone to get back to you.
Has this issue since been resolved or are you still having issues?

if it still continues it might be easier if I could come on and see the issue first hand rather than trying to replicate it.
Do you use discord? If so add ipr0james#1814 and I can try help get this resolved.

Thanks.

**Comment by ipr0james** [comment] 2017-11-29 13:19
Issue fully identified. Awaiting fix.

**Comment by kangarko** [comment] 2017-12-04 08:21
@LogGits I have fixed this issue. I apology for such a delay.

**Closed by kangarko** 2017-12-04 08:21 UTC
Labels: Issue: confirmed, Status: in progress
