### ISSUE TITLE
Color codes / Formatting codes in bungee chat

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1390] opened 2019-09-07 10:06 UTC
When I deny the use of color codes / formatting codes within the (default) bungee chat, it shows a blank space in front of the word: http://prntscr.com/p3006k

Also sometimes color codes still process through: http://prntscr.com/p300h2

This is what my permissions look like: http://prntscr.com/p303ml

**Comment by Sikatsu** [comment] 2019-09-07 10:41
They can also use it within the private chat: http://prntscr.com/p30a6t

**Comment by kangarko** [comment] 2019-09-07 16:40
We remove the color so a space can occur naturally if "&c test" is used for example. I look into what I can do with it.

Where did colors process in your image? The "Hey"? What was the message in the console?

I cannot reproduce the problem in private msgs, ensure you have the latest version. Notice the toast still sends the message with colors though:

![a](https://i.imgur.com/Ak4Zvwz.png)

**Comment by Sikatsu** [comment] 2019-09-07 17:03
Yes I am running the latest version, I just updated this morning. 

The ''hey'' for some reason still showed a color and it looked exactly the same in the console (with a color). While other times it shows a blank space instead.

I'm not sure why this occurs for me if you are not able to reproduce it? :/

I also noticed the behavior between /r and /w is different. With /w it shows &cHi while with /r it doesn't show the color code.

/w : http://prntscr.com/p33vd5
/r : http://prntscr.com/p33vg9

**Comment by Sikatsu** [comment] 2019-09-07 17:08
Found it. Using a capital it still processes. ''&B Hello'' for example.

**Comment by kangarko** [comment] 2019-09-09 16:25
Thank you the capital problem will be fixed!

Yes when the message is sent through our chat component API, we remove the colors because they are applied automatically when we replace variables for that component.

The other parts of the plugin don't need to have interactive components in so we only replace the format but leave the player's message as-it, leaving the color codes unreplaced.

I am leaving this open, let me know if you have any more questions or I this helped!

**Comment by Sikatsu** [comment] 2019-09-10 07:48
I found another issue. If you put another color code between a color code, it will still apply.

http://prntscr.com/p44j89

**Comment by TNTUP** [comment] 2019-09-10 08:20
Heya, im following this issue aswell and I can reproduce it in chat or PMs^^ (Ver 8.3.16) ^^ I hope it won't be possible to either bypass any combination with &&&'s^^

**Comment by kangarko** [comment] 2019-09-11 05:47
Alright, seems like we have to find a better solution then removing colors, we will just leave them there and not replace them. I take a look at the system in the next days.

**Comment by kangarko** [comment] 2019-11-02 18:32
Closing, new versions don't hide color codes, they are show unaltered

**Closed by kangarko** 2019-11-02 18:32 UTC
Labels: Issue, in-progress
