### ISSUE TITLE
BungeeControlBridge with RedisBungeecord almost perfect

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#643] opened 2018-03-15 19:17 UTC
The new BungeeControlBridge functions quite well under redisbungee. Only a small amount of notifies does not function. I still haven't figured out why.
I have seen many notifications of people from different bungees as well as the one I am at. But for some reason, a few are not visible. Of the few I do not see, many of them happen on the same bungee as mine.

**Comment by kangarko** [comment] 2018-03-19 21:02
Hey, I have no idea sorry, and I cannot test it at the moment.

Can you check, whether or not this is related to the partial matching of /tell ? Example: do you get notification when you message with a partial completition (e.g. 'gark' for kangarko). Thanks.

**Comment by x1p** [comment] 2018-03-19 21:54
The only pattern I see is that it only happens with players on the same bungee as me. I happens also to other staff. Sometimes, while we are on the phone. It happens to them also, where I can do can see the notice.

**Comment by x1p** [comment] 2018-03-19 22:06
Done a second test:
player on the same bungee, same server not a problem. Different server, no notice.
Different player, same bungee, same server not a problem. Same bungee, different server, no problem.
I'm confused

**Comment by kangarko** [comment] 2018-03-22 19:28
I am investigating this. What exactly kind of notifications are not (sporadically) sent?

**Comment by x1p** [comment] 2018-03-23 10:41
Normally I only see that I'm missing something when a mute is executed. So I've missed the notify.ad or notify.swear.
But in this test (above), I've also used the notify.rulesalert. So that gives me the impression that it happens to basically all notifiers.

**Comment by kangarko** [comment] 2018-03-25 10:21
I added more debug messages to bungeecords. Set Debug to "["bungee"]" in settings.yml for each server and please take note at the console when it happens again. You should clearly see a log of any message being or (not being) sent out, so we can find the cause easily.

**Comment by x1p** [comment] 2018-03-25 12:47
Ok thanks. I will test very soon.

**Comment by x1p** [comment] 2018-03-26 21:42
Day 1 of the debug: cant reproduce.

What I do saw: each ignore string is matched (if possible of course) as if it was a match rule.
I would think it is only checked if the match regex of that rule is matched.
Doesn't this slow CHC down unnecessary?

**Comment by x1p** [comment] 2018-03-27 18:45
Day 2: I've got one!!

The broadcast was send by the server were the action took place.
2 Admin's were present on 2 different servers. One admin did receive it, another one did not receive it. Both admins have the same permissions.

**Comment by x1p** [comment] 2018-03-27 18:59
I do notice an unusual amount of errors concerning BungeeControlBridge on different Bungee's on other occasions. Maybe this has nothing to do with it. In that case I will make a separate issue.
https://hastebin.com/weyapehofo.lua
https://hastebin.com/yamiteseno.lua

**Comment by kangarko** [comment] 2018-03-28 19:30
I am on it, please allow me up till Monday when I get back home & we'll put this nasty bug where it belongs ; )

**Comment by kangarko** [comment] 2018-04-09 18:42
Closing, please let me know if issues persist. As I explained in #680, we rely on an external method to fetch the player, that may or may not be reliable.

**Closed by kangarko** 2018-04-09 18:42 UTC
Labels: Issue: complaint, Status: in progress
