### ISSUE TITLE
1.16.1: StackOverflowError when player leaves

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#1925] opened 2020-09-05 17:56 UTC
What happened:
- Player left the server
- Public chat says: `Player123 left the game` despite turned off
- Error on console: https://pastebin.com/raw/04pMZp8K

This error happens multiple times a day but not with everyone.
It also happens if the config is reloaded.
Since it happens regularly and the enormous length of the error and the fact that it annoys players , it's a pretty awful error.

messages.yml file:
`Hide_Join_Quit_Kick_Messages: true`

Expected behavior:
Always prevent join/leave messages.
Error graceful

Chc version 8.8.2
Paper 1.16.1
Using a mysql database

**Comment by kangarko** [comment] 2020-09-09 10:02
Sorry I was not able to reproduce: https://i.imgur.com/FjupSkN.png

Please send me the following information in private via PM on SpigotMC:

- Your full ChatControl folder as ZIP
- Your ChatControl_data table exported as SQL so I can import it and test

You can use uploadfiles.io for both.

Matej

**Comment by x1p** [comment] 2020-09-09 10:55
It only happens a few times a day. It's not very easy to reproduce.

Files send

**Comment by kangarko** [comment] 2020-09-09 11:03
Thanks.

**Comment by kangarko** [comment] 2020-09-09 11:31
Fixed in the next release :)

**Closed by kangarko** 2020-09-09 11:31 UTC
Labels: issue

**Comment by x1p** [comment] 2020-09-09 11:40
that was quickly found :-)
