### ISSUE TITLE
1.16.3: Bungee channel messages appear in logs, but they don't appear in the chat.

### ISSUE THREAD

**Issue by oberhauserg** [kangarko/ChatControl-Pro#1958] opened 2020-09-17 06:08 UTC
I want to be able to read messages from bungeecord in other servers. I have allowed the plugin to completely reset to a default config, enabled channels, then tried using the "global" channel to talk between servers. I have also made sure I have joined the channel, so I am reading it. However, I can only see the messages in /ChatControl/logs/channel-global.log. I am doing `tail --follow channel-global.log` and I can see the messages coming in.
I'm using version 8.8.5

My plugins folder is bigger than 10 MB, so I've uploaded it to dropbox here: https://www.dropbox.com/s/py7k65vzz8l8lo3/Plugins.zip

Thank you

**Comment by oberhauserg** [comment] 2020-09-17 07:42
I now know that it's a permissions issue. Our "God" role has `*` permissions, so we'll probably have to deny wildcard permissions on chatcontrol and be more selective. I'll try that and update once I get it working.

**Comment by kangarko** [comment] 2020-09-20 08:54
Thanks, to quickly ensure:

- Are you joining through bungeecord and not to the spigot server directly?
- Have you tried without other plugins to isolate the problem?

Matej

**Comment by BijuuKrunos** [comment] 2020-09-24 06:52
I have the same issue with ChatControlo 8.8.8 on MC 1.15.2.
The message is formatted in the console but no one can see the message ingame. with and without * Permission.
@oberhauserg did you found a solution? If not I will create a test System without other plugins to isolate the problem like Kangarko wrote.

Greetz
Krunos

**Comment by kangarko** [comment] 2020-09-24 18:22
Still cannot reproduce, @BijuuKrunos please ZIP me your full test environment with steps to reproduce.

**Comment by BijuuKrunos** [comment] 2020-09-24 19:42
Yeah I think this issue has something to do with other plugins or the permissions.
On my test environment withour other plugins it is working as it should.
I will look further from where this error comes from, but it seems that it has nothing to do with ChatControl himself.

I think you can close this.

Greetz
Krunos

**Comment by oberhauserg** [comment] 2020-09-25 16:03
I believe it happened because admins had permissions for `chatcontrol.bypass.ignore`. I'm not sure if this is expected behavior.

**Comment by kangarko** [comment] 2020-09-28 17:35
Sorry that I was not able to help but I am happy we could isolate the problem!

**Closed by kangarko** 2020-09-28 17:35 UTC
Labels: issue
