### ISSUE TITLE
[7.5.3] Own Factions Relation Color  is wrong

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#359] opened 2017-09-16 08:28 UTC
Hi, now factions color work, but i see all members of my faction in chat with red tag instaed, it must be green.

**Comment by kangarko** [comment] 2017-09-17 16:57
Please post me your settings.yml and formatting.yml with the variable.

What factions plugin are you using?

**Comment by xion87** [comment] 2017-09-18 08:23
I am using Factions Mcore
Settings: https://hastebin.com/qixejevopo.php
Format: https://hastebin.com/hazufeqifu.php

My prefix for example was white, and when somesone do /f enemy me, my factions it will became red for myself, or purple or green when they do the relation command

**Comment by kangarko** [comment] 2017-09-22 16:21
Sorry for the delay, I am currently setting a support team because of the load, please allow me additional 1-2 days to resolve your issue.

**Comment by kangarko** [comment] 2017-09-25 19:08
Sorry I have to delay it again due to stay in the outlands. Thanks. I will get to it 3nd of October.

**Comment by kangarko** [comment] 2017-09-25 19:08
@malon could you be able to reproduce this bug please?

**Comment by malonnnn** [comment] 2017-10-12 18:49
@kangarko 

I'm sorry I don't know anything about factions.

**Comment by kangarko** [comment] 2017-10-19 20:12
Closing because we are investigating this issue in https://github.com/kangarko/ChatControl-Pro/issues/406

**Closed by kangarko** 2017-10-19 20:12 UTC
Labels: Issue: cannot reproduce, Status: queued
