### ISSUE TITLE
Error on Tab Completion 

### ISSUE THREAD

**Issue by zeronerve** [kangarko/ChatControl-Pro#1454] opened 2019-11-24 18:54 UTC
Got this when trying to tab complete the /gamemode... command.  Using Paper 1.14 latest build. And ChatControl Pro 8.4.8

`[12:50:11] [Server thread/ERROR]: [ChatControl] Unhandled exception occured in onPacketSending(PacketEvent) for ChatControl
com.comphenix.protocol.reflect.FieldAccessException: No field with type [Ljava.lang.String; exists in class PacketPlayOutTabComplete.
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:216) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[?:?]
	at org.mineacademy.chatcontrol.hook.super$3.onPacketSending(SourceFile:193) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:364) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:63) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:329) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:299) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:200) ~[patched_1.14.4.jar:git-Paper-223]
	at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:169) ~[patched_1.14.4.jar:git-Paper-223]
	at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:163) ~[patched_1.14.4.jar:git-Paper-223]
	at net.minecraft.server.v1_14_R1.PlayerConnection.lambda$null$2(PlayerConnection.java:565) ~[patched_1.14.4.jar:git-Paper-223]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_222]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:669) ~[?:1.8.0_222]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:1997) ~[?:1.8.0_222]
	at net.minecraft.server.v1_14_R1.PlayerConnection.lambda$a$3(PlayerConnection.java:563) ~[patched_1.14.4.jar:git-Paper-223]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-223]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-223]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-223]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-223]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-223]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-223]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-223]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-223]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-223]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[12:50:11] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_14_R1.PacketPlayOutTabComplete@7091afbe[
    a=0
    b=Suggestions{range=StringRange{start=0, end=4}, suggestions=[Suggestion{range=StringRange{start=0, end=4}, text='gamemode', tooltip='null'}, Suggestion{range=StringRange{start=0, end=4}, text='gamerule', tooltip='null'}]}
  ]
`

**Comment by lackoSK** [comment] 2019-11-25 14:47
Hello,

Which ProtocolLib are you running? 

Please update to the latest version if you aren't running it.

https://www.spigotmc.org/resources/protocollib.1997/

Thanks!

**Comment by zeronerve** [comment] 2019-11-25 20:05
I don't think i was on the latest version, but I've updated, so we'll see if it keeps happening. Thanks.

**Comment by lackoSK** [comment] 2019-11-26 16:42
Hello,

Are you still having issues or any questions you want to ask?

Regards,
lackoSK

**Comment by zeronerve** [comment] 2019-11-29 15:48
Still looking for the problem to occur again. I've updated to the latest version and I don't think it's happening, but I'd like to check during a busier time.

**Comment by lackoSK** [comment] 2019-12-07 11:43
Closing this issue, user not responding.

**Comment by zeronerve** [comment] 2019-12-07 17:03
I needed to evaluate this in a busier time. We're still having the issue on the latest version of protcolLib.

**Comment by kangarko** [comment] 2019-12-11 17:23
Sorry this looks to me like it has to do with ProtocolLib, I cannot reproduce this

**Comment by zeronerve** [comment] 2020-03-15 00:59
Sorry to revive an old thread, but I'm on the latest version of ProtocolLib and I'm getting this on tab-complete ....

`[19:53:54 ERROR]: [ChatControl] Unhandled exception occured in onPacketSending(PacketEvent) for ChatControl
com.comphenix.protocol.reflect.FieldAccessException: No field with type [Ljava.lang.String; exists in class PacketPlayOutTabComplete.
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:216) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[?:?]
        at org.mineacademy.chatcontrol.final.nul. .C$3.onPacketSending(SourceFile:193) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_13_R2.NetworkManager.b(NetworkManager.java:209) ~[patched_1.13.2.jar:git-Paper-652]
        at net.minecraft.server.v1_13_R2.NetworkManager.sendPacket(NetworkManager.java:172) ~[patched_1.13.2.jar:git-Paper-652]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1506) ~[patched_1.13.2.jar:git-Paper-652]
        at net.minecraft.server.v1_13_R2.PlayerConnection.sendPacket(PlayerConnection.java:1479) ~[patched_1.13.2.jar:git-Paper-652]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
        at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:686) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.lambda$scheduleMainThread$1(ChannelInjector.java:505) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-652]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-652]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.2.jar:git-Paper-652]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-652]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-652]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-652]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[19:53:54 ERROR]: Parameters:
  net.minecraft.server.v1_13_R2.PacketPlayOutTabComplete@1f87bc04[
    a=0
    b=Suggestions{range=StringRange{start=4, end=8}, suggestions=[Suggestion{range=StringRange{start=4, end=8}, text='zeronerve', tooltip='null'}]}
  ]
`

**Comment by zeronerve** [comment] 2020-03-15 01:02
I'm now on ChatControl 8.6.6 and ProtocolLib 4.5.0 on Paper build 52 (1.13.2)

**Comment by kangarko** [comment] 2020-05-11 04:49
@lackoSK missed this

**Comment by lackoSK** [comment] 2020-05-11 09:15
Hello,

Are you still having issues? 

Regards,
lackoSK

**Comment by zeronerve** [comment] 2020-05-11 13:18
Yes. Let me check my recent logs and I'll get back to you today.

**Comment by zeronerve** [comment] 2020-05-11 21:06
Using version 8.6.6
on Paper build 245 (1.15.2)
ProtocolLib 4.5

We're still seeing this...

`
[12:59:24 ERROR]: [ChatControl] Unhandled exception occured in onPacketSending(PacketEvent) for ChatControl
com.comphenix.protocol.reflect.FieldAccessException: No field with type [Ljava.lang.String; exists in class PacketPlayOutTabComplete.
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:216) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[?:?]
        at org.mineacademy.chatcontrol.final.nul. .C$3.onPacketSending(SourceFile:193) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_15_R1.NetworkManager.b(NetworkManager.java:241) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.NetworkManager.dispatchPacket(NetworkManager.java:217) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.NetworkManager.o(NetworkManager.java:273) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.NetworkManager.sendPacketQueue(NetworkManager.java:259) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.NetworkManager.sendPacket(NetworkManager.java:213) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.NetworkManager.sendPacket(NetworkManager.java:186) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.PlayerConnection.lambda$null$2(PlayerConnection.java:584) ~[patched_1.15.2.jar:git-Paper-245]
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:669) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:1997) ~[?:1.8.0_201]
        at net.minecraft.server.v1_15_R1.PlayerConnection.lambda$a$3(PlayerConnection.java:579) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1081) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1074) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1035) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:950) ~[patched_1.15.2.jar:git-Paper-245]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
`

**Comment by lackoSK** [comment] 2020-05-13 17:04
Hello,

Can you please run /protocol dump and send me the output?

Sincerely,
Ladislav from MineAcademy.org

**Comment by zeronerve** [comment] 2020-05-13 17:27
May I email or DM?

**Comment by lackoSK** [comment] 2020-05-14 19:14
Hello,

Okay, I got a response from their support. 
**They said you need to update your paper server jar.** 

Sincerely,
Ladislav from MineAcademy.org

**Comment by zeronerve** [comment] 2020-05-14 19:33
Thanks for forwarding the issue. I keep Paper updated.  Were they implying that a new build has fixed this?

**Comment by lackoSK** [comment] 2020-05-15 12:58
They said

"update paper, you are using an ancient version..."

**Comment by zeronerve** [comment] 2020-05-15 13:00
Paper was updated at the time of my last error post, and I don't think the
person who replied is with protocollib? Mrtiennes?

The problem is occurring with the latest version.

**Comment by lackoSK** [comment] 2020-05-15 13:08
I got respond from MiniDigger

**Comment by zeronerve** [comment] 2020-05-15 13:12
Yes my mistake. Regardless of who responded, we are getting the error in
the latest Paper. Thank you for looking at this.

**Comment by lackoSK** [comment] 2020-05-15 13:32
Thanks! Told them.

**Comment by lackoSK** [comment] 2020-05-17 16:16
Hello,

These issues should be fixed within the next release of ChatControl-Pro.

Sincerely,
Ladislav from MineAcademy.org

**Comment by lackoSK** [comment] 2020-05-17 16:16
Hello,

Do you still need help? If yes, please comment under this issue and **mention me to respond!**. 
Example: 
`Yes, I do! @lackoSK `

If not, then we hope your issue was solved! If there is anything more we can do for you, just follow the "Yes" part.

 Anyways, have a beautiful day!

Sincerely,
Ladislav from MineAcademy.org

**Closed by lackoSK** 2020-05-17 16:16 UTC
Labels: Issue
