### ISSUE TITLE
Error on 8.4.12

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#1479] opened 2019-12-13 21:28 UTC
```
[22:17:20 ERROR]: Fatal error trying to convert ChatControl v8.4.12:org/mineacademy/chatcontrol/ChatControl.class
java.lang.IllegalArgumentException: null
at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.<init>(ClassReader.java:258) ~[patched_1.14.4.jar:git-Paper-235]
at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.<init>(ClassReader.java:176) ~[patched_1.14.4.jar:git-Paper-235]
at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.<init>(ClassReader.java:162) ~[patched_1.14.4.jar:git-Paper-235]
at org.bukkit.craftbukkit.v1_14_R1.util.Commodore.convert(Commodore.java:170) ~[patched_1.14.4.jar:git-Paper-235]
at org.bukkit.craftbukkit.v1_14_R1.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:283) ~[patched_1.14.4.jar:git-Paper-235]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:112) ~[patched_1.14.4.jar:git-Paper-235]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-235]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:63) ~[patched_1.14.4.jar:git-Paper-235]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.14.4.jar:git-Paper-235]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:337) ~[patched_1.14.4.jar:git-Paper-235]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:257) ~[patched_1.14.4.jar:git-Paper-235]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:355) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:226) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-235]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[22:17:21 ERROR]: Could not load 'plugins/ChatControl-8.4.12.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ClassFormatError: Unknown constant tag 0 in class file org/mineacademy/chatcontrol/ChatControl
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:138) ~[patched_1.14.4.jar:git-Paper-235]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:337) ~[patched_1.14.4.jar:git-Paper-235]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:257) ~[patched_1.14.4.jar:git-Paper-235]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:355) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:226) ~[patched_1.14.4.jar:git-Paper-235]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-235]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassFormatError: Unknown constant tag 0 in class file org/mineacademy/chatcontrol/ChatControl
at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_212]
at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_212]
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_212]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[patched_1.14.4.jar:git-Paper-235]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-235]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:63) ~[patched_1.14.4.jar:git-Paper-235]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.14.4.jar:git-Paper-235]
... 6 more
```

**Comment by ElBananaa** [comment] 2019-12-13 21:46
Hey!
Same error for me since the last update, and there's no way to download a previous version ! Please update

**Comment by x1p** [comment] 2019-12-13 22:07
See your spigot page under "history"

Always first test on an empty server before you put it on a production server

**Comment by lackoSK** [comment] 2019-12-14 07:08
Sorry but I’ve tested it, was working... Will have a look ASAP

**Comment by merlinshaw** [comment] 2019-12-14 21:53
Same error as well.

**Comment by Kedarin** [comment] 2019-12-15 00:31
same error

**Comment by JavaFactoryDev** [comment] 2019-12-15 10:52
Will be fixed asap.

**Comment by lackoSK** [comment] 2019-12-15 14:02
We're sorry for the delay. We are waiting for kangarko to fix the issue.  The issue is in our backend server. Please be patient.

**Comment by mibby** [comment] 2019-12-18 11:39
@lackoSK Have you heard from @kangarko about this issue yet? I would really like to re-enable ChatControlPro for 1.15.1. :(

```
[03:27:46] [Server thread/ERROR]: Fatal error trying to convert ChatControl v8.4.12:org/mineacademy/chatcontrol/ChatControl.class
java.lang.IllegalArgumentException: null
	at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.<init>(ClassReader.java:258) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.<init>(ClassReader.java:176) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.<init>(ClassReader.java:162) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.craftbukkit.v1_15_R1.util.Commodore.convert(Commodore.java:170) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.craftbukkit.v1_15_R1.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:283) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:112) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[paperclip.jar:git-Purpur-348]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_232]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_232]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:63) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:337) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:257) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:356) ~[paperclip.jar:git-Purpur-348]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:235) ~[paperclip.jar:git-Purpur-348]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:886) ~[paperclip.jar:git-Purpur-348]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
[03:27:46] [Server thread/ERROR]: Could not load 'plugins/ChatControl-8.4.12.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ClassFormatError: Unknown constant tag 0 in class file org/mineacademy/chatcontrol/ChatControl
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:138) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:337) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:257) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:356) ~[paperclip.jar:git-Purpur-348]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:235) ~[paperclip.jar:git-Purpur-348]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:886) ~[paperclip.jar:git-Purpur-348]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.ClassFormatError: Unknown constant tag 0 in class file org/mineacademy/chatcontrol/ChatControl
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_232]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_232]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_232]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[paperclip.jar:git-Purpur-348]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_232]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_232]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:63) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[paperclip.jar:git-Purpur-348]
	... 6 more
```

**Comment by lackoSK** [comment] 2019-12-18 15:28
Hey,

Download the newest ChatControl guys ;)

Regards,
lackoSK

**Closed by lackoSK** 2019-12-18 15:28 UTC
Labels: Issue

**Comment by mibby** [comment] 2019-12-18 16:24
@lackoSK Error seems to be gone now but is there any way to override the forced disabling with ChatControlPro v8.4.13 on 1.15.1? I just use and need basic features like formatting and message announcements. :(

```
[08:17:58] [Server thread/INFO]: [ChatControl] Enabling ChatControl v8.4.13
[08:17:58] [Server thread/INFO]: !-----------------------------------------------------!
[08:17:58] [Server thread/INFO]: ** Your Minecraft version v1_15 has not yet
[08:17:58] [Server thread/INFO]: been officialy tested with the Foundation
[08:17:58] [Server thread/INFO]: library that powers the ChatControl plugin.
[08:17:58] [Server thread/INFO]:  
[08:17:58] [Server thread/INFO]: For your safety, the plugin is now disabled.
[08:17:58] [Server thread/INFO]: !-----------------------------------------------------!
```

**Comment by lackoSK** [comment] 2019-12-18 17:12
This means it's not **yet** compatible. Foundation is our 'manager' that is doing everything for our plugins.

**Comment by granis** [comment] 2019-12-22 22:15
Any ETA on when Foundation is 1.15-compatible?
