### ISSUE TITLE
Issues Transferring From Localhost to Live Server

### ISSUE THREAD

**Issue by KensonPlays** [kangarko/ChatControl-Pro#278] opened 2017-07-05 21:57 UTC
The filters were working on localhost, but once I uploaded it to my live server, it seems it's not triggering on any of the bad words in the filter/anti advertisement filters. Here is my settings.yml and rules.txt:
https://pastebin.com/piSSkZ2Y -- settings.yml
https://pastebin.com/b3KjXmvS -- rules.txt

Depending on how we fix this, will tell me if I'll purchase Pro or not.

**Comment by KensonPlays** [comment] 2017-07-07 05:24
Ended up purchasing, but none of the filters/custom death messages are appearing. All the YML is valid, according to multiple validators.

**Comment by EvilOlaf** [comment] 2017-07-07 06:36
@kandaro is still on vacation AFAIK. Therefore support might be delayed ;). 

Any errors or hints in console? If in doubt please post a full startup log to pastebin.

**Comment by KensonPlays** [comment] 2017-07-07 06:39
Here's my paste (I'm trying to use Github Gist more often): https://gist.github.com/KensonPlays/963c487739d872c78ee21cf5ef4b8a0f

**Comment by EvilOlaf** [comment] 2017-07-07 07:49
This is from a server startup? 
You can see that CHC disabled itself, because something is missing.

**Comment by KensonPlays** [comment] 2017-07-07 07:58
Yea, it's from a startup. I'm not completely sure what's going on.
https://gist.github.com/KensonPlays/28290c8dc1cad7465d85b60512d38bdc

That's from a recent /reload.
Yea, I know /reload isn't completely recommended, but I wanted to get some of the logs to you.

**Comment by KensonPlays** [comment] 2017-07-07 08:25
IIRC, something about "Prefix" or "Suffix" was an error I got earlier. I checked all 4 YML files in the root directory of the plugin, and I can't seem to find anything referring to the error I'm receiving.

**Comment by KensonPlays** [comment] 2017-07-07 08:29
Rules.txt gives me the following parse error on a validator, though:


> Error : Unable to parse.
> Line : 68  match \b[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}\b

**Comment by KensonPlays** [comment] 2017-07-07 08:51
Console told me to run **/vault-info**. This is what it returns:
http://i.imgur.com/OnpriLf.png

**Comment by KensonPlays** [comment] 2017-07-07 09:12
Somehow, I fixed it. If I find the reason for the problem, I will post it here. Leaving it up for a few days to see if I can figure out why.

**Comment by KensonPlays** [comment] 2017-07-07 09:18
Okay. I _think_ I figured out the problem.

When I went into settings.yml, and turned on the channels feature (changing it from 'false' to 'true'), it seems to break the plugin and so the channels feature isn't working for me.

**Comment by EvilOlaf** [comment] 2017-07-07 10:24
That's kind a odd. 

Most common issue when transferring edited files to server, especially when the source system is MS windows and the target system is *nix based, is file encoding. Therefor it is strongly recommended to use notepad++ for editing any files from CHC on MS Windows.

**Comment by KensonPlays** [comment] 2017-07-07 20:00
Yea, I was using the multicraft editor haha. I copied over the edits FROM notepad++ to the multicraft editor and saved, seems to have worked.

**Comment by kangarko** [comment] 2017-07-08 18:53
Hey,

glad to hear you'd solved the problem. From my experience, these things work:

**Parsing files:**
* Do not parse rules.txt or any other files in rules/ directory using a validator. We use an own language so it won't work.
* For .yml files settings.yml, messages.yml, chat.yml and handlers.yml, I personally find using only [this](https://yaml-online-parser.appspot.com/) validator sufficient. It covers 100% and thus saves times.

**Encoding**
* Each system accepts different encodings. I personally use Notepad++ to save the files with the UTF-8 or UTF-8 with BOM encoding options.
* Multicraft text editors may or may not respect encoding and may or may not break the files.
* Windows text editors do NOT support encoding and will break the files (Notepad, Wordpad).

**Vault**
* When the plugin refuses to start and refers to the /vault-info command, it is because you have either Chat Formatter or Chat Channels enabled and you lack a plugin to manage players' prefixes and suffixes. Note the "Chat: None" line in your picture. Generally speaking, PermissionsEx installed is fully sufficient to solve the problem (or any other plugin capable of setting up prefixes and suffixes).

**Comment by KensonPlays** [comment] 2017-07-08 20:57
> When the plugin refuses to start and refers to the /vault-info command, it is because you have either Chat Formatter or Chat Channels enabled and you lack a plugin to manage players' prefixes and suffixes. Note the "Chat: None" line in your picture. Generally speaking, PermissionsEx installed is fully sufficient to solve the problem (or any other plugin capable of setting up prefixes and suffixes).

I do not use PermissonsEx. I use Ultra Permissions. But it's green, everything working (except channels, which are disabled since it seems to break the plugin?).

**Comment by KensonPlays** [comment] 2017-07-09 21:23
Am updating now. I didn't get an 'new update' notification, thanks for letting me know!

**Comment by KensonPlays** [comment] 2017-07-09 21:39
So, channels are enabled and plugin (mostly) works now. Tried sending a message to the donor channel via **/ch send donor hi**

and this popped up in the console: https://gist.github.com/KensonPlays/af9d142a9a0bf7f8c44e8c4f05d7cd6c

**Comment by EvilOlaf** [comment] 2017-07-10 05:16
`09.07 14:39:50 [Server] WARN java.lang.NullPointerException: Chat format 'Donor_Chat' doesn't exist in chat.yml! Available: Private_Message_Receiver, Example_Format, Admin_Chat, Bungee_Chat, Private_Message_Sender, Spy_Chat, Global_Chat`

Create a definition for your `Donor_Chat` in your `chat.yml`. ;)

**Comment by kangarko** [comment] 2017-07-10 19:13
Kenson, please do as Olaf says. Make the Donor_Chat format and the error will disappear :)

Olaf, what do you mean by silencing a NPE on missing definitions? Is this the error we're talking about that the Kenson posted? If so, I am not silencing it. Users need to know that something they've configured won't work due to a missing format.

**Comment by KensonPlays** [comment] 2017-07-10 19:30
But donor does exist I think? http://i.imgur.com/EADSzgB.png

**Comment by EvilOlaf** [comment] 2017-07-10 19:34
@kangarko Yes, I am talking about this issue.
I probably was not precisely enough. I meant to say silent the stack trace, not the essential error message ;)

**Comment by kangarko** [comment] 2017-07-13 18:42
To correct some confusion, there are two parts of the plugin we're talking about:

1. Chat channels (define the channel and its options)
2. Chat formatters (how the channel message looks like)

You have set 'donor' as your channel name. This is what your picture shows. If you navigate above that section, there should be a Formats section at the very top of that file. You need to make a 'Donor_Chat' formatter there.

@EvilOlaf The stack trace comes from how the code is written. It stops processing what else would not work anyways. If I would only print an error message, the processing could not be stopped upstream, only in that very method. Currently that's the best way imo.

**Comment by KensonPlays** [comment] 2017-07-16 01:54
I'll take a look into it shortly. Opening another thread with a regex question.

**Comment by KensonPlays** [comment] 2017-07-16 02:49
the 'donor:' line does exist, so does Mod and Admin: http://i.imgur.com/GAVgcej.png

**Comment by kangarko** [comment] 2017-07-16 12:14
Can you post me the entire chat.yml file please?

**Comment by KensonPlays** [comment] 2017-07-16 20:09
https://gist.github.com/KensonPlays/521d7addc3b1e01f0ed45e21fdfa3210

**Comment by kangarko** [comment] 2017-07-17 10:04
I've tested the file without any issues. Does it run fine as per now? I don't know what the problem was, it seemed to be that you had the Donor_Chat formatter before assigned to your donor channel (that didn't exist), and now you have Donor formatter assigned there which is correct.

**Comment by KensonPlays** [comment] 2017-07-17 18:10
Maybe it's a plugin incompatibility?

Know of any plugins that are incompatible?

**Comment by kangarko** [comment] 2017-07-18 10:31
It's very unlikely so.

Are you still getting an error? If so please repost it so I can reproduce with your exact chat.yml

**Comment by kangarko** [comment] 2017-07-31 09:33
Closing, assuming fixed.

Please remind me if not.

**Closed by kangarko** 2017-07-31 09:33 UTC
Labels: Issue: complaint, Question
