### ISSUE TITLE
chc reload/message twice

### ISSUE THREAD

**Issue by TomasOlsson** [kangarko/ChatControl-Pro#464] opened 2017-11-05 22:21 UTC
I'm having trouble when I do / chc reload.

Have shared chat over my entire bungee cord network and on the server that I reload on, send the same message twice as you type. Do not know if I've missed something in config but find nothing that might be wrong.

Latest Spigot
Latest Bungee cord
ChatControl Pro 7.6.7

**Comment by CrashOverrideMC** [comment] 2017-11-05 23:34
I have noticed this too after I do reload whatever I say shows up in adminchat and standard channel. I use plugman, I unload and load plug in and fixes it.

**Comment by kangarko** [comment] 2017-11-06 22:16
Hey!

I apology for the bug. I am closing this in faith that the next release that also solves https://github.com/kangarko/ChatControl-Pro/issues/468 has resolved this as well. From my testing, I could not reproduce it after the changes made there, but surely remind me if you experience anything unusual.

Have a great day/evening!

**Closed by kangarko** 2017-11-06 22:16 UTC
