### ISSUE TITLE
Sound notify doesn't work

### ISSUE THREAD

**Issue by Heliosard** [kangarko/ChatControl-Pro#519] opened 2017-12-06 13:51 UTC
ChatControl Pro: **7.6.18**
ProtocolLib: **4.3.0**
Server version: **CraftBukkit version git-TacoSpigot-"c2835dfc" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)**

The notification system does not work: no change of the color nickname, no sound notification.
![image](https://user-images.githubusercontent.com/31409151/33664624-92d15fd4-da94-11e7-9ff0-9275f1f347c5.png)

Config: https://hastebin.com/kudihitene.rb

**Comment by kangarko** [comment] 2017-12-08 18:19
Hey, I cannot reproduce, make sure you waited 10 seconds between each attempt
![a](https://i.imgur.com/T9Llvxd.png)

What part of the plugin are you using it in? Channels, formatter?

Try giving yourself OP on a test account to except a permission-related problem.

**Comment by kangarko** [comment] 2017-12-16 18:31
Closing in faith this has been resolved.

**Closed by kangarko** 2017-12-16 18:31 UTC
Labels: Issue: cannot reproduce
