### ISSUE TITLE
Anti-Bot Cooldown Not Working

### ISSUE THREAD

**Issue by MrHumblePie** [kangarko/ChatControl-Pro#458] opened 2017-11-01 20:41 UTC
Hello, so I have set my options as seen below however players seem free to leave and enter regardless of these cool down settings. I have restarted the server etc and tried everything but the rejoin factor seems to have no effect at all. 

```
# -------------------------------------------------------------------------------------------------
# Reduce impact of spamming bots
# -------------------------------------------------------------------------------------------------
Anti_Bot:
  
  Cooldown: 
  
    # How many seconds the player needs to wait before logging in again?
    Rejoin: 5
    
    # How many seconds must the player wait after login to chat?
    Chat_After_Login: 0
    
    # How many seconds must the player wait after login to run commands?
    Command_After_Login: 0
  
  # Block chat until the player has moved? They can still execute commands.
  Block_Chat_Until_Moved: true
  
  # A list of commands to block until the player has moved.
  # To disable, set to: Block_Commands_Until_Moved: '[]'
  Block_Commands_Until_Moved: []
```

**Comment by ipr0james** [comment] 2017-11-02 20:35
Just looking at this myself, I'm seeing the same result though I've only had chance to have a quick look due to lack of internet. Hopefully someone can take a further look..

**Comment by ipr0james** [comment] 2017-11-04 17:44
I've just re-looked at this issue. I was using an account with permissions I hadn't  fully checked back to their full root and had a permission to bypass. after checking with default perms and no bypass the feature is working fine for me, However I'm on an older version, I can't currently download a new as I'm working mainly offline due to no internet, replying to Github by phone..

**Comment by MrHumblePie** [comment] 2017-11-04 21:45
Heya, I can confirm that my users have no chatcontrol permissions (unless the perm to bypass cool down is given to them automatically - which would be odd), I'm on latest version, can confirm the cool down setting has no effect.

**Comment by ipr0james** [comment] 2017-11-04 22:22
I'll try get latest tomorrow so I can confirm issue. Hoping new provider will have me online by then..

**Comment by kangarko** [comment] 2017-11-09 20:30
Hello,

I have tested this myself, it does work correctly on my system. Please make sure, if you have Groups enabled, that settings there correspond with the main Anti_Bot settings, as they override them.

![a](https://i.imgur.com/FvtB5D6.png)

**Comment by MrHumblePie** [comment] 2017-11-09 20:36
Hiya, 1.12.2.-RO.1-snapshot

Players can join freely on my server there is no whitelist or anything like that. 

No errors on console. 

Groups are not enabled. 

For some reason it just doesn't work for me at all.

**Comment by kangarko** [comment] 2017-11-09 20:46
Hmm that's totally odd, honestly I would blame a third party cause.

If you have an extra time, you could firstly make a totally dummy test server on your Windows/Mac with purely ChatControl, to see if the feature works for you, at all, without any other plugins (takes under 10 mins). 

If it will work, then its sadly another plugin blocking it. You could then temporary disable plugins one-by-one to see which one is the cause of the problem (this takes longer but I cannot do it for you I am sorry).

**Comment by MrHumblePie** [comment] 2017-11-09 21:24
Heya, I'd already tried it on a clean test server, still doesn't work there for me either I'm afraid.

**Comment by kangarko** [comment] 2017-11-11 17:15
Just to be sure, could you post me:

1. Full startup log.
2. settings.yml (without MySQL part if you have it)

**Comment by MrHumblePie** [comment] 2017-11-12 09:22
Sure, please see attached, I've again started a completely new server and the only things i have installed are chc and protocol lib; I've not even touched the settings or anything, still doesn't work for me. I don't know if I'm just missing something insanely obvious at this point. 

[latest.log](https://github.com/kangarko/ChatControl-Pro/files/1464474/latest.log)

[settings.yml.zip](https://github.com/kangarko/ChatControl-Pro/files/1464475/settings.yml.zip)

**Comment by MrHumblePie** [comment] 2017-11-12 18:37
Thats just because I those logs were from a new server, literally just booted up with fresh spigot, chc and protocollib. I edit my configs across ftp filezilla and using TextWrangler. However its worth noting that in that example I did not touch anything, just using the default configs which have a 4 second (iirc) delay.

**Comment by kangarko** [comment] 2017-11-12 18:40
I have enabled extra debug to the next version, please set Debugger.Sections to [antibot] and see the console on re-joining.

**Comment by ipr0james** [comment] 2017-11-29 12:10
I've just tested this with the latest version.
Are you still seeing issues @MrHumblePie ? If so would it be possible to come and see your server firsthand to see it not working and we can trace it down from there.

**Comment by kangarko** [comment] 2017-12-16 18:32
Closing in faith this has been resolved.

**Closed by kangarko** 2017-12-16 18:32 UTC
Labels: Issue: cannot reproduce, Status: awaiting answer
