### ISSUE TITLE
1.16.4: Formatting broken

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#2128] opened 2020-11-13 14:59 UTC
Formatting doesn't seem to work on version 8.9.2. It just shows "<{playername}>" with `{playername}` being the players username. Before updating it was working as intended now it doesn't format at all.
the `formatting.yml` has:
```yaml
Enabled: true
```
paper 1.16.4 build 275
chc pro 8.9.2
**It was working on build 8.9.0-BETA**
**EDIT:**
All formatting is removed with `Bungeecord: true` is set in the settings.yml so that's the bug.

**Comment by kangarko** [comment] 2020-11-16 16:31
I do have BungeeCord enabled, channels disabled and formatting enabled on latest version, but I cannot reproduce. I assume it's due to the other error you're getting so I am closing this since it should self-fix itself when I fix the other problem to the next release.

If not please comment below with your ZIP folder of ChatControl

**Closed by kangarko** 2020-11-16 16:31 UTC
Labels: issue
