### ISSUE TITLE
Chatcontrol crash/freeze the console

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#1622] opened 2020-04-11 18:51 UTC
I just update all server with version 8..6.6 and now randomly server will crash after a good while (it happened to 2-4 server with different paper version 1.8.8, and 1.1.5.2) on 1..8.8 i got the crash dump
https://gist.github.com/xion87/cb34125dac5ac70ccccebf597a1400c5

**Comment by lackoSK** [comment] 2020-04-11 19:18
Hello there...

"Please report this to PaperSpigot directly!"

Also, it seems to do something with other plugins... (FactionChat)
[17:37:24] [PaperSpigot Watchdog Thread/ERROR]: 		nz.co.lolnet.james137137.FactionChat.FactionChatListener.onChat(FactionChatListener.java:140)
[17:37:24] [PaperSpigot Watchdog Thread/ERROR]: 		nz.co.lolnet.james137137.FactionChat.FactionChatListener.onPlayerChat(FactionChatListener.java:121)
[17:37:24] [PaperSpigot Watchdog Thread/ERROR]: 		nz.co.lolnet.james137137.FactionChat.FactionChatListener$1.execute(FactionChatListener.java:58)

Regards,
lackoSK

**Comment by xion87** [comment] 2020-04-12 07:08
is not from that, because before update was working perfect (using 8.6.4), then i just upgraded luckperms and chatcontrol on all server, and these server start to freeze after 10-12 hours or crash sudently with that dump (1.8.8 and 1.15.2)

**Comment by lackoSK** [comment] 2020-04-15 12:39
Hello,

Can you tell me how am I supposed to restimulate this issue? What all ale of your plugins?

Sincerely,
Ladislav from MineAcademy.org

**Comment by xion87** [comment] 2020-04-15 14:58
it happen randomly, a i know it just freezed 4-5 server 2 times in 2 days when i have upgraded chatcontrol

**Comment by lackoSK** [comment] 2020-04-18 09:38
Hello,

The problem is we need to simulate this issue.  And if we can not, we can not fix it because we do not know what to fix exactly.

Can you please wait until next ChatControl's release and test it then? 

Sincerely,
Ladislav from MineAcademy.org

**Comment by xion87** [comment] 2020-04-18 09:40
but the log don't help? i see chatcontrol here

**Comment by lackoSK** [comment] 2020-04-18 09:59
Hello,

Just wait until the next release please, big changes are coming. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by xion87** [comment] 2020-04-18 10:00
oke :)

**Comment by PatoTheBest** [comment] 2020-04-22 00:47
I'm seeing the same crash. Just people chatting normally
```
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: The server has stopped responding!
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: Please report this to PaperSpigot directly!
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: Be sure to include ALL relevant console errors and Minecraft crash reports
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: ------------------------------
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to PaperSpigot!):
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: ------------------------------
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: Current Thread: Server thread
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 	PID: 17 | Suspended: false | Native: false | State: WAITING
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 	Stack:
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		sun.misc.Unsafe.park(Native Method)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lock(ReentrantReadWriteLock.java:943)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		org.mineacademy.chatcontrol.final.nul. .bi.a(SourceFile:1473)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		org.mineacademy.chatcontrol.final.nul. .bi.put(SourceFile:1118)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		org.mineacademy.chatcontrol.ChatControl.a(SourceFile:589)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		org.mineacademy.chatcontrol.ChatControl.a(SourceFile:582)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		org.mineacademy.chatcontrol.final.nul. .N.onJoin(SourceFile:118)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		java.lang.reflect.Method.invoke(Method.java:498)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:307)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:311)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:170)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:886)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:422)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:724)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:627)
[02:36:28] [PaperSpigot Watchdog Thread/ERROR]: 		java.lang.Thread.run(Thread.java:748)
```

**Comment by lackoSK** [comment] 2020-04-25 18:43
Yeah, please, just wait, we are almost finishing

**Comment by PatoTheBest** [comment] 2020-05-06 19:53
@lackoSK Why was this closed? When is the update coming?

**Comment by lackoSK** [comment] 2020-05-06 19:58
We are testing the new ChatControl (only BETA testers have access)

**Comment by lackoSK** [comment] 2020-05-06 19:58
we should release Sunday

**Comment by kangarko** [comment] 2020-05-15 06:32
Lets close this when it is properly fixed, apology for the delays.

**Comment by lackoSK** [comment] 2020-06-11 06:04
Hello,

We've recently updated the version to 9.0.0. Can you please update and test it out here? Thank you.

Sincerely,
Ladislav from MineAcademy.org

**Closed** 2020-06-19 12:14 UTC
Labels: Issue

**Comment by xion87** [comment] 2020-08-08 11:38
Since now 9.x is not released, where the issue will go? i am afraid to upgrade again

**Comment by kangarko** [comment] 2020-08-12 15:34
Are you still having this problem on the latest 8.x.x? Please downgrade and use that, I am personally updating it right now. If still having problems, simply open a new ticket, thank you!

**Comment by xion87** [comment] 2020-09-18 15:59
Hi, issue still persist on  ChatControl v8.8.5. it cause random freeze after some hours, i throught it was not chatcontrol but today i got a nice crash dump https://gist.github.com/xion87/c16f3e59696b54f013ff9a511ed8f901
Using paperspigot 1.8.8
Please fix....

**Comment by kangarko** [comment] 2020-09-20 08:21
Please test the next version. Also the version you provided is an outdated one. I have made the error do nothing and not even print to file to see if that helps resolve the problem.

If the error happens please repost using the latest version otherwise I am not able to track the error lines since they are different because the code already changed.
