### ISSUE TITLE
chatcontrol.bypass.rules.packets spams permission checks 400+ times a second.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#433] opened 2017-10-19 10:38 UTC
ChatControlPro 7.5.16

Enabling permission verbose to see what permissions were constantly being checked, I noticed ```chatcontrol.bypass.rules.packets``` is being constantly spammed for checks 400+ times a second.

```
[03:29:47] [main/INFO]: [CHAT] [LP] VB > mibby - chatcontrol.bypass.rules.packets - true
[03:29:47] [main/INFO]: [CHAT] [LP] VB > mibby - chatcontrol.bypass.rules.packets - true
[03:29:47] [main/INFO]: [CHAT] [LP] VB > mibby - chatcontrol.bypass.rules.packets - true
[03:29:47] [main/INFO]: [CHAT] [LP] VB > mibby - chatcontrol.bypass.rules.packets - true
[03:29:47] [main/INFO]: [CHAT] [LP] VB > mibby - chatcontrol.bypass.rules.packets - true
[03:29:47] [main/INFO]: [CHAT] [LP] VB > mibby - chatcontrol.bypass.rules.packets - true
[03:29:47] [main/INFO]: [CHAT] [LP] VB > mibby - chatcontrol.bypass.rules.packets - true
[03:29:47] [main/INFO]: [CHAT] [LP] VB > mibby - chatcontrol.bypass.rules.packets - true
[03:29:47] [main/INFO]: [CHAT] [LP] VB > mibby - chatcontrol.bypass.rules.packets - true
[03:29:47] [main/INFO]: [CHAT] [LP] VB > mibby - chatcontrol.bypass.rules.packets - true
[03:29:47] [main/INFO]: [CHAT] [LP] VB > mibby - chatcontrol.bypass.rules.packets - true
[03:29:47] [main/INFO]: [CHAT] [LP] VB > mibby - chatcontrol.bypass.rules.packets - true
[03:29:47] [main/INFO]: [CHAT] [LP] VB > mibby - chatcontrol.bypass.rules.packets - true
[03:29:47] [main/INFO]: [CHAT] [LP] VB > mibby - chatcontrol.bypass.rules.packets - true
[03:29:47] [main/INFO]: [CHAT] [LP] VB > mibby - chatcontrol.bypass.rules.packets - true
```

One second worth of spam.
http://paste.ubuntu.com/25771566/

Using LuckPerms for server permissions and verbose debugging.
```/lp verbose on```

I'm guessing you are blanket listening on the readChatPosition packet and not doing a permission check for specific messages / rules only. So when a message comes through from a permission debug, it gets stuck in a constant loop.

This is bad because it spams permission checks constantly and breaks functionality behavior with LuckPerms since you can't legibly read permission checks or even disable the verbose with it spamming.

Print message for check -> ChatControlPro check permission -> Print message for check -> ...

Would it be possible to fix this?

**Comment by kangarko** [comment] 2017-10-19 19:27
Hello,

good notice! I have just stumbled upon something and have changed the logic under which plugin is reloaded - if you have used /chc rl - this may have been the cause.

Nevertheless, I am closing this in faith that this has been fixed, please test out the next release available tonight.

**Comment by mibby** [comment] 2017-10-20 10:33
Unfortunately testing as of ChatControlPro v7.6.0, permission checks are still spammed when turning lp verbose on.

**Comment by kangarko** [comment] 2017-11-05 20:32
@mibby, sorry for the delay.

I have made the necessary changes and from my testing the issues seemed to disappear. I am leaving this open for you to close depending on whether or not you will experience the issue.

**Comment by kangarko** [comment] 2017-11-07 19:04
Just to be sure, I done another series of testing and it appears to be fixed. I am closing this, but please let me know if anything raises ever again.

Cheers!

**Closed by kangarko** 2017-11-07 19:04 UTC
Labels: Issue: confirmed
