### ISSUE TITLE
1.16.1: 8.7.7 inability to run

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#1841] opened 2020-08-13 21:48 UTC
Chatcontrol encountered an aF:
https://pastebin.com/528d422g

**Comment by WolverStones** [comment] 2020-08-13 21:53
Yea same issue https://github.com/kangarko/ChatControl-Pro/issues/1840

**Comment by kangarko** [comment] 2020-08-14 06:35
Thanks, should be fixed. I did test the released however our lag catcher methods seems to behave this way since the chat is async. I only tested with one player (myself) hence could not reproduce this.

**Closed by kangarko** 2020-08-14 06:35 UTC
Labels: issue

**Comment by mrcoffee1026** [comment] 2020-08-14 15:47
Yeah it's that way with testing sometimes... need a live server with a few people on to really know things aren't working right.  I test things before too but generally with the same limitation... maybe someone can make a "fake player" plugin to test things with where it just spawns like 3 people who say random things every few moments for that very purpose... until then, this is the only way I know to really put a thing to the test either (just launch it on a live server).
