### ISSUE TITLE
It does not replace the message

### ISSUE THREAD

**Issue by TheMochonful** [kangarko/ChatControl-Pro#44] opened 2016-05-13 18:05 UTC
By putting the "handlers.xml" in the Swear, placing Rewrite_to file: "Viva MineSteel" does not replace the word or message.

**Comment by EvilOlaf** [comment] 2016-05-13 19:08
There is no handlers.xml. Did you mean `handlers.yml`?
You can define your rules within the files you can find in the `rules` directory.
Please paste the actual rule your defined which does not work for you.

**Comment by TheMochonful** [comment] 2016-05-14 21:40
This is the file **rules.txt**

# Blocks fuck

match \b(f+(\W|\d|_)*u+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*)

handle as swear

# Blocks puta

match \b(p+(\W|\d|_)*u+(\W|\d|_)*t+(\W|\d|_)*a+(\W|\d|_)*)
handle as swear


# Blocks follar

match \b(f+(\W|\d|_)*o+(\W|\d|_)*l+(\W|\d|_)*l+(\W|\d|_)*a+(\W|\d|_)*r+(\W|\d|_)*)
handle as swear


And this is the file **handlers.yml**

swear:
  Bypass_With_Permission: "chatcontrol.bypass.swear"
  Ignored_In_Commands:
    - // # WorldEdit
    - /auction
    - /register
    - /reg
    - /login
    - /l

  Player_Warn_Message: "&cPlease do not swear, otherwise an action will be taken!"
  Console_Message: "%player violated rule ID %ruleID, triggered %handler filter with: %message"
  
  Staff_Alert_Message: "&8[&7Swear/ID %ruleID&8] &7%player: &f%message"
  Staff_Alert_Permission: chatcontrol.notify.swear
  Block_Message: true

  Rewrite_To: Donare a MineSteel
  Write_To_File: logs/swears.txt

**Comment by kangarko** [comment] 2016-05-15 11:31
Cannot reproduce. Ensure you test from a player account without bypass permissions.
You can post me your settings.yml (upload to pastebin) so I ensure it is not caused from there.

**Comment by kangarko** [comment] 2016-05-24 16:51
Closing, Rewrite_To has recently been fixed.

**Closed by kangarko** 2016-05-24 16:51 UTC
Labels: cannot reproduce, issue
