### ISSUE TITLE
Book managing intervenes with Authme /login

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl-Pro#263] opened 2017-06-16 17:14 UTC
Getting this message on console when some players attempt to login:
`<player> was disallowed from running a command from book: /login <password>`
But why should book managing (which I'm not really interested in), be censoring words when logging in through chat?
```
  Block_Book_Commands: true
  Block_Book_Commands_Whitelist:
  - /login
  - /l
```
Does this have anything to do? Excuse my ignorance, I've never used this feature. I'd just like to stop it from intervening by default.
I set block commands to false, which is something I did in the past to evade this issue.

**Comment by kangarko** [comment] 2017-06-17 09:45
Hey,

so you're reporting that even if the /login command is specified in the whitelist, it is still being blocked? I just tested and I cannot reproduce

![img](https://i.imgur.com/TcsjPG5.png)

The way it works is that we check whether or not the player holds a book in their hands while running a command, and if they do, it is considered as being from the book (even when it does not have to be). This is due to limitations of the API and server (there's no way of checking whether it is coming from an actual book).

**Comment by MithrandirCraft** [comment] 2017-06-17 11:52
It doesn't always happen... I think it depends on the player's password for some reason.

**Comment by kangarko** [comment] 2017-07-01 18:18
Closing, this feature has been temporary disabled. When I find a proper way to block commands from books I'll read it.

**Closed by kangarko** 2017-07-01 18:18 UTC
Labels: Issue: cannot reproduce, Status: awaiting answer
