### ISSUE TITLE
[7.5.3] Double messages in all bungee chat (global chat, admin chat ecc)

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#361] opened 2017-09-16 08:33 UTC
In certain server (for example factions) when i receive admin chat messages, i see them as doubled..
I already updated the bungee plugin to latest release

**Comment by kangarko** [comment] 2017-09-17 16:55
Cannot reproduce from testing. Please describe how you use the plugin: channels/interactive chat? Is admin chat done via a channel or /chc ach command? Lastly, post your settings.yml for both servers.


![pic](https://i.imgur.com/CNAQNz8.jpg)

**Comment by xion87** [comment] 2017-09-18 08:16
all fixed, was caused because i have upgraded chatcontrol only on certain server on network, now that i have full upgraded all these issue gone

**Comment by xion87** [comment] 2017-09-18 20:53
![immagine](https://user-images.githubusercontent.com/3611852/30564069-1502cb00-9cc4-11e7-8bc2-9a40a5c167f5.png)

The issue is still happening in 7.5.3 randomly in servers....

**Comment by kangarko** [comment] 2017-09-19 17:52
@xion87 please test out on 7.5.4 :)

**Comment by xion87** [comment] 2017-09-19 21:28
Still happening in 7.5.4

**Comment by kangarko** [comment] 2017-09-20 17:21
Can you please test if the message is tripled or quadrupled if there are three or four people on the sender or receiver's server? We had such issue in the past. I am currently out of workspace with enough resources for that but if you could test it it would be golden.

**Comment by xion87** [comment] 2017-09-21 08:18
it seem base on number of people that have access to admin channel... but if he quit it keep to stay buged until restart

**Comment by kangarko** [comment] 2017-09-25 19:07
Thanks. I will get to it 3nd of October due to stay in the outlands.

**Comment by kangarko** [comment] 2017-10-11 20:46
@xion87 I apology for the delay. Please test against 7.5.14 that will be available tonight.

**Comment by kangarko** [comment] 2017-10-19 19:39
Closing in faith that this has been resolved by fixing the reload logic.

**Closed by kangarko** 2017-10-19 19:39 UTC
Labels: Issue: complaint, Status: awaiting answer
