### ISSUE TITLE
Latest releases take a LOT of times/stuck to authorize

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#591] opened 2018-02-05 12:55 UTC
Everytime that i try to upgrade to new release from 7.6.29 to new release, chatcontrol will get stucked at start. Please do something.
(i run the paperspigot server under bungeecord)
The log where i get stucked is:
https://hastebin.com/jajidikusa.md

**Comment by kangarko** [comment] 2018-02-09 09:55
Hello, I am sorry for the annoyance. I have communicated with the hosting company several times before but they failed to fix it. When I am finished with moving (in real life) I will change the hosting. 

Until then, how long is the waiting time at the start? It should not be more then 4 seconds.

**Comment by xion87** [comment] 2018-02-09 10:11
it get stucked forever until i crash the server ç_ç

**Comment by xion87** [comment] 2018-02-09 10:13
You cant' just find a alternative method and obfuscate the code? like the other plugins

**Comment by kangarko** [comment] 2018-02-09 10:19
Obfuscation doesn't help. I tried various methods and found this best; I am almost not receiving complaints these days.

Can you try running the plugin offline?

**Comment by xion87** [comment] 2018-02-09 10:36
you can just make a first time activation and then generate a unique key for that server so it don't need to verificate again everytime i start the server (or just cache it for X day)
How i run the plugin offline anyway?

**Comment by kangarko** [comment] 2018-02-09 11:01
Just make a local server on your Windows/Mac and disable internet access to see if it loads correctly. It should as there is an offline mode.

Good idea. I will keep it in mind.

**Comment by xion87** [comment] 2018-02-09 12:46
I tried to run from my pc, it just took 140ms for enable
I run it from my bungee server, it took 1168855 ms

**Comment by xion87** [comment] 2018-02-12 08:18
Tested on hub, it took 3 hours for enable it... LOL https://hastebin.com/boxocoduvo.md

**Comment by kangarko** [comment] 2018-02-12 09:03
Does it stop and freeze under "Connecting to MySQL database" message or another one?

**Comment by kangarko** [comment] 2018-02-14 13:23
@xion87 What is the last message from when ChatControl is enabled before the free-out please? There are multiple checks that may hang on, so to save us time I would like to know the last one.

**Comment by xion87** [comment] 2018-02-14 13:28
just look the timestamp
[05:00:47] [Server thread/INFO]: [0;36;22mBungeeCords enabled. [0;37;22mSee www.spigotmc.org/resources/13079[m
[09:10:32] [Server thread/INFO]:  [m
[09:10:32] [Server thread/INFO]: [0;32;22mWe're live! (took 14984714 ms)[m

**Comment by kangarko** [comment] 2018-02-14 14:22
Oh sorry totally missed those! I am on it.

**Comment by kangarko** [comment] 2018-02-14 14:26
The timestamp is at the place least expected. I've added two more startup messages to further get to know the root cause. A new release will be up tomorrow or the day after.

**Comment by kangarko** [comment] 2018-02-14 14:27
The timestamp is at the place least expected. Neither my machine would ever hang there, so I've added two more startup messages to further get to know the root cause. A new release will be up tomorrow or the day after. Please re-post the startup log.

You don't have to wait 3h just post it to the last message before it hangs on again.

**Comment by xion87** [comment] 2018-02-14 14:28
oke, i will run it from test serve

**Comment by kangarko** [comment] 2018-02-15 09:32
@xion87 any news? Sorry to push, I got today's evening & tomorrow to fix it, otherwise it'll be around 20th.

**Comment by xion87** [comment] 2018-02-15 13:20
I don't see any chatcontrol release

**Comment by kangarko** [comment] 2018-02-15 22:41
Nope, sorry I have the most done but there been issues with https://github.com/kangarko/ChatControl-Pro/issues/577 left unresolved, and I am not willing to push half broken release 23:41. Tomorrow :)

**Comment by kangarko** [comment] 2018-02-16 09:24
@xion87 just pushed it out

**Comment by xion87** [comment] 2018-02-16 10:29
Tried now, took 30 seconds around
https://pastebin.com/4Ae4BXn3

**Comment by kangarko** [comment] 2018-03-02 09:44
@xion87 I am terribly sorry I failed to read it until the paste expired, just paste it here directly in the tags.

In the meanwhile I got a reply from customer support from my current hosting saying they have been upgrading their servers and what not, I tested from a free wifi hotspot (super slow) and it took 1-2 seconds to load. Hope you encountered an improve as well.

**Comment by xion87** [comment] 2018-03-02 12:37
it took 29062 seconds https://hastebin.com/ucitijonus.md

**Comment by kangarko** [comment] 2018-03-05 20:01
Sorry for the delay. Can you please disable Silent_Startup and ensure you're on latest version so I can see the extra messages between that time? 29 seconds, that's 29.000 milliseconds, but still far beyond what's acceptable.

**Comment by kangarko** [comment] 2018-03-12 10:50
@xion87 if you happen to have some recent login with those extra messages, post it now 

Regardless, I am rewriting the system to the next major update.

**Comment by xion87** [comment] 2018-03-12 11:13
Oh sorry i missed the reply, there there is
https://hastebin.com/jesuyukama.md

**Comment by kangarko** [comment] 2018-03-12 12:06
What is the size of your data.db file just out of curiosity?

**Comment by xion87** [comment] 2018-03-12 12:11
6kb

**Comment by kangarko** [comment] 2018-03-12 15:08
Okay, in the next release, I moved that task out of starting and I added a watcher. If it takes over 30 seconds after your server starts, you will be notified (and please post that message). Thank you for your cooperation. Closing in faith it has been resolved.

**Closed by kangarko** 2018-03-12 15:08 UTC
Labels: Issue: complaint, Status: in progress
