### ISSUE TITLE
Issue with RedisBungee

### ISSUE THREAD

**Issue by Affixes** [kangarko/ChatControl-Pro#942] opened 2018-09-30 22:42 UTC
I have run out of ideas. Hours and hours of debugging have lead absolutely nowhere, so at this point I'm going to classify this as an actual bug with the affected plugin(s).

**The issue is as follows:**
We are trying to achieve cross-server messaging using the "Bungee" feature integrated with ChatControl, however it seems like the compatibility between RedisBungee, BungeeControlBridge and ChatControl is completely broken. The compatibility with default Bungeecord seems to work fine.

**The setup:**
- `Player 1` is connected to `survival1` on `bungee1`
- `Player 2` is connected to `skyblock` on `bungee1`
- `Player 3` is connected to `skyblock1` on `bungee2`
- When `Player 1` is trying to message `Player 2`, both on `bungee1`, it works fine
- When `Player 1` is trying to message `Player 3`, one on `bungee2`, they get a "Player not found"

I have tried absolutely everything that I can think of to try and mitigate the issue, including:
- Updating ChatControl Pro and BungeeControlBridge to their latest versions
- Completely resetting both plugins and using a clean installation
- Creating a dev network isolated from production with ONLY ChatControl, Redis and ControlBridge
- Messing with different server IDs
- Switching between using MySQL and not using MySQL (not sure if required?)
- Enabling the "debug" option for "redis" in ControlBridge which shows nothing (except below)
- Trying multiple different server setups (i.e. Bungee with only one gamemode / two gamemodes)

The "debug" option sometimes prints this in the console (but not all the time):
```
[18:39:21 INFO] [BungeeControlBridge]: ChatControl: Incoming message from server 'Unknown Server' of type 'PM_LOOKUP'
[18:39:25 INFO] [BungeeControlBridge]: ChatControl: Incoming message from server 'Unknown Server' of type 'PM_LOOKUP'
```

**Below are the startup logs from all 3 plugins.**

```
[18:22:52 INFO]: Loaded plugin BungeeControlBridge version 3.1 by kangarko
[18:22:52 INFO]: Hooked into: RedisBungee
[18:22:52 INFO]: Started listening on channel: plugin:chatcontrol
[18:22:52 INFO]: Enabled plugin BungeeControlBridge version 3.1 by kangarko
```

```
[18:38:51 INFO]: Loaded plugin RedisBungee version 0.3.10 by tuxed
[18:38:51 INFO] [RedisBungee]: Successfully connected to Redis.
[18:38:51 INFO]: Enabled plugin RedisBungee version 0.3.10 by tuxed
```
**SIDENOTE:** We are in fact using 0.4, the latest version, but I presume the plugin.yml isn't updated)

```
[18:28:48] [Server thread/INFO]: [ChatControl] Loading ChatControl v7.9.25
[18:28:50 INFO]: [ChatControl] Enabling ChatControl v7.9.25
[18:28:50 INFO]:   _____ _           _    _____            _             _  +
[18:28:50 INFO]:  / ____| |         | |  / ____|          | |           | |
[18:28:50 INFO]: | |    | |__   __ _| |_| |     ___  _ __ | |_ _ __ ___ | |
[18:28:50 INFO]: | |    | '_ \ / _` | __| |    / _ \| '_ \| __| '__/ _ \| |
[18:28:50 INFO]: | |____| | | | (_| | |_| |___| (_) | | | | |_| | | (_) | |
[18:28:50 INFO]:  \_____|_| |_|\__,_|\__|\_____\___/|_| |_|\__|_|  \___/|_|
[18:28:50 INFO]:
[18:28:51 INFO]:
[18:28:51 INFO]: Checking compatible plugins..
[18:28:51 INFO]: Found: Essentials, PlaceholderAPI, ProtocolLib, Vault, WorldEdit, WorldGuard
[18:28:51 INFO]:
[18:28:51 INFO]: Rules loads now..
[18:28:51 INFO]: 43 global, 15 chat, 4 command, 2 packet and 1 book rule(s) found
[18:28:51 INFO]:
[18:28:51 INFO]: Listening starts..
[18:28:51 INFO]: Rules & antispam listening at normal priority.
[18:28:51 INFO]: Fallback chat listener started at normal priority
[18:28:51 INFO]:
[18:28:51 INFO]: BungeeCords enabled. See www.spigotmc.org/resources/13079
[18:28:51 INFO]:
[18:28:51 INFO]: Chat now controls. (took 37 ms)
[18:28:51 INFO]: _____________________________________________________________
```

Please advise what else I can do in this situation as I am absolutely lost. I'd be happy to assist with any required debugging.

**Comment by jascotty2** [comment] 2018-10-02 17:38
I can reproduce the issue and have identified what needs to be fixed. Working on getting this fixed up, but looks like it will take some work to iron out.

Thanks for bringing this up! :)

**Comment by kangarko** [comment] 2018-10-02 20:10
A huge thanks to @jascotty2 for taking time for this and resolving the issue.

A new release of BungeeControlBridge is now available.

**Closed by kangarko** 2018-10-02 20:10 UTC
