### ISSUE TITLE
1.13.2: Unhandled exception number 2048

### ISSUE THREAD

**Issue by StarozytnySky** [kangarko/ChatControl-Pro#1855] opened 2020-08-15 23:06 UTC
1.13.2: Unhandled exception number 2048

When i installed latest version chatcontrol i have error in console:

https://pastebin.com/eR4XuniF

**Comment by AngellitoX** [comment] 2020-08-17 01:41
Hello, are there any steps to reproduce?
What's your settings?

What specific ChatControl version are you running?

By looking at your logs, the problem is coming from ProtocolLib, so you're probably running an incorrect version from it. Try to disable ProtocolLib features from ChatControl or test different versions from ProtocolLib to see which one works for you. 

Hope this works!

**Comment by StarozytnySky** [comment] 2020-08-17 15:33
I use protocollib version 4.5.1 and chatcontrol 8.7.9

**Comment by kangarko** [comment] 2020-08-20 15:55
Thanks, will be fixed.

**Closed by kangarko** 2020-08-20 15:55 UTC
Labels: issue
