### ISSUE TITLE
1.16.2: MySQL Issue

### ISSUE THREAD

**Issue by KasearMC** [kangarko/ChatControl-Pro#1920] opened 2020-09-04 13:30 UTC
Minecraft: 1.16.2
Paper: 182
CCP: 8.8.1

this may have been reported already but i haven't seen an open issue about it.
this happens every time a player logs out.

https://pastebin.com/RGcYfcFs

**Comment by AngellitoX** [comment] 2020-09-05 04:52
Hello there! Thank you for reaching us out.

We will take a look to this in the next couple of days.

Angel from MineAcademy.org

**Comment by kangarko** [comment] 2020-09-07 17:27
Sorry, I cannot reproduce, can you please share this with me in private by sending a PM to kangarko on SpigotMC?

- Your ChatControl (ChatControl_Data) table from your MySQL database exported as SQL.
- Your ChatControl/ entire plugin folder as ZIP.

Closing this and we will continue in private over PM to avoid leaking potentially sensitive data.

**Closed by kangarko** 2020-09-07 17:27 UTC
Labels: issue
