### ISSUE TITLE
/ignore doesn't work?

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#425] opened 2017-10-18 23:13 UTC
Seems that this doesn't function... I can add permissions to people to allow them to use it, but their using it can add users to their ignore list only.  Users can not be removed from this list by any means that I can see.  (essentials had an /unignore command.,.. i would assume something like that should also exist, but if it does, it is not documented).  Adding a player to that list... does not actually ignore that player?  They can still chat messages and the person will be able to see those messages just fine.  I have no idea of the scope (if it successfully ignore/mutes their private messages or /tp requests... I have no idea, just that their chat is not blocked... which is generally what /ignore would be hoping to accomplish).

**Comment by mibby** [comment] 2017-10-19 09:48
Can confirm that I'm also experiencing this issue. Trying to ignore players, they are still able to have their message seen with bungeecord cross-server global chat.

**Comment by kangarko** [comment] 2017-10-19 17:11
Hello,

I am sorry for that you have issues.

**1. Un-ignore**
Players can use /ignore command twice - to ignore the player, and, if they use it the second time, to un-ignore the ignored player.

![img](https://i.imgur.com/xtuOned.png)

**2. Malfunction**
From my testing I cannot reproduce this. Please provide me more data on how you use the plugin:
* Channels / Chat Formatter enabled?
* Does it work locally and breaks over bungee only, or breaks on both?

**Comment by kangarko** [comment] 2017-10-19 18:29
**Update:**

I had time to review this and I found out a lack of /ignore support to /chc g, /chc ach and channels on bungee mode. 

This will be added into the next version :)

**Comment by mrcoffee1026** [comment] 2017-10-19 18:40
I'm not running bungee?  When I use /ignore a second time it just says the player is ignored again, it doesn't un-ignore... all chat messages sent by ignored user in chat still display to the user that ignored them? Yeah, based on what you said... this shouldn't be an issue but it is.  Not sure what other info you're going to need on this, I may do some more experimenting later to see if I can find an error of some sort.

**Comment by kangarko** [comment] 2017-10-19 20:18
Hmm that's odd. Do you have Ignore.Enabled to true in settings.yml and are sure that no other plugin override this feature?

Btw, do you use MySQL?

**Comment by mrcoffee1026** [comment] 2017-10-19 21:42
ignore is enabled (according to this part of the config, yes?  I put it below).... as far as i can tell there may be TWO plugins possibly running interference here, but chc's ignore list is displayed (and it's permission node is mentioned if there isn't permission to use it), so it seems chc is taking it over completely.  Essentials has an /ignore, and I believe so does GriefPrevention.  Essentials simply drops the ability to use the command when it exists in another plugin... only way to get it back is to make an /eignore alias.  I know a bit less about the GriefPrevention one as far as priority goes... and technically the command is /ignoreplayer and /unignoreplayer, I don't think it has /ignore as an alias.

```
# ------------------------------------------------------------------------------------------------- 
# Ability to ignore chat and private messages from certain players.
# -------------------------------------------------------------------------------------------------
Ignore: 
  Enabled: true
  
  # Please do not remove the first alias, as this is the main command label.
  Aliases: [ignore, ign]
  
  # Hide chat messages from ignored players?
  Chat: true
  
  # Do not receive private messages from ignored people?
  Private_Messages: true
```

**Comment by kangarko** [comment] 2017-10-19 21:46
I see. I will just advise you to wait and test out the next release, as it recodes some parts of the ignore feature.

**Comment by mrcoffee1026** [comment] 2017-10-19 21:48
ah k, will do.  Thanks for everything :D

**Comment by mrcoffee1026** [comment] 2017-10-20 01:23
Tried with your latest (7.6.0), ignore is now removing/adding properly... although seems to have lost whatever records were previously there (like... one for us since this wasn't really working at all so I didn't put the perms to anyone), but is still not actually blocking the chat messages.

![ignore-fail](https://user-images.githubusercontent.com/3322491/31801078-94831f3a-b513-11e7-9689-0adc2b0cafdb.jpg)

(book == bookwormbumpkin), user was ignored prior to their chat, does not have ignore bypass permission)

**Comment by kangarko** [comment] 2017-10-20 10:18
Please upload me your ChatControl/ folder here (make sure to remove mysql information).

**Comment by mrcoffee1026** [comment] 2017-10-20 19:18
Stripped the login for the sql but I haven't really been able to use it.  The "autoreconnect" directive seems to be ignored so it often disconnects, and since it also ignores the useSSL=false directive, it always puts a very verbose and lengthy warning in my logs, so I just disabled the database altogether.

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/1403039/ChatControl.zip)

**Comment by kangarko** [comment] 2017-11-09 20:34
Hello,

I am sorry that I forgot to reply. I don't want to be rude, but I assume you no longer experience the issue, so I kindly close this. 

If anything at all shows up or continues to happening, you're most welcome to open a new issue!

Cheers!

**Comment by mrcoffee1026** [comment] 2017-11-09 21:42
This is still happening.  Cannot /ignore users, seems to have no effect.

**Comment by kangarko** [comment] 2017-11-11 17:20
Duplicate of https://github.com/kangarko/ChatControl-Pro/issues/482, please continue there.

**Closed by kangarko** 2017-11-11 17:20 UTC
Labels: Issue: complaint, Status: queued
