### ISSUE TITLE
1.16.2: DiscordSRV Integration not Working 

### ISSUE THREAD

**Issue by coco0325** [kangarko/ChatControl-Pro#1897] opened 2020-08-29 02:46 UTC
After upgrading ChatControl Pro form 8.6.6 to 8.8.0 beta, I found that I can't see any Discord messages in Minecraft and vice versa.

**Comment by AngellitoX** [comment] 2020-09-01 01:51
Hello there, that's odd. I can confirm DiscordSRV and ChatControl are properly working in my own network.

Can you please make sure you are also running the latest version from DiscordSRV? If so, there's probably something going on your settings.

I'm marking this as solved. Consider commenting if you still present issues.
Angel from MineAcademy.org

**Comment by coco0325** [comment] 2020-09-01 09:43
DiscordSRV version is also the latest.
I didn't change my setting during the upgrade, so i don't think that's the problem.

**Comment by AngellitoX** [comment] 2020-09-01 17:27
Hmmm, intereseting.

Have you checked your console in order to see any startup errors? Most of the time that could tell us what's happening, sounds like DiscordSRV isn't loading properly.

**Comment by coco0325** [comment] 2020-09-02 12:18
No error shown.
Here's ChatControl's console info, it says it hooked into DiscordSRV

```
[20:13:56 INFO]: Connecting to MySQL database...
[20:13:56 INFO]:
[20:13:56 INFO]: Registering commands...
[20:13:56 INFO]:
[20:13:56 INFO]: Loading variables...
[20:13:56 INFO]:
[20:13:56 INFO]: Loaded 43 global, 15 chat, 4 command, 2 packet and 1 book rules
[20:13:56 INFO]: Hooked into: DiscordSRV
```

**Comment by AngellitoX** [comment] 2020-09-02 16:36
Hello! And what about DiscordSRV logs? does it say anything?

**Comment by coco0325** [comment] 2020-09-03 12:17
`[20:09:53 INFO]: [DiscordSRV] API listener org.mineacademy.chatcontrol.lib.fo.model.k$a `

**Comment by kangarko** [comment] 2020-09-03 17:54
ZIP me your ChatControl config (expect MySQL if you have it on) as well as "Channels" part of DiscordSRV config (not the whole config there, as it has sensitive keys) and I'll have a look.

**Comment by AngellitoX** [comment] 2020-09-03 18:04
Hello, just to make sure, last night I updated my production server to ChatControl 8.8.1-BETA and the very latest build of DiscordSRV 1.9.1 and everything is working as expected, so there's definitely a config issue on your end bro.

So yes, please ZIP us your config so we can take a look to it and find what happened.

**Comment by james-d-elliott** [comment] 2020-09-04 00:01
Are you using CCP channels? I had the same issue with DiscordSRV and channels enabled. Reverting to 8.7.

**Comment by coco0325** [comment] 2020-09-04 13:43
> ZIP me your ChatControl config (expect MySQL if you have it on) as well as "Channels" part of DiscordSRV config (not the whole config there, as it has sensitive keys) and I'll have a look.

[Configs.zip](https://github.com/kangarko/ChatControl-Pro/files/5175125/Configs.zip)

**Comment by NerdyBirder** [comment] 2020-09-04 23:55
I am having an issue with DiscordSRV as well. I have scoured the wiki pages for both DiscordSRV and ChatControl and have made sure that I have everything setup correctly.

Bungee-chat is sending chat to our discord channel and vice-versa, so I don't have an issue with that part of discord integration.
My issue is with *channels* sending and receiving messages to/from discord. I have set up a channel for our staff chat to receive chat from minecraft into a staff chat channel on our discord. It was working before the update to 8.0.0 BETA but is not working after the update. I have double checked to be sure the name is exactly the same in the settings.yml as it is in our discord server but there is still no communication.

**Comment by coco0325** [comment] 2020-09-05 02:27
@kangarko 

> > 給我郵編您的ChatControl配置（如果有，請使用MySQL）以及DiscordSRV配置的“通道”部分（而不是整個配置，因為它具有敏感的密鑰），我來看看。
> 
> [Configs.zip](https://github.com/kangarko/ChatControl-Pro/files/5175125/Configs.zip)

**Comment by coco0325** [comment] 2020-09-07 12:00
@kangarko

**Comment by NerdyBirder** [comment] 2020-09-07 13:41
A new issue that I realized was a problem today is that we can not see messages from our discord server in the game chat until an admin does /chc reload. After chatcontrol is reloaded we can see the messages from discord to minecraft but nothing goes through until that command is done. Even a server restart does not fix it, the command has to be run for it to work.

**Comment by hammad-alhassan** [comment] 2020-09-08 14:30
> A new issue that I realized was a problem today is that we can not see messages from our discord server in the game chat until an admin does /chc reload. After chatcontrol is reloaded we can see the messages from discord to minecraft but nothing goes through until that command is done. Even a server restart does not fix it, the command has to be run for it to work.

i confirm this too

**Comment by hammad-alhassan** [comment] 2020-09-08 15:54
last working version with no issues with discordsvr using 1.16.2 is ChatControl_8.7.12

**Comment by kangarko** [comment] 2020-09-09 14:01
Thanks for reporting. 

Oddly enough, after setting up a channel by the name of admin on both Discord and ChatControl, things appear to be working: https://i.imgur.com/HRklaF2.png

Everyone please update to the next version that will be available later today, then set your Debug key in settings.yml to ["discord"] and post me the console log when the problem happens.

**Comment by kangarko** [comment] 2020-09-09 14:01
I made those debug messages self-explanatory so you should be able to see why things are (not) happening.

**Comment by hammad-alhassan** [comment] 2020-09-09 15:56
with the latest update 8.8.4 ,now messages from game to discord are not showing but from discord to game are showing

**Comment by coco0325** [comment] 2020-09-10 13:57
https://pastebin.com/PexYquk2

**Comment by coco0325** [comment] 2020-09-12 01:44
@kangarko 
Error log:
https://pastebin.com/HPsP2exS
Debug message:
`[discord] > Message from channel '公共聊天區' not sent to Discord because the Discord_Format option in channel is missing.`
I did set a Discord_Format in the channels.yml

**Comment by kangarko** [comment] 2020-09-13 06:15
@coco0325 please update your BungeeControl and ChatControl then try again

**Comment by coco0325** [comment] 2020-09-14 13:05
[21:05:13 INFO]: [discord] > Message from channel '公共聊天區' not sent to Discord because the Discord_Format option in channel is missing.
@kangarko Still.

**Comment by hammad-alhassan** [comment] 2020-09-14 21:24
[00:21:47 INFO]: [discord] > Message from channel 'admin-chat-minecraft' not sent to Discord because the Discord_Format option in channel is missing.

**Comment by hammad-alhassan** [comment] 2020-09-14 21:35
> last working version with no issues with discordsrv using 1.16.2 is ChatControl_8.7.12

**Comment by coco0325** [comment] 2020-09-15 11:07
@kangarko

**Comment by kangarko** [comment] 2020-09-15 15:17
@coco0325 tested @hammad-alhassan sorry guys but I cannot reproduce, works fine for me:  https://i.imgur.com/RGW5BEO.png

Please post me your channels.yml uploaded to pastebin.com

**Closed by kangarko** 2020-09-15 15:17 UTC
Labels: issue

**Comment by coco0325** [comment] 2020-09-16 11:59
It worked after add Discord_Format: in channels section.

**Comment by kangarko** [comment] 2020-09-16 12:58
Yeah just add that option as instructed by the console log...
