### ISSUE TITLE
Reload command kicks players from channels

### ISSUE THREAD

**Issue by Kbryst** [kangarko/ChatControl-Pro#1916] opened 2020-09-03 21:07 UTC
I'm mostly just looking for a way to reload the messages.yml for broadcasts. 

This plugin reloads like a trainwreck and often times breaks on reload. Players suddenly lose their channels and are honestly too stupid to handle how complicated parts of this plugin is. (Yes, joining a channel is too hard apparently). It would just be nice to update automatic broadcasts and reload them without things breaking. As a server owner, I'm sure many know my pain when you log in and realize "oups, forgot an old broadcast".

**Comment by AngellitoX** [comment] 2020-09-05 04:49
Hello there, thank you for the suggestion. Probably this can be added for the future ChatControl 9.1.0 releases :) 

Angel from MineAcademy.org

**Comment by kangarko** [comment] 2020-09-07 17:12
How do the players obtain their channels that they lose? Is it from MySQL database, or do they have autojoin permissions? Can you give me an example on how they lose channels please? I will fix that.

**Comment by Kbryst** [comment] 2020-09-07 22:36
Oh honestly I haven't gone into too much testing on it or really paid too
much attention to it.

From what I see their channels are removed and they have to rejoin with /ch
join or whatever the current correct command is.

They have autojoin permissions.

This has been an issue for quite some time for us, I just assumed that's
how the reload is supposed to work.

**Comment by kangarko** [comment] 2020-09-09 14:10
No, reload should retain your channels. I could not reproduce the problem: https://i.imgur.com/QwBWMXJ.png

Please ZIP me your whole ChatControl/ folder as ZIP (except MySQL database info) so I will have a look.

Also let me know what chatcontrol-related permissions do players have.

**Comment by Kbryst** [comment] 2020-09-11 23:26
I am so sorry Maj, covid emergency I need at least a week before I can provide this information for you.

**Comment by kangarko** [comment] 2020-09-15 15:28
No worries, just tested both /reload confirm and /chc reload without issue. Closing in good faith. If anything, just comment below.

**Closed by kangarko** 2020-09-15 15:28 UTC
Labels: issue
