### ISSUE TITLE
Broadcaster broken?

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#75] opened 2016-08-04 12:14 UTC
This is no longer working? http://prntscr.com/c1ijb7

**Comment by Sikatsu** [comment] 2016-08-04 12:20
Seems mode 2 is broken.

**Comment by locke-d** [comment] 2016-08-05 00:41
see issue 72, this has been reported.

**Comment by kangarko** [comment] 2016-08-05 08:09
Duplicate of #72 

Please upload me your messages.yml file so I can directly test

**Closed by kangarko** 2016-08-05 08:09 UTC
