### ISSUE TITLE
1.16.1: ChatControl 8.7.7 does not work 

### ISSUE THREAD

**Issue by WolverStones** [kangarko/ChatControl-Pro#1840] opened 2020-08-13 21:39 UTC
chatcontrol does not work when I type something into chat I get an error in the console.

`[23:34:27 INFO]: ChatControl 8.7.7 encountered an aF! Please check your error.log and report this issue with the information in that file.
[23:34:27 ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v8.7.7
org.mineacademy.chatcontrol.final.nul. .aF: Report / Key 'creating component [Chat]' is already in the map --> '15997980517428272'
at org.mineacademy.chatcontrol.final.nul. .W.a(SourceFile:77) ~[?:?]
at org.mineacademy.chatcontrol.lib.fo.collection.d.a(SourceFile:86) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .ax.a(SourceFile:43) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .dj.a(SourceFile:46) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .dj.a(SourceFile:42) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .cZ.a(SourceFile:135) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .cZ.a(SourceFile:93) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .cZ.a(SourceFile:38) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .aC.execute(SourceFile:77) ~[?:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.1.jar:git-Paper-135]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-135]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-135]
at net.minecraft.server.v1_16_R1.PlayerConnection.chat(PlayerConnection.java:1823) ~[patched_1.16.1.jar:git-Paper-135]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1738) ~[patched_1.16.1.jar:git-Paper-135]
at net.minecraft.server.v1_16_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.16.1.jar:git-Paper-135]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_241]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_241]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
[23:34:27 INFO]: <Machy> 4`

error.log:
https://pastebin.com/WzDyM68k

**Comment by WolverStones** [comment] 2020-08-13 21:42
I will add that I use Waterfall Build 370 and BungeeControl-2.3.1.jar

**Comment by kangarko** [comment] 2020-08-14 06:34
Thanks, should be fixed. I did test the released however our lag catcher methods seems to behave this way since the chat is async. I only tested with one player (myself) hence could not reproduce this.

**Closed by kangarko** 2020-08-14 06:34 UTC
Labels: issue
