### ISSUE TITLE
Can't seem to stop chatcontrol from filtering out console info

### ISSUE THREAD

**Issue by Kadell** [kangarko/ChatControl-Pro#25] opened 2016-04-07 03:40 UTC
I can no longer call functions from the server console, and see their output. Command runs, but the out put no longer shows in the console.
things like /pex commands or /gc none of the normal output shows anymore,

my config http://pastebin.com/PPDWK8bU

**Comment by kangarko** [comment] 2016-04-10 09:22
ChatControl does not do that by default. I see you have Console Filter disabled, so I don't believe this is caused by this plugin.

**Comment by kangarko** [comment] 2016-05-08 08:52
Closing, as it is most likely not caused by ChatControl.

**Closed by kangarko** 2016-05-08 08:52 UTC
Labels: wontfix
