### ISSUE TITLE
Getting NullPointerException error when Enabling Chat Control Pro

### ISSUE THREAD

**Issue by iavengetheweak** [kangarko/ChatControl-Pro#1796] opened 2020-08-04 22:01 UTC
Minecraft Version 1.16.1
Paper 1.16.1 #131
Chat Control Pro Version: 8.7.1

Issue: Server failed to enable Chat Control Pro.  I would like the plugin to successfully be enabled on the server

PasteBin of Console Error Log: https://pastebin.com/vbTMvTst

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/5024887/ChatControl.zip)

I am not sure of any other information to give since I could not actually test the plugin on the server.

**Comment by AngellitoX** [comment] 2020-08-05 05:53
Hello @iavengetheweak,

I just tested a clean server and a fresh ChatControl folder and I couldn't replicate your issue as ChatControl started perfectly on my end.

My assumptions is that either you have a corrupted variables file, or your server doesn't have the right permissions to add the variables folder.

Could you please make sure of any of them?

Angel from MineAcademy.org

**Comment by james-d-elliott** [comment] 2020-08-05 10:06
I'm getting this same error from a completely blank folder:

```
svra              | [10:01:44 INFO]: [ChatControl] Enabling ChatControl v8.7.1
svra              | [10:01:45 INFO]:   _____ _           _    _____            _             _  +
svra              | [10:01:45 INFO]:  / ____| |         | |  / ____|          | |           | |
svra              | [10:01:45 INFO]: | |    | |__   __ _| |_| |     ___  _ __ | |_ _ __ ___ | |
svra              | [10:01:45 INFO]: | |    | '_ \ / _` | __| |    / _ \| '_ \| __| '__/ _ \| |
svra              | [10:01:45 INFO]: | |____| | | | (_| | |_| |___| (_) | | | | |_| | | (_) | |
svra              | [10:01:45 INFO]:  \_____|_| |_|\__,_|\__|\_____\___/|_| |_|\__|_|  \___/|_|
svra              | [10:01:45 INFO]:
svra              | [10:01:45 INFO]: !-----------------------------------------------------!
svra              | [10:01:45 INFO]: Failed to copy /variables to variables
svra              | [10:01:45 INFO]: !-----------------------------------------------------!
svra              | [10:01:45 INFO]: ChatControl 8.7.1 encountered a NullPointerException! Please check your error.log and report this issue with the information in that file.
svra              | [10:01:46 INFO]: java.lang.NullPointerException
svra              | [10:01:46 INFO]: at org.mineacademy.chatcontrol.final.nul. .F.d(SourceFile:518)
svra              | [10:01:46 INFO]: at org.mineacademy.chatcontrol.lib.fo.model.h.a(SourceFile:94)
svra              | [10:01:46 INFO]: at org.mineacademy.chatcontrol.lib.fo.model.X.i(SourceFile:286)
svra              | [10:01:46 INFO]: at org.mineacademy.chatcontrol.final.nul. .dI.p(SourceFile:71)
svra              | [10:01:46 INFO]: at org.mineacademy.chatcontrol.final.nul. .dI.g(SourceFile:51)
svra              | [10:01:46 INFO]: at org.mineacademy.chatcontrol.final.nul. .cN$1.<init>(SourceFile:53)
svra              | [10:01:46 INFO]: at org.mineacademy.chatcontrol.final.nul. .cN.<init>(SourceFile:50)
svra              | [10:01:46 INFO]: at org.mineacademy.chatcontrol.final.nul. .cK.<init>(SourceFile:23)
svra              | [10:01:46 INFO]: at org.mineacademy.chatcontrol.final.nul. .dI.<init>(SourceFile:40)
svra              | [10:01:46 INFO]: at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
svra              | [10:01:46 INFO]: at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
svra              | [10:01:46 INFO]: at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
svra              | [10:01:46 INFO]: at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
svra              | [10:01:46 INFO]: at java.base/java.lang.Class.newInstance(Unknown Source)
svra              | [10:01:46 INFO]: at org.mineacademy.chatcontrol.final.nul. .cN.a(SourceFile:80)
svra              | [10:01:46 INFO]: at org.mineacademy.chatcontrol.final.nul. .bv.onEnable(SourceFile:251)
svra              | [10:01:46 INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
svra              | [10:01:46 INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
svra              | [10:01:46 INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
svra              | [10:01:46 INFO]: at java.base/java.lang.Thread.run(Unknown Source)
svra              | [10:01:46 INFO]:   _   _                       _
svra              | [10:01:46 INFO]:   | | | | ___   ___  _ __  ___| |
svra              | [10:01:46 INFO]:   | |_| |/ _ \ / _ \| '_ \/ __| |
svra              | [10:01:46 INFO]:   |  _  | (_) | (_) | |_) \__ \_|
svra              | [10:01:46 INFO]:   |_| |_|\___/ \___/| .__/|___(_)
svra              | [10:01:46 INFO]:                     |_|
svra              | [10:01:46 INFO]: !-----------------------------------------------------!
svra              | [10:01:46 INFO]: Error loading ChatControl v8.7.1, plugin is disabled!
svra              | [10:01:46 INFO]: Running on 1.16.1-R0.1-SNAPSHOT (v1_16_R1) & Java 11.0.8
svra              | [10:01:46 INFO]: !-----------------------------------------------------!
svra              | [10:01:46 INFO]: Error: Unable to get the error message, search above.
svra              | [10:01:46 INFO]: !-----------------------------------------------------!
svra              | [10:01:46 INFO]: [ChatControl] Disabling ChatControl v8.7.1
svra              | [10:01:46 INFO]: Plugin might not shut down property. Got NullPointerException: null
```

**Comment by james-d-elliott** [comment] 2020-08-05 10:23
Duplicate of #1794

**Comment by kangarko** [comment] 2020-08-05 19:13
Confirmed, thank you. Let's continue here: https://github.com/kangarko/ChatControl-Pro/issues/1794

**Closed by kangarko** 2020-08-05 19:13 UTC
Labels: question
