### ISSUE TITLE
Bug with tagging players without capitals

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#186] opened 2017-03-30 14:58 UTC
I can't tag someone on my server called jprz, this playername doesn't contain any capitals. Name is typed correctly.

Screenshot: http://prntscr.com/eqd8ue

**Comment by kangarko** [comment] 2017-04-01 17:58
Cannot reproduce:
(img)[https://i.imgur.com/iJtcy3P.jpg]

Can you tag other players/is he on the same server? Tagging is not supported on bungee.

**Comment by Sikatsu** [comment] 2017-04-01 18:20
Well, he was called jprz and could not be tagged with color. Using normal
spigot.

Op za 1 apr. 2017 19:58 schreef kangarko <notifications@github.com>:

**Comment by kangarko** [comment] 2017-04-01 18:21
Okay I see.

Was he connected on the same server as you?
Can you tag other players?

**Comment by Sikatsu** [comment] 2017-04-01 18:27
Same server, there is no other server. I can tag most players correctly,
but @sikatsu doesn't work when my name is Sikatsu (capitalized) however he
was called jprz without capital and that didn't work either.

Op za 1 apr. 2017 20:21 schreef kangarko <notifications@github.com>:

**Comment by kangarko** [comment] 2017-04-01 18:42
That's really odd, I thought I fixed it some time ago. Anyways, a new release is coming within an hour, please retest it there.

**Comment by kangarko** [comment] 2017-04-06 07:21
Hey @Sikatsu, can you reproduce it on the latest release?

**Comment by Sikatsu** [comment] 2017-04-06 10:23
I have not been able to test it yet, didn't see a player without capitals
yet. Will let you know soon!

Op do 6 apr. 2017 om 09:21 schreef kangarko <notifications@github.com>:

**Comment by Sikatsu** [comment] 2017-04-06 10:24
Perhaps it's an idea to make @rotonde work even while it's name is @RoTonde?

Op do 6 apr. 2017 om 12:23 schreef Shane Kloosterman <suomis1997@gmail.com>:

**Comment by kangarko** [comment] 2017-04-06 13:15
It is coded like that. ChatControl will correct capitalization to the nickname automatically.

**Comment by Sikatsu** [comment] 2017-04-08 13:10
Alright, tagging players without capitals seems to work now.

However, someone called ALIKOALI, and tagging him as alikoali, doesn't seem to auto-correct? (http://prntscr.com/ety4fe)
The system looks very sensitive currently, tagging players is a nice idea so hope it can be improved in the future, eventually with essentials support on the longterm.

**Comment by kangarko** [comment] 2017-04-08 16:15
Hey, it may be the anticaps, try setting Anti_Caps.Ignore_Usernames to true.

What do you mean by Essentials support?

**Comment by Sikatsu** [comment] 2017-04-08 17:12
Nicknames from essentials.

Why would it be related to caps though? As the cap version is the one working, without caps it doesn't auto-correct however.

**Comment by kangarko** [comment] 2017-04-08 18:56
The anticaps may make the message lowercase. The nicknames are not currently planned, but are on the todo list.

**Comment by Sikatsu** [comment] 2017-04-08 21:20
I know what you mean, but they can do ALIKOALI perfectly fine with it getting tagged, but when they do it without caps it won't work. That's something different, no?

Nicknames would be nice, as forgetting an underscore (_) will already fail the tag currently :)

Will test!

**Comment by kangarko** [comment] 2017-04-09 07:45
I was able to tag ALIKOALI by typing "@alikoali", can you reproduce? :)

**Comment by Sikatsu** [comment] 2017-04-09 11:31
How can someone tag who is offline? :P 

It seems to work now !

**Comment by kangarko** [comment] 2017-04-09 13:13
Oh did not though of this one haha, because I usually run it on an offline-mode test server using some hacked client to just change the nickname (or Magic Launcher).

**Comment by kangarko** [comment] 2017-04-09 13:13
Closing. Feel free to comment below or open a new issue if any unusual behaviour occurs again.

**Closed by kangarko** 2017-04-09 13:13 UTC
Labels: cannot reproduce
