### ISSUE TITLE
Regex error domain filtrer

### ISSUE THREAD

**Issue by dartasen** [kangarko/ChatControl-Pro#146] opened 2017-01-16 02:09 UTC
I have this error many time when players send links : 
 Matching timed out (bad regex?) (plugin ver. 7.0.32)! 
 String checked: https://www.teamspeak.com/downloads# (example but also with youtube links)
 Regex: (https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-\?]*)*\/?$

My rules' file configuration : 
# IP filter. 
# (Notice the operator strip which removes specified characters BEFORE the message is checked.)
match \b[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}\b
before replace dot|\[|\]|\{|\}|\(|\) with .
before strip [\(\[\]\)]
handle as pub

# Domain/URL filter.
# You can add new domains to be blocked by inserting '|your_domain' after '|me' (e.g. '|me|io' for also blocking '.io' domains)
#match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(com|org|net|cz|co|uk|sk|xxx|eu|io|fr|be)\b
#ignore string minecraft.net|gamepedia.com|join.me|youtube.com|youtu.be|imgur.com|noelshack.com|prntscr.com|prnt.sc|strawpoll.me|strawpoll.de
#before replace dot|\[|\]|\{|\}|\(|\) with .
#before strip [\(\[\]\)]
#handle as pub

**Comment by kangarko** [comment] 2017-01-19 18:30
Please post your entire rules.txt to pastebin, here it looks like you have disabled domain filter which makes such error unable to appear.

**Comment by dartasen** [comment] 2017-01-29 18:27
Sorry for the wait
rules.yml : http://pastebin.com/hiQc5hkn
new errors' example : http://pastebin.com/kWyWwY7e
(also youtube links but for the players' anonymity, I removed them)

**Comment by kangarko** [comment] 2017-01-30 16:36
Confirmed. I am working on this and the fix will be available in the next version.

**Comment by kangarko** [comment] 2017-02-11 19:03
Resolved in the latest update.

**Closed by kangarko** 2017-02-11 19:03 UTC
Labels: bug
