### ISSUE TITLE
To-do / Server crash due to book check

### ISSUE THREAD

**Issue by Kira07** [kangarko/ChatControl-Pro#114] opened 2016-10-22 17:40 UTC
Hello,
It is the second time this week that my server crashed because of chatcontrol, here is the crash stacktrace:
http://pastebin.com/195CiXSG
And here is the previous crash:
http://pastebin.com/uRZHdf7T

Seems related to book check.

**Comment by kangarko** [comment] 2016-10-23 08:16
Which ChatControl version was used? Have you any special rules in books.txt ? If so, please post the file.

**Comment by Kira07** [comment] 2016-10-23 14:09
I used version v7.0.26

And I only have the default rule in book.txt ->
match \bHerobrine\b
then deny

**Comment by kangarko** [comment] 2016-10-26 17:10
This is odd. How much RAM do you dispose of in your server? Please also ensure the **Regex_Timeout_Milis** key in settings.yml has a value of 100 or less.

**Comment by Kira07** [comment] 2016-10-26 19:54
I have 30 gigs of RAM in my xmx flag and my Regex_Timeout_Milis key is set to 100 (default)

**Comment by kangarko** [comment] 2016-10-29 10:02
Can you please run the /timings command for at least 20 minutes to measure server performance, making sure there is no anything else slowing it down? I have never had reported any crash resulting from rules, but I believe it can happen if the server is already under load from other sources. I can run performance checks on a local server, but it's completely different as on live server with player base.

**Comment by SucceededKiller** [comment] 2016-11-07 16:05
Hey,

I have a similar issue regarding the regex causing a crash, but this is with chat rather than books and is triggered when it checks URL's sometimes. I'll make a separate issue if you wish, but they seem somewhat related.

http://pastebin.com/eSrFcdrH
or
http://pastebin.com/hp1ihFda

Player counts vary quite a bit throughout the course of the day, but I'll try and get a timings report when the counts are around the same as those crashes. TPS was listed as ~18 during one crash though.

**Comment by kangarko** [comment] 2016-11-09 18:07
I see. I shall do an extensive testing asap. The plugin has an inner mechanism to prevent crashes from regex, but I haven't really tested it since the first 7th generation's release.

**Comment by Kira07** [comment] 2016-11-09 21:25
Thanks, hope that you'll manage to fix it

**Comment by kangarko** [comment] 2016-12-04 13:30
Oups! I have missed this issue, I am sorry. 

After some testing the issue seems to lie in the internal domain check, which is responsible for ignoring valid domains in the caps filter. I think I have fixed it, if all goes well, a new version should be released tonight.

**Comment by kangarko** [comment] 2016-12-04 14:19
Please test against the latest version. I am closing this for now as I believe the issue is fixed, but in case you experience similar problems again, please create a new ticket.

**Closed by kangarko** 2016-12-04 14:19 UTC
Labels: bug, [! TO - DO !]
