### ISSUE TITLE
1.16.1: Internal Server Error; Seeing if it's this

### ISSUE THREAD

**Issue by zaccieslak** [kangarko/ChatControl-Pro#1784] opened 2020-08-03 01:39 UTC
1) Minecraft Version: 1.16.1

Hello! I don't know which plugin could be causing this error:

Internal Exception: io.netty.handler.codec.DecoderException: The received string length is longer than maximum allowed

- I get this error when I try to input a command into a command block that exceeds 2048 characters. I know that it's a plugin that has a rule set to kick players who input more than 2048 characters, and seeing as how this is one of the only chat-using plugins I am running, I wanted to see if it was the issue. 

I'm trying to paste a give command for a book that I wrote. 

I wish that it would tell me from where the rule is coming from, but it's not, so I have to hit up multiple different plugin owners. Please let me know if your plugin has a rule set to only allow 2048 characters for string length. Thank you!

![image](https://user-images.githubusercontent.com/51010650/89138147-9a18e980-d508-11ea-8235-6bec4d26c9a1.png)

**Comment by JavaFactoryDev** [comment] 2020-08-03 08:25
Hi,

this is not a ChatControl exception. As you can see it is an internal server exception. It might be caused by protocollib + viaversion.

Regards,
Leonhard

**Comment by kangarko** [comment] 2020-08-04 11:46
It can be caused by ChatControl, too. Please can you test the following:

1. Disable console log.
2. Disable packet rules.

Try to see if removing either of these features causes these problems. Unfortunately, if you use ViaVersion and packet rules for ChatControl, it gets problematic so you may not be able to use that feature in our plugin together with ViaVersion.

Thanks
Matej

**Comment by kangarko** [comment] 2020-08-06 05:52
Closing in good faith this did get resolved, if not comment below.

**Closed by kangarko** 2020-08-06 05:52 UTC
Labels: issue
