### ISSUE TITLE
Max Time For Spam Similarity Checks

### ISSUE THREAD

**Issue by nitewing76** [kangarko/ChatControl-Pro#2010] opened 2020-10-04 04:59 UTC
I'm in the latter stages of alpha dev for a small network, so in this pre-sales suggestion I'm primarily drawing on my experience as a former Admin on Saico and as an older player on other large networks. I currently have DeluxeChat, but it looks like the same rank chat formatting options are buried within ChC Pro. I had planned to mainly use ChC (free) for the rules+handlers, but I'd like to use it to cut down on spam; however, the spam control works too well. And tbh I need to justify the extra $24, when most of the additional features of ChC Pro I already have with DeluxeChat (though in speaking with multiple ChC Pro users, I've heard that when sending a /msg over Bungee, ChC Pro doesn't add the server name as it should...checking old servers I played in the past, they now list the server on all /msgs not just the cross-server ones, which possibly adds validity to the claims of others). I'm not opposed to & getting ChC Pro and ditching DChat, but I have to satisfy the _fiscally responsible_ part of my brain as well. Anyways...

There are legit reasons why a player might need to repeat the same msg every 3-4 minutes. Maybe they have a question while they are building and no one is paying attention to them (especially if they are non-donators), so they need to ask multiple times without adding fluff msgs (e.g. _asking to ask_, random thoughts that have nothing to do with the topic, etc) to satisfy the similarity checks.  Or maybe they asked a busy staff member a question, but after a few minutes of no response they decided to forward their question to another staff member...doing so requires more useless fluff msgs to satisfy the similarity checks. 

To solve this problem, my suggestion/request is to add a time limit for the similarity check. With independent limits for public/global chat and private msgs. I have never used channels, so I hope someone else will share their wisdom on whether these should have a separate time or combined with public/global chat (or if everything should be separate). I did see a mention of _Whitelist_Time_ in the default settings.yml page, but no other mentions of it as an actual setting.

Thank you for your time and attention in this matter!

**Comment by broken1arrow** [comment] 2020-10-04 07:02
It is not a perfect plugin, I have a couple of problems.

Just wondering does DeluxeChat have discordSRV suport and you can add multiple channels?

**Comment by nitewing76** [comment] 2020-10-04 20:12
Any complex system will rarely, if ever, achieve perfection. That's not an excuse for any lack of determination by any programer for any program/platform...just saying it's unreasonable for anyone to expect anything to be _perfect_. I'm not saying you are, I'm only sharing my philosophy on the matter. :)

Feature comparisons could serve as red herring (a distraction) and could be seen as promoting the use of a competitor's plugin, even if you're trying to convince me to buy ChC Pro. So I'll just say that with a little bit of searching, the answers are out there and can be found in under 2 minutes (just not in the same place). I have no plans to use channels atm. And for as long as MineChat is around, I don't intend to use DiscordSRV, unless I can't figure out Slack integration with Admin/Staff Chat as we had on Saico (they don't use ChC). But that's a separate topic, since it'd likely be a separate custom plugin or a BungeeControl feature request.

**Comment by broken1arrow** [comment] 2020-10-05 04:15
> Any complex system will rarely, if ever, achieve perfection. That's not an excuse for any lack of determination by any programer for any program/platform...just saying it's unreasonable for anyone to expect anything to be _perfect_. I'm not saying you are, I'm only sharing my philosophy on the matter. :)
> 
> Feature comparisons could serve as red herring (a distraction) and could be seen as promoting the use of a competitor's plugin, even if you're trying to convince me to buy ChC Pro. So I'll just say that with a little bit of searching, the answers are out there and can be found in under 2 minutes (just not in the same place). I have no plans to use channels atm. And for as long as MineChat is around, I don't intend to use DiscordSRV, unless I can't figure out Slack integration with Admin/Staff Chat as we had on Saico (they don't use ChC). But that's a separate topic, since it'd likely be a separate custom plugin or a BungeeControl feature request.

Hm, i not say buy the plugin. What I have experience with chat control pro, shall I say I should think twice before buy. 

First dev say it recommend use chc site for bug reports and one in chc staff start to close threads on github and say use chc site for bugreports. 

The main developer say fast on spigot you can use github for bug reports. 

It was even they has released 9.0 it had serious problems, every update broke something new. 

He force to roll back to 8 again and he some has done most of the work on 9 he not work on chc any more (that dev say).

It took 20 days for him to see he not have support for auto join spy on channels and when he fix it all players auto join spy (is a local chanel for players chat in close area). Some I want have options to spy on. He has fix it, but now players not auto join readmode on channels.

**Comment by broken1arrow** [comment] 2020-10-05 04:45
But one thing I can cred him for he fix the problem and not blame on other plugin I have installed.

**Comment by kangarko** [comment] 2020-10-06 14:22
Awesome suggestion, I have implemented it right away to upcoming ChatControl 9.1.

Don't buy it right now, it's going to be a heavy change, I recommend you read our Overview sales letter then decide. The free version is not receiving new features.

The BungeeCord server naming issues have been resolved in 8.8.x already.

@broken1arrow I apology for the errors in our past management, I let go of these developers months ago. The only official support place is GitHub and SpigotMC private messages. Not a single time I closed a ticket without an answer. Things have been busy lately due to works on ChatControl 9, but I made commitment to reply to all tickets within 1-4 days and most of the time it's been helt.

Are you still experiencing the "now players not auto join readmode on channels" problem? I just tested it out for you and it appears to be resolved: https://i.imgur.com/SRg7a2i.png

**Comment by broken1arrow** [comment] 2020-10-06 14:37
> 
> 
> Awesome suggestion, I have implemented it right away to upcoming ChatControl 9.1.
> 
> Don't buy it right now, it's going to be a heavy change, I recommend you read our Overview sales letter then decide. The free version is not receiving new features.
> 
> The BungeeCord server naming issues have been resolved in 8.8.x already.
> 
> @broken1arrow I apology for the errors in our past management, I let go of these developers months ago. The only official support place is GitHub and SpigotMC private messages. Not a single time I closed a ticket without an answer. Things have been busy lately due to works on ChatControl 9, but I made commitment to reply to all tickets within 1-4 days and most of the time it's been helt.
> 
> Are you still experiencing the "now players not auto join readmode on channels" problem? I just tested it out for you and it appears to be resolved: https://i.imgur.com/SRg7a2i.png

Yes was not you some close the treads, so I not blame you directly (mistakes happen). Support work much better an some other plugin some are free or you pay for.

The problem is when the player joins then he is in four channels, but if he switches between these, all but the one he is in disappear.

Player join
![2020-10-06_16 36 31](https://user-images.githubusercontent.com/16368286/95216240-2047f980-07f2-11eb-88e6-ac2a241b4a92.png)

change channels
![2020-10-06_16 35 31](https://user-images.githubusercontent.com/16368286/95216283-2d64e880-07f2-11eb-820b-ef4d7f76b67f.png)

**Comment by kangarko** [comment] 2020-10-06 14:52
What command did you type between these two screenshots? Please attach me your channels.yml file.

**Comment by broken1arrow** [comment] 2020-10-06 16:37
/ch join mc-lokalt /ch join mc-✆hjälp and last /ch join mc-globalt 


[channels.zip](https://github.com/kangarko/ChatControl-Pro/files/5335334/channels.zip)

**Comment by broken1arrow** [comment] 2020-10-08 13:39
> 
> 
> What command did you type between these two screenshots? Please attach me your channels.yml file.

has you see I send channels zip and what command i use?

**Comment by broken1arrow** [comment] 2020-10-09 06:40
St

> 
> 
> What command did you type between these two screenshots? Please attach me your channels.yml file.

Still not work in 8.8.15

**Comment by kangarko** [comment] 2020-10-12 18:19
Thank you, what's your SpigotMC username please? I am afraid I cannot get this to work in ChatControl 8 but I can send you an early ChatControl 9 version and you can tell me if it is working as you wished. Then we can tweak it and make it work for you.

Just PM me on SpigotMC.

**Closed by kangarko** 2020-10-12 18:19 UTC
Labels: improvement

**Comment by broken1arrow** [comment] 2020-10-12 20:43
> 
> 
> Thank you, what's your SpigotMC username please? I am afraid I cannot get this to work in ChatControl 8 but I can send you an early ChatControl 9 version and you can tell me if it is working as you wished. Then we can tweak it and make it work for you.
> 
> Just PM me on SpigotMC.

Almost same name has here. Broken_arrow

**Comment by kangarko** [comment] 2020-10-13 17:45
Awesome I will message it to you once it is ready!
