### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#439] opened 2017-10-22 12:17 UTC
Getting this error upon startup. I dont use discordsrv.

```
Configuration loads..
Update settings.yml at 'Private_Messages.Toast.Enabled' -> 'true'
Update settings.yml at 'Private_Messages.Toast.Format' -> '[{sender} -> you]{dynamic_spaces}{message}'
Update settings.yml at 'Variables.Replace_In_Custom' -> 'true'
Saved updated file: settings.yml (# Comments removed)
Using locale from file: messages_en.yml
at me.kangarko.chatcontrol.final..\... .LPt7$super.const(SourceFile:102)
at me.kangarko.chatcontrol.final..\... .LPt7$super.const(SourceFile:95)
at me.kangarko.chatcontrol.final..\... .LPt7.strictfp(SourceFile:40)
at me.kangarko.chatcontrol.final..\... .LPt7.native(SourceFile:36)
at me.kangarko.chatcontrol.final..\... .LPt9.onEnable(SourceFile:145)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:386)
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:335)
at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292)
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
at java.lang.Thread.run(Thread.java:748)
_ _ _ 
| | | | ___ ___ _ __ ___| |
| |_| |/ _ \ / _ \| '_ \/ __| |
| _ | (_) | (_) | |_) \__ \_|
|_| |_|\___/ \___/| .__/|___(_)
|_| 
!-----------------------------------------------------!
Error loading ChatControl v7.6.4, plugin is disabled!
Running on 1.12.2-R0.1-SNAPSHOT (v1_12_R1) & Java 1.8.0_144
!-----------------------------------------------------!
Error: github.scarsz.discordsrv.DiscordSRV
!-----------------------------------------------------!
```

Also read your discord msgs xD

**Comment by kangarko** [comment] 2017-10-22 12:35
Hello,

The error is caused by missing discordsrv plugin, that will be fixed.

Usually I respond quickest over here (email notifications) or via PM.

**Closed by kangarko** 2017-10-22 12:35 UTC
