### ISSUE TITLE
Ignore username doesn't work

### ISSUE THREAD

**Issue by Kira07** [kangarko/ChatControl-Pro#573] opened 2018-01-15 22:54 UTC
Log:

[15.01.2018 13:03:02] Relaktor: [Handler=insultes, Rule ID=ta mère] /r moi TaMereEnSlip

Rule:

match t+(\W|\d|_)*a+(\W|\d|_)*m+(\W|\d|_)*(e|[^a-zA-Z])+(\W|\d|_)*r+(\W|\d|_)*e|t+(\W|\d|_)*a+(\W|\d|_)*d+(\W|\d|_)*(a|[^a-zA-Z])+(\W|\d|_)*r+(\W|\d|_)*(o|[^a-zA-Z])+(\W|\d|_)*n+(\W|\d|_)*e
ignore usernames
before strip x
id ta mère
handle as insultes

**Comment by x1p** [comment] 2018-01-17 13:55
I can't read French, but above rule requires a space or something between ta and mere. And the message does not have a space.
(\W|\d|) imho should very well be (\W|\d)
Furthermore I think above rule a bit too complicated and could very well be a lot more simple. Have you considered "Translate_Diacritical_Marks"

**Comment by kangarko** [comment] 2018-01-17 16:05
Works for me just the exact version as you posted @Kira07,

![b](https://i.imgur.com/ErbmJYL.png)
![c](https://i.imgur.com/e2ADo7i.png)

What's your MC version? Also post me your settings.yml for control.

**Comment by Kira07** [comment] 2018-01-17 16:18
Maybe the issue can only be reproduced with commands ?
I use tacospigot 1.8.8 and here is my settings.yml : `# -------------------------------------------------------------------------------------------
# 
#  Your file has been automatically updated at 15.01.2018 05:05:42
#  to ChatControl 7.6.32
# 
#  Unfortunatelly, due to how Bukkit saves all .yml files, it was not possible
#  preserve the documentation comments in your file. We apologies.
# 
#  If you'd like to view the default file, you can either:
#  a) Open the ChatControl-7.6.32.jar with a WinRar or similar
#  b) or, visit: https://github.com/kangarko/ChatControl-Pro/wiki
# 
# -------------------------------------------------------------------------------------------

Anti_Bot:
  Cooldown:
    Rejoin: 0
    Chat_After_Login: 0
    Command_After_Login: 0
  Block_Chat_Until_Moved: true
  Block_Commands_Until_Moved:
  - /afk
  - /me
  Show_Quit_Message_Only_If_Logged: true
  Block_Signs_With_Same_Text: true
  Disallowed_Nicknames:
  - Erisium
Anti_Caps:
  Enabled: true
  Enabled_In_Commands: false
  Commands_To_Apply:
  - /msg
  - /tell
  Points:
    Warn_Set: spam
    Amount: 0
  Ignore_Usernames: false
  Min_Message_Length: 5
  Min_Caps_Percentage: 50
  Min_Caps_In_A_Row: 5
  Whitelist:
  - OMG
  - LOL
  - WTF
  - WOW
  - ROFL
  - LMAO
Anti_Spam:
  Similarity_Check:
    Ignore_Special_Characters: false
    Ignore_Duplicate_Characters: false
    Ignore_First_Arguments_In_Commands: true
  Regex_In_Whitelists: false
  Commands:
    Command_Delay: 0
    Delay_Points:
      Warn_Set: fastmessages
      Amount: 0
    Similar_Percentage_Block: 99
    Similarity_Points:
      Warn_Set: spam
      Amount: 0
    Whitelist_Works_Like_Blacklist: true
    Whitelist_Similarity:
    - /tell
    - /pm
    - /msg
    Whitelist_Delay:
    - /spawn
    - /hello
    Handle_As_Chat:
    - /me
  Chat:
    Message_Delay: 3
    Delay_Points:
      Warn_Set: fastmessages
      Amount: 0
    Similar_Percentage_Block: 70
    Similarity_Message_Check_Count: 4
    Similarity_Points:
      Warn_Set: spam
      Amount: 0
    Whitelist_Similarity:
    - hello
    - hey
    Whitelist_Delay:
    - mutede1hstpbs
Grammar:
  Insert_Dot:
    Enabled: false
    Min_Message_Length: 5
  Capitalize:
    Enabled: true
    Min_Message_Length: 5
Clear:
  Broadcast: true
  Do_Not_Clear_For_Staff: false
  Console_Lines: 300
Mute:
  Broadcast: true
  Prevent:
    Writing_Books: false
    Placing_Signs: true
  Silence:
    Join_Messages: true
    Quit_Messages: true
    Death_Messages: true
  Disabled_Commands:
  - me
  - tell
  - msg
  - r
  - w
Announcer:
  Bungee: true
  Ignore_Self: false
  Log_To_Console: true
  Sound: ENTITY_ARROW_HIT_PLAYER, 1.0, 0.1
Admin_Chat:
  Bungee: true
  Log_To_Console: true
  Write_To_File: true
  Discord_Channel: admin
Bungee_Chat:
  Enabled_By_Default: false
  Log_To_Console: true
  Write_To_File: true
  Discord_Channel: global
Private_Messages:
  Enabled: false
  Bungee: false
  Aliases:
    Tell:
    - tell
    - msg
    - t
    - whisper
    Reply:
    - reply
    - r
    TogglePM:
    - togglepm
    - ignorepm
    - nopm
  Format_Sender: Private_Message_Sender
  Format_Receiver: Private_Message_Receiver
  Register_Reply_To_Self: true
  Toast:
    Enabled: true
    Format: '&6[{sender} &8-> &6you]{dynamic_spaces}&7{message}'
  Deny_Message_Self: false
Ignore:
  Enabled: false
  Aliases:
  - ignore
  - ign
  Chat: true
  Private_Messages: true
Packets:
  Enabled: true
  Tab_Complete:
    Disable: false
    Disable_Only_In_Commands: false
    Allow_When_Message_Has_Space: false
    Allow_When_Length_Above: 0
    Hide_Vanished_Players:
      Enabled: false
      Maximum_Length: 20
Rules:
  Verbose: true
  Bungee: true
  Chat: true
  Commands: true
  Packets: true
  Signs:
    Check: true
    Block: true
    Drop: true
  Books:
    Check: true
    Replace: true
  Anvil:
    Check: true
    Replace: true
  Chat_Ignorer:
    Enabled: false
    Sets:
      swear:
        Ignored_By_Default: false
Console_Filter:
  Enabled: false
  Log: false
  Filter_Console_Messages:
  - Reached end of stream for
  - Connection reset
Sound_Notify:
  Enabled: true
  Cooldown: 10 seconds
  Require_Afk: false
  Require_Prefix: '@'
  Sound: CHICKEN_EGG_POP, 1F, 1.5F
  Color: '&a'
  Enabled_In_Commands:
  - msg
  - m
  - reply
  - tell
  - t
  - w
  - r
Groups:
  Enabled: false
  List:
    vip:
      Message_Delay: 0
      Command_Delay: 0
Points:
  Enabled: true
  Repeat_Last_Action: true
  Smart_Warnings: true
  Reset_Task:
    Repeat_Every_Seconds: 60000
    Remove:
      global: 5
      adresse: 1
      provoc: 10
      pub: 1
      swear: 3
  Warn_Sets:
    adresse:
      '1':
      - warn &7Merci de respecter les &2règles du serveur &7sous peine de &4sanction&7.
      '5':
      - |-
        warn &c**** &lHey &c{player} ****
         &7-> &c6Dernier &cavertissement !
      '15':
      - kick {player} &cMerci de respecter les règles
    swear:
      '2':
      - kick {player} &cLangage incorrect (dernier avertissement avant le mute)
      '3':
      - sudo {player} c:mutede1hstpbs
      '4':
      - sudo {player} c:mutede2hstpbs
      '5':
      - sudo {player} c:mutede5hstpbs
    provoc:
      '2':
      - warn &cPremier avertissement pour provocation.
      '4':
      - warn &cMerci de ne pas provoquer sous peine de sanctions sévères !
      '6':
      - kick {player} &cProvocation (dernier avertissement avant le mute)
      '7':
      - sudo {player} c:mutede1hstpbs
      '8':
      - sudo {player} c:mutede2hstpbs
      '9':
      - sudo {player} c:mutede5hstpbs
    pub:
      '2':
      - warn &cSi vous continuez, vous serez sanctionné plus sévèrement.
      '4':
      - kick {player} &cPub interdite ! (Dernier avertissement)
      '6':
      - tempban {player} 1d &7[BloodGuard] &aVous avez été sanctionné pour pub &7(&cban de 24h&7)
    fastmessages:
      '3':
      - warn &cPlease slow down chat messages.
      '5':
      - warn &cSlow down chat, otherwise you will be banned.
      '7':
      - kick {player} &cSlow down chat (last warning)
      '9':
      - tempban {player} 10m autoban for chat spam
Variables:
  Custom_Enabled: true
  Vault:
    Multi_Prefix: false
    Multi_Suffix: false
  Replace_In_Custom: true
  Replace_Own_In_Custom: false
Writer:
  Enabled: false
  Ignore_Players:
  - ignoredAdmin
  Commands:
  - me
  - msg
  - m
  - tell
  - t
  - reply
  - r
  - mail
Motd:
  Enabled: false
  Delay_Ticks: 2
  Sound: ENTITY_FIREWORK_LAUNCH, 1F, 0.1F
  Message:
  - '&8*--------------------------------------------------*'
  - '&fHello {player}, we kindly welcome you to &e{server_name}&f and wish you great
    experience :)'
  - \n
  - '&6Version: &f{nms_version} &7/&f 08.04.2017'
  - '&6Changelog:'
  - ' &7- &fAdded ChatControl Pro plugin'
  - \n
  - '&6Help &7- &f/help &6Settings &7- &f/menu &6Web &7- &f/web'
  - '&8*--------------------------------------------------*'
Spy:
  Enabled: true
  Command_Aliases:
  - spy
  - socialspy
  Format: '&8[spy] {player}: &7{message}'
  Channel_Prefix: '&8[spy] '
  Bungee: false
  Command_List_Works_Like_Blacklist: false
  Command_List:
  - /tell
  - /msg
  - /t
  - /whisper
  - /r
  - /reply
BungeeCords:
  Enabled: true
  Prefix: '&5[Bungee/{server_name}] &7'
MySQL:
  Enabled: false
  Connection:
    Host: localhost
    Database: minecraft
    Port: '3306'
    User: ''
    Password: ''
    Table_Prefix: ChatControl_
    Connector_Advanced: jdbc:mysql://{host}:{port}/{database}?autoReconnect=true
  Aggressive: false
Debugger:
  Sections: []
  Keys: ''
  Save: true
  Log: false
Listener_Priority:
  Formatter: NORMAL
  Checker: LOWEST
  Signs: HIGHEST
Command_Aliases:
- chatcontrol
- chc
Translate_Diacritical_Marks: true
Locale: en
Regex_Timeout_Milis: 100
Log_Lag_Over_Milis: 100
Silent_Startup: false
Regex_Strip_Colors: true
Reset_Cache_On_Quit: false
Enforce_New_Line: false
Server_Name: default
Check_Updates: true
Debug: false
Version: 18
Clear_Data_If_Inactive: 30 days
`

**Comment by kangarko** [comment] 2018-01-17 16:39
Thanks. Still cannot reproduce. What's your handlers.yml?

**Comment by Kira07** [comment] 2018-01-17 16:43
https://hastebin.com/kuvasafogo.bash

**Comment by kangarko** [comment] 2018-01-17 17:24
I am sorry I can't reproduce, all works for me.

Eventually you can add this to the rule:

`ignore string TaMereEnSlip`

**Comment by Kira07** [comment] 2018-01-17 17:39
That's weird, alright

**Comment by kangarko** [comment] 2018-01-22 21:09
Closing, let me know if anything else arises.

**Closed by kangarko** 2018-01-22 21:09 UTC
Labels: Issue: cannot reproduce
