### ISSUE TITLE
Problem With Books And AntiSpam

### ISSUE THREAD

**Issue by MatinDark** [kangarko/ChatControl-Pro#597] opened 2018-02-11 15:45 UTC
Hello  i use Chatcontrolpro 7.6.34 On My BungeeCord and Stand Alone Servers has different versions for example 
skyblock : paperspigot 1.12.1
survival : 1.9.4
and .....

all works fine but swear and ads don't blocks on book either i enable book check on settings.yml i don't know why but on signs and server chat is fine

my second problem is about survival running on spigot 1.9.4 command antispam is not work on that server and players can spam /msg /tell /tpa /tpahere and other i enable use whitelist as blacklist on my settings.yml but there is no change on other server like skyblock kitpvp and .... is ok i only have antispam issue on survival

**Comment by kangarko** [comment] 2018-02-12 10:54
Hello!

1) What server version are you using where book filtering doesn't work?

2) Please post me your settings.yml to pastebin.com from that server. Make sure to remove MySQL sensitive parts.

**Comment by MatinDark** [comment] 2018-02-12 12:28
Hello There I say i use on bungeecord server and stand alone server has different versions but there is no matter because that wasn't work on any version on my server but for example is send this settings.yml from my survival server on 1.9.4 spigot and antispam and anti book ad and swear dosen't work
https://hastebin.com/gurafugila.php 
and i don't use mysql and there is no sensitive parts !

**Comment by kangarko** [comment] 2018-02-16 09:16
Hey, sorry for the delay, I could not reproduce it from testing but I will get to more testing after 19th.

Please also note that those things only work locally, and not over bungee.

**Comment by kangarko** [comment] 2018-03-11 11:58
Sorry for late reply, I could not again reproduce by testing, I am closing this in faith you have resolved it on your side. Correct me if this is not the case.

**Closed by kangarko** 2018-03-11 11:58 UTC
Labels: Issue: complaint, Status: queued

**Comment by MatinDark** [comment] 2018-03-11 13:02
hello still not working on new versions too

**Comment by kangarko** [comment] 2018-03-11 16:49
Hey, in the next version set Debug to "rules_books" as per the image below and post me the console messages when someone attempts to violate a rule in a book but it doesn't get blocked.

![a](https://i.imgur.com/5BV6xmE.png)

**Comment by kangarko** [comment] 2018-03-11 16:50
Hey, in the next version set Debug to "rules_books" as per the image below and post me the console messages when someone attempts to violate a rule in a book but it doesn't get blocked.

![a](https://i.imgur.com/5BV6xmE.png)

If the anti-spam still doesn't work, please try adjusting the priority of Checker to HIGHEST or MONITOR as per https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities.

**Comment by MatinDark** [comment] 2018-03-11 17:47
Anti-spam and others work find but book filter doesn't work i am going to enable debug message for book  tomorrow thanks for your help <3

**Comment by kangarko** [comment] 2018-03-11 18:33
Please, wait for the next release because the debug messages are not in the current version. Thanks!

**Comment by MatinDark** [comment] 2018-03-12 19:16
Hello wow New update is ❤️ so good ❤️ all work great now on 1.12.x servers but book ads problem on 1.9.4  still happening and i enable debug for books but there is no message on console when they are advertise ! ( thanks for new things add on new update and if you can please add hook to litebans plugin so that when we mute a player he wont be able to write on signs and books)  😉

**Comment by kangarko** [comment] 2018-03-15 10:00
Oh I reviewed the API and found that the "book event" is not available for 1.9.4, so there is no way for us to know when a book is edited. Sorry for that! I will include this on the wiki as a notice.
