### ISSUE TITLE
Not working on cauldron-1.7.10-2.1403.1.54

### ISSUE THREAD

**Issue by xyblues** [kangarko/ChatControl-Pro#125] opened 2016-11-23 00:18 UTC
I use default config.
Why is that?
![image](https://cloud.githubusercontent.com/assets/15712089/20547153/39700d6e-b155-11e6-8b2f-8b900393791b.png)

**Comment by kangarko** [comment] 2016-11-23 17:10
It appears as a problem with encoding.

Even if you opened the default config and saved it again, the encoding might have been changed to some type that is unsupported by bukkit/chc. Ensure you are saving the file in UTF-8 format. You are recommended to use Notepad++ (on Windows) and save the file in utf-8 (without bom) encoding.

**Comment by xyblues** [comment] 2016-11-24 00:00
I already use utf-8 (without bom) encoding.
But it still doesn't work.
ChatControl v5.3.8 work very well.
![image](https://cloud.githubusercontent.com/assets/15712089/20582313/11a09dfa-b21b-11e6-91f8-4765996f6b04.png)

**Comment by kangarko** [comment] 2016-11-29 18:58
That's odd. I can't reproduce it.

Perhaps the old 1.7.10 version only allows ANSI formatting on your system. Please try it and give me feedback :)

**Comment by xyblues** [comment] 2016-11-29 19:58
It still does not work.......
Windows Server 2008 R2

**Comment by kangarko** [comment] 2016-12-04 13:22
I am sorry. I have installed Cauldron and I cannot reproduce it. Both UTF-8 and ANSI encodings works for me.

If you say you are using the default settings.yml, please try to removing that file so the plugin will regenerate it.

**Comment by kangarko** [comment] 2016-12-26 11:25
Closing. Please remind me if issues persist.

**Closed by kangarko** 2016-12-26 11:25 UTC
Labels: issue, wontfix

**Comment by xyblues** [comment] 2016-12-26 11:30
Problems still exist I can only be forced to use ChatControl.

**Comment by kangarko** [comment] 2016-12-26 11:48
Please try to rename your settings.yml to settings_old.yml so it will regenerate.
